### ISSUE TITLE
ERROR: UnboundLocalError: local variable 'key' referenced before assignment

### ISSUE THREAD

**Issue by g2290412** [NVIDIA/DIGITS#1044]
Digits 4.1 dev
NVcaffe 0.15.13

I got this error trying to create a "object detection" dataset. I can create a "image classification" dataset without problems. Tried change some parameters and the images. Maybe i'm doing something wrong...

I'm using a folder for each validation/training images/label... label: a empty ".txt" file with the name of related  image: 01_y.jpg - 01_y.txt (tried with just numbers without success)
 

`Default value for torch_root "<PATHS>" invalid:
torch binary not found in PATH
2016-09-06 09:12:34 [ERROR] UnboundLocalError: local variable 'key' referenced before assignment
Traceback (most recent call last):
File "/home/user/folder/DIGITS/tools/create_generic_db.py", line 468, in <module>
args['stage']
File "/home/user/folder/DIGITS/tools/create_generic_db.py", line 433, in create_generic_db
force_same_shape)
File "/home/user/folder/DIGITS/tools/create_generic_db.py", line 284, in create_db
entry_ids = extension.itemize_entries(stage)
File "/home/user/folder/DIGITS/digits/extensions/data/objectDetection/data.py", line 188, in itemize_entries
self.load_ground_truth(self.train_label_folder)
File "/home/user/folder/DIGITS/digits/extensions/data/objectDetection/data.py", line 213, in load_ground_truth
datasrc.load_gt_obj()
File "/home/user/folder/DIGITS/digits/extensions/data/objectDetection/utils.py", line 207, in load_gt_obj
self.update_objects_all(key, objects_per_image)
UnboundLocalError: local variable 'key' referenced before assignment`

**Comment by gheinrich** [comment]
Hello, can you review [the object detection label format](https://github.com/NVIDIA/DIGITS/tree/v4.0.0/digits/extensions/data/objectDetection#label-format) and see if your labels have the expected format? Also have a look at the [object detection walk-through](https://github.com/NVIDIA/DIGITS/tree/master/examples/object-detection) for some background information.

**Comment by g2290412** [comment]
You are right, the format of my labels are wrong, thank you for help
