### ISSUE TITLE
"python -m digits.download_data" fails with TypeError exception

### ISSUE THREAD

**Issue by milijan** [NVIDIA/DIGITS#1150]
using the python script described in the wiki to download dataset fails with the following error:

[milijan@OAK digits]$ python -m digits.download_data cifar10 ../cifar10
Downloading url=http://www.cs.toronto.edu/~kriz/cifar-10-python.tar.gz ...
Uncompressing file=cifar-10-python.tar.gz ...
Extracting images file=../cifar10/cifar-10-batches-py/data_batch_1 ...
Traceback (most recent call last):
  File "/usr/lib64/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib64/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/data/digits/digits/download_data/__main__.py", line 44, in <module>
    d.getData()
  File "digits/download_data/downloader.py", line 34, in getData
    self.processData()
  File "digits/download_data/cifar10.py", line 57, in processData
    self.__extractData(filepath, phase, label_names)
  File "digits/download_data/cifar10.py", line 102, in __extractData
    PIL.Image.fromarray(image).save(filename)
  File "/usr/lib64/python2.7/site-packages/PIL/Image.py", line 1477, in save
    save_handler(self, fp, filename)
  File "/usr/lib64/python2.7/site-packages/PIL/PngImagePlugin.py", line 608, in _save
    ImageFile._save(im, _idat(fp, chunk), [("zip", (0,0)+im.size, 0, rawmode)])
  File "/usr/lib64/python2.7/site-packages/PIL/ImageFile.py", line 456, in _save
    e = Image._getencoder(im.mode, e, a, im.encoderconfig)
  File "/usr/lib64/python2.7/site-packages/PIL/Image.py", line 395, in _getencoder
    return encoder(mode, *args + extra)
TypeError: function takes at most 4 arguments (6 given)

**Comment by milijan** [comment]
My issue was related to PIL/Pillow install and was fixed by uninstalling PIL. I'll leave this issue open in case there is a more elegant way to handle the error.

**Comment by lukeyeager** [comment]
What platform are you on? Who uses `/usr/lib64/`?

**Comment by lukeyeager** [comment]
It certainly does look like a problem with your PIL installation. Thanks for reporting back.

**Comment by milijan** [comment]
no worries. Cheers.
