### ISSUE TITLE
async_mode error running digits-devserver

### ISSUE THREAD

**Issue by michaelholm-ce** [NVIDIA/DIGITS#1195]
Hello -- I've researched related issues and posts related to the below error.  In particular, I have run ```sudo pip install -r requirements.txt```, but the error persists.  

I'm running digits 5.1-dev on Ubuntu14.04 and Caffe 0.15.3.

Error message:
```
sudo ./digits-devserver 
  ___ ___ ___ ___ _____ ___
 |   \_ _/ __|_ _|_   _/ __|
 | |) | | (_ || |  | | \__ \
 |___/___\___|___| |_| |___/ 5.1-dev

Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/exx/12TB/image_recognition/DIGITS/digits/__main__.py", line 66, in <module>
    main()
  File "/home/exx/12TB/image_recognition/DIGITS/digits/__main__.py", line 51, in main
    import digits.webapp
  File "digits/webapp.py", line 25, in <module>
    socketio = SocketIO(app, async_mode='gevent')
TypeError: __init__() got an unexpected keyword argument 'async_mode'
Exception KeyError: KeyError(139774545760816,) in <module 'threading' from '/usr/lib/python2.7/threading.pyc'> ignored
```

**Comment by LucMioulet** [comment]
You need to install the requirements : 
pip install -r requirements.txt

**Comment by michaelholm-ce** [comment]
Yes, I have done that (please see my issue description), and requirements installed successfully, but the error persists.

**Comment by LucMioulet** [comment]
It might be a conflict between certain versions of packages. Flask and gevent ?

**Comment by lukeyeager** [comment]
This looks problematic:
```
Found existing installation: Flask-SocketIO 0.6.0
    Not uninstalling Flask-SocketIO at /usr/lib/python2.7/dist-packages, owned by OS
  Running setup.py install for Flask-SocketIO
```
Which installation of Flask-SocketIO are you picking up?
```sh
# mine comes from /usr/lib/
$ python -c 'import flask_socketio; print flask_socketio.__file__'
/usr/lib/python2.7/dist-packages/flask_socketio/__init__.pyc

# which is provided by a deb package
$ dpkg -S /usr/lib/python2.7/dist-packages/flask_socketio
python-flaskext.socketio: /usr/lib/python2.7/dist-packages/flask_socketio

# and my installed version is 2.6
$ apt-cache policy python-flaskext.socketio
python-flaskext.socketio:
  Installed: 2.6-1ppa1
  Candidate: 2.6-1ppa1
  Version table:
 *** 2.6-1ppa1 500
        500 http://ppa.launchpad.net/luke-yeager/digits/ubuntu xenial/main amd64 Packages
        500 http://ppa.launchpad.net/luke-yeager/digits/ubuntu xenial/main i386 Packages
        100 /var/lib/dpkg/status
     2.6-1 500
        500 file:/usr/local/repo ./ Packages
        500 http://sqrl.nvidia.com/data/repos/machine-learning.debian/xenial/7.0-devel+cuda8.0  Packages
```

**Comment by michaelholm-ce** [comment]
Thanks for your prompt replies!  

@LucMioulet:  When I tried ```sudo pip uninstall flask``` or ```sudo pip uninstall gevent```, It fails with ```Not uninstalling Flask at /usr/lib/python2.7/dist-packages, owned by OS```.  Not sure how to proceed there.

@lukeyeager:  I have identical outputs for your first two commands, but the third reveals an older version:
```
apt-cache policy python-flaskext.socketio
python-flaskext.socketio:
  Installed: 0.6.0-2
  Candidate: 0.6.0-2
  Version table:
 *** 0.6.0-2 0
        100 /var/lib/dpkg/status
```
It looks like the problem is not being able to uninstall the older version of flask.

**Comment by lukeyeager** [comment]
Here's what I'd do:
```sh
sudo apt-get install virtualenv

# create a venv that can use python packages installed with apt-get
virtualenv --system-site-packages venv

# activate the venv
source venv/bin/activate

# try installing the requirements again
pip install -r requirements.txt
```
I think that will let you install the newer version of Flask-SocketIO into your virtual environment.

Otherwise, you can remove the flask-socketio deb package (note: this will probably force the removal of your old digits package, too):
```sh
sudo apt-get remove python-flaskext.socketio
```

**Comment by michaelholm-ce** [comment]
@lukeyeager:  The first strategy did not successfully uninstall flask-socket-io, but I am now in a virtualenv.  The second strategy ran successfully, and when I reran ```sudo pip install -r requirements.txt```, I have the following output:
```
sudo pip install -r requirements.txt 
Requirement already satisfied (use --upgrade to upgrade): Pillow>=2.3.0,<=3.1.2 in /usr/lib/python2.7/dist-packages (from -r requirements.txt (line 1))
Requirement already satisfied (use --upgrade to upgrade): numpy>=1.8.1,<=1.11.0 in /usr/lib/python2.7/dist-packages (from -r requirements.txt (line 2))
Requirement already satisfied (use --upgrade to upgrade): scipy>=0.13.3,<=0.17.0 in /usr/lib/python2.7/dist-packages (from -r requirements.txt (line 3))
Requirement already satisfied (use --upgrade to upgrade): protobuf>=2.5.0,<=2.6.1 in /usr/lib/python2.7/dist-packages (from -r requirements.txt (line 4))
Requirement already satisfied (use --upgrade to upgrade): six>=1.5.2,<=1.10.0 in /usr/lib/python2.7/dist-packages (from -r requirements.txt (line 5))
Requirement already satisfied (use --upgrade to upgrade): requests>=2.2.1,<=2.9.1 in /usr/lib/python2.7/dist-packages (from -r requirements.txt (line 6))
Requirement already satisfied (use --upgrade to upgrade): gevent>=1.0,<=1.1.0 in /usr/lib/python2.7/dist-packages (from -r requirements.txt (line 7))
Requirement already satisfied (use --upgrade to upgrade): gevent-websocket==0.9.3 in /usr/lib/python2.7/dist-packages (from -r requirements.txt (line 8))
Requirement already satisfied (use --upgrade to upgrade): Flask==0.10.1 in /usr/lib/python2.7/dist-packages (from -r requirements.txt (line 9))
Requirement already satisfied (use --upgrade to upgrade): Flask-WTF>=0.11,<=0.12 in /usr/lib/python2.7/dist-packages (from -r requirements.txt (line 10))
Requirement already satisfied (use --upgrade to upgrade): wtforms>=2.0,<=2.1 in /usr/lib/python2.7/dist-packages (from -r requirements.txt (line 11))
Requirement already satisfied (use --upgrade to upgrade): Flask-SocketIO==2.6 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 12))
Requirement already satisfied (use --upgrade to upgrade): setuptools>=3.3,<=20.7.0 in /usr/lib/python2.7/dist-packages (from -r requirements.txt (line 13))
Requirement already satisfied (use --upgrade to upgrade): lmdb==0.87 in /usr/lib/python2.7/dist-packages (from -r requirements.txt (line 14))
Requirement already satisfied (use --upgrade to upgrade): h5py>=2.2.1,<=2.6.0 in /usr/lib/python2.7/dist-packages (from -r requirements.txt (line 15))
Requirement already satisfied (use --upgrade to upgrade): pydot>=1.0.28,<=1.0.29 in /usr/lib/python2.7/dist-packages (from -r requirements.txt (line 16))
Requirement already satisfied (use --upgrade to upgrade): psutil>=1.2.1,<=3.4.2 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 17))
Requirement already satisfied (use --upgrade to upgrade): matplotlib>=1.3.1,<=1.5.1 in /usr/lib/pymodules/python2.7 (from -r requirements.txt (line 18))
Requirement already satisfied (use --upgrade to upgrade): scikit-fmm>=0.0.9 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 19))
Requirement already satisfied (use --upgrade to upgrade): Werkzeug>=0.7 in /usr/lib/python2.7/dist-packages (from Flask==0.10.1->-r requirements.txt (line 9))
Requirement already satisfied (use --upgrade to upgrade): Jinja2>=2.4 in /usr/lib/python2.7/dist-packages (from Flask==0.10.1->-r requirements.txt (line 9))
Requirement already satisfied (use --upgrade to upgrade): itsdangerous>=0.21 in /usr/lib/python2.7/dist-packages (from Flask==0.10.1->-r requirements.txt (line 9))
Requirement already satisfied (use --upgrade to upgrade): python-socketio>=1.4 in /usr/local/lib/python2.7/dist-packages (from Flask-SocketIO==2.6->-r requirements.txt (line 12))
Requirement already satisfied (use --upgrade to upgrade): python-engineio>=0.9.2 in /usr/local/lib/python2.7/dist-packages (from Flask-SocketIO==2.6->-r requirements.txt (line 12))
Requirement already satisfied (use --upgrade to upgrade): pyparsing in /usr/lib/python2.7/dist-packages (from pydot>=1.0.28,<=1.0.29->-r requirements.txt (line 16))
Requirement already satisfied (use --upgrade to upgrade): python-dateutil in /usr/lib/python2.7/dist-packages (from matplotlib>=1.3.1,<=1.5.1->-r requirements.txt (line 18))
Requirement already satisfied (use --upgrade to upgrade): tornado in /usr/lib/python2.7/dist-packages (from matplotlib>=1.3.1,<=1.5.1->-r requirements.txt (line 18))
Requirement already satisfied (use --upgrade to upgrade): nose in /usr/lib/python2.7/dist-packages (from matplotlib>=1.3.1,<=1.5.1->-r requirements.txt (line 18))
Requirement already satisfied (use --upgrade to upgrade): markupsafe in /usr/lib/python2.7/dist-packages (from Jinja2>=2.4->Flask==0.10.1->-r requirements.txt (line 9))
Cleaning up...
```
which looks good.  However, when I run ```sudo ./digits-devserver```, I now have this output:
```
The gevent-socketio package is incompatible with this version of the Flask-SocketIO extension. Please uninstall it, and then install the latest version of python-socketio in its place.
```

**Comment by lukeyeager** [comment]
This is why you're seeing that error:

> ## Upgrading to Flask-SocketIO 1.x and 2.x from the 0.x releases
If you wish to continue using gevent, then uninstall gevent-socketio from your virtual environment, as this package is not used anymore and may collide with its replacement, python-socketio.
https://flask-socketio.readthedocs.io/en/latest/#upgrading-to-flask-socketio-1-x-and-2-x-from-the-0-x-releases

To remove the troublesome deb package:
```sh
sudo apt-get remove python-gevent-socketio
```
Alternatively, you can start with a clean virtualenv and install all the requirements from scratch:
```sh
# shut down and remove the old venv
deactivate
rm -rf venv

# make and activate a new one (without the --sytem-site-packages flag)
virtualenv venv
source venv/bin/activate

# install only what you need
pip install -r $CAFFE_ROOT/python/requirements.txt
pip install -r $DIGITS_ROOT/requirements.txt
```

**Comment by michaelholm-ce** [comment]
@lukeyeager:  The first approach returns 
```
sudo apt-get remove python-gevent-socketio
[sudo] password for exx: 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package python-gevent-socketio
```
I tried the second approach, too, with _sudo_, and I'm getting the same ```cannot uninstall, belongs to OS``` messages as below.  The end result is the same ```The gevent-socketio package is incompatible with this version of the Flask-SocketIO extension. Please uninstall it, and then install the latest version of python-socketio in its place.``` message as before.  

Thank you for your support -- I'm looking forward to trying DIGITS 5.0.

**Comment by lukeyeager** [comment]
Oops, the package name is actually [python-socketio](http://packages.ubuntu.com/trusty/python-socketio).

**Comment by michaelholm-ce** [comment]
That worked -- thank you, @lukeyeager.

**Comment by d4baggs** [comment]
Hello,
I also have the same problem, so the server won't start
![image](https://cloud.githubusercontent.com/assets/26714819/24801714/efa48ca8-1bd7-11e7-9201-9f8c9179d5dc.png)

I already check the requirement and its already satified
![image](https://cloud.githubusercontent.com/assets/26714819/24801779/29767450-1bd8-11e7-8d7a-126a32501850.png)

**Comment by mvvardhan** [comment]
I get the same error. What is the resolution for the issue?

**Comment by arunpatro** [comment]
I am working on Ubuntu 14.04
