### ISSUE TITLE
Create Dataset Problem

### ISSUE THREAD

**Issue by amlarraz** [NVIDIA/DIGITS#1209]
Hi!

When i'm going to create a object detection dataset, DIGITS give me the following error:

ERROR: ValueError: invalid literal for int() with base 10: 'image_117'

And the creation process stop (Total - 2 seconds)

My log file:

libdc1394 error: Failed to initialize libdc1394
2016-10-23 10:15:50 [ERROR] ValueError: invalid literal for int() with base 10: 'boar_117'
Traceback (most recent call last):
File "/usr/share/digits/tools/create_generic_db.py", line 458, in <module>
args['stage']
File "/usr/share/digits/tools/create_generic_db.py", line 423, in create_generic_db
label_encoding)
File "/usr/share/digits/tools/create_generic_db.py", line 276, in create_db
entry_ids = extension.itemize_entries(stage)
File "/usr/share/digits/digits/extensions/data/objectDetection/data.py", line 188, in itemize_entries
self.load_ground_truth(self.train_label_folder)
File "/usr/share/digits/digits/extensions/data/objectDetection/data.py", line 213, in load_ground_truth
datasrc.load_gt_obj()
File "/usr/share/digits/digits/extensions/data/objectDetection/utils.py", line 206, in load_gt_obj
key = int(os.path.splitext(label_file)[0])
ValueError: invalid literal for int() with base 10: 'boar_117'

I'm working with nvidia/digits Docker 4.0. However i try to create the Dataset in DIGITS 4.1 and working fine!

**Comment by gheinrich** [comment]
As you noticed there is a limitation in DIGITS 4.0 where files must have filenames like `IDENTIFIER.EXTENSION` where the identifier must be a number. On further revisions of DIGITS that limitation does not apply.

**Comment by amlarraz** [comment]
Thanks gheinrich! it's work now!!
