### ISSUE TITLE
can not enter the homepage when using localhost:5000

### ISSUE THREAD

**Issue by JulyUp** [NVIDIA/DIGITS#1213]
Hello, I use digits-4.0 and install several PyPI packages using the command 'sudo pip install -r $DIGITS_ROOT/requirements.txt'. Then I do command './digits-devserver', but it shows error 
`ImportError: cannot import name socketio_manage`
So, I modified the item 'Flask-SocketIO==0.6.0' to 'Flask-SocketIO==2.6' in requirements.txt. Thus, digits can start. However when I input URL 'localhost:5000' in my browser, it shows error

```
Couldn't import dot_parser, loading of dot files will not be possible.
2016-10-24 10:11:29 [INFO ] Loaded 0 jobs.
  ___ ___ ___ ___ _____ ___
 |   \_ _/ __|_ _|_   _/ __|
 | |) | | (_ || |  | | \__ \
 |___/___\___|___| |_| |___/ 4.0.0

Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/gevent/greenlet.py", line 327, in run
    result = self._run(*self.args, **self.kwargs)
  File "/usr/lib/python2.7/dist-packages/gevent/server.py", line 102, in wrap_socket_and_handle
    ssl_socket = self.wrap_socket(client_socket, **self.ssl_args)
TypeError: wrap_socket() got an unexpected keyword argument 'policy_server'
<Greenlet at 0x7f2b4a41d550: <bound method WSGIServer.wrap_socket_and_handle of <WSGIServer at 0x7f2b4a0ddc90 fileno=17 address=0.0.0.0:5000>>(<socket at 0x7f2b4a10b5d0 fileno=30 sock=127.0.0.1, ('127.0.0.1', 55138))> failed with TypeError

Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/gevent/greenlet.py", line 327, in run
    result = self._run(*self.args, **self.kwargs)
  File "/usr/lib/python2.7/dist-packages/gevent/server.py", line 102, in wrap_socket_and_handle
    ssl_socket = self.wrap_socket(client_socket, **self.ssl_args)
TypeError: wrap_socket() got an unexpected keyword argument 'policy_server'
<Greenlet at 0x7f2b4a41d5f0: <bound method WSGIServer.wrap_socket_and_handle of <WSGIServer at 0x7f2b4a0ddc90 fileno=17 address=0.0.0.0:5000>>(<socket at 0x7f2b4a10b7d0 fileno=31 sock=127.0.0.1, ('127.0.0.1', 55139))> failed with TypeError

Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/gevent/greenlet.py", line 327, in run
    result = self._run(*self.args, **self.kwargs)
  File "/usr/lib/python2.7/dist-packages/gevent/server.py", line 102, in wrap_socket_and_handle
    ssl_socket = self.wrap_socket(client_socket, **self.ssl_args)
TypeError: wrap_socket() got an unexpected keyword argument 'policy_server'
<Greenlet at 0x7f2b4a41d690: <bound method WSGIServer.wrap_socket_and_handle of <WSGIServer at 0x7f2b4a0ddc90 fileno=17 address=0.0.0.0:5000>>(<socket at 0x7f2b4a10b850 fileno=32 sock=127.0.0.1, ('127.0.0.1', 55140))> failed with TypeError

Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/gevent/greenlet.py", line 327, in run
    result = self._run(*self.args, **self.kwargs)
  File "/usr/lib/python2.7/dist-packages/gevent/server.py", line 102, in wrap_socket_and_handle
    ssl_socket = self.wrap_socket(client_socket, **self.ssl_args)
TypeError: wrap_socket() got an unexpected keyword argument 'policy_server'
<Greenlet at 0x7f2b4a41d730: <bound method WSGIServer.wrap_socket_and_handle of <WSGIServer at 0x7f2b4a0ddc90 fileno=17 address=0.0.0.0:5000>>(<socket at 0x7f2b4a10b8d0 fileno=33 sock=127.0.0.1, ('127.0.0.1', 55141))> failed with TypeError

Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/gevent/greenlet.py", line 327, in run
    result = self._run(*self.args, **self.kwargs)
  File "/usr/lib/python2.7/dist-packages/gevent/server.py", line 102, in wrap_socket_and_handle
    ssl_socket = self.wrap_socket(client_socket, **self.ssl_args)
TypeError: wrap_socket() got an unexpected keyword argument 'policy_server'
<Greenlet at 0x7f2b4a41d7d0: <bound method WSGIServer.wrap_socket_and_handle of <WSGIServer at 0x7f2b4a0ddc90 fileno=17 address=0.0.0.0:5000>>(<socket at 0x7f2b4a10b950 fileno=34 sock=127.0.0.1, ('127.0.0.1', 55142))> failed with TypeError

Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/gevent/greenlet.py", line 327, in run
    result = self._run(*self.args, **self.kwargs)
  File "/usr/lib/python2.7/dist-packages/gevent/server.py", line 102, in wrap_socket_and_handle
    ssl_socket = self.wrap_socket(client_socket, **self.ssl_args)
TypeError: wrap_socket() got an unexpected keyword argument 'policy_server'
<Greenlet at 0x7f2b4a41d7d0: <bound method WSGIServer.wrap_socket_and_handle of <WSGIServer at 0x7f2b4a0ddc90 fileno=17 address=0.0.0.0:5000>>(<socket at 0x7f2b4a10b790 fileno=30 sock=127.0.0.1, ('127.0.0.1', 55143))> failed with TypeError
```

And I can not enter the homepage of digits.

**Comment by lukeyeager** [comment]
Why did you change the line in `requirements.txt`? DIGITS 4.0 does require v0.6.0 of flask_socketio - that's correct.
https://github.com/NVIDIA/DIGITS/blob/v4.0.0/requirements.txt#L11

**Comment by JulyUp** [comment]
@lukeyeager  It shows error `ImportError: cannot import name socketio_manage` when using 
Flask-SocketIO==0.6.0. How to solve this problem?

**Comment by michaelholm-ce** [comment]
@JulyUp:  Can you access the page via 0.0.0.0:5000?  That worked for me when I had the same problem.

**Comment by lukeyeager** [comment]
This is a straight-forward (but not simple) matter of conflicting dependencies. On Ubuntu, you could have packages coming from apt-get, pip and/or conda. You've probably mixed two or more installation methods and have conflicting packages on your system.

This should be fool-proof:
```sh
virtualenv venv
source venv/bin/activate
pip install -r $CAFFE_ROOT/python/requirements.txt
pip install -r $DIGITS_ROOT/requirements.txt
./digits-devserver
```
If you're still having trouble, try reading through these threads/articles:

- https://github.com/NVIDIA/DIGITS/issues/1195
- https://github.com/NVIDIA/DIGITS/blob/digits-2.2/docs/VirtualEnvironment.md

**Comment by JulyUp** [comment]
@michaelholm-ce  I can not  access the page via 0.0.0.0:5000. 
@lukeyeager  It does not work. And I uninstall the dependences and install them again using pip, but it still does not work. It seems that I should give up digits-4.0.

**Comment by lukeyeager** [comment]
If you want to give up on configuring your system, you can try using Docker.

As explained on [our README](https://github.com/NVIDIA/DIGITS/blob/digits-5.0/README.md), another installation method is to use nvidia-docker to [run DIGITS](https://github.com/NVIDIA/nvidia-docker/wiki/DIGITS).

**Comment by JulyUp** [comment]
@lukeyeager Thank you very much.

**Comment by lukeyeager** [comment]
@JulyUp did you find something that works for you?
