### ISSUE TITLE
Medical-imaging example, Test an image error

### ISSUE THREAD

**Issue by imrael202** [NVIDIA/DIGITS#1232]
Hello, i have problem with Medical-imaging example.

"Test a record from valiation set" works fine, but when i try to put path in "Test an image"

Which file types i can use there dcm or png?

![1iss](https://cloud.githubusercontent.com/assets/20860578/19886036/1d6e935e-a03b-11e6-9d17-39aa6673e297.png)

i have an error in both cases(dcm/png),( the path is correct 100%)

```
2016-11-01 13:56:04 [ERROR] Error: None: No such file or directory
Traceback (most recent call last):
File "/digits/MS/plugins/DIGITS/digits/tools/inference.py", line 293, in <module>
args['resize']
File "/digits/MS/plugins/DIGITS/digits/tools/inference.py", line 93, in infer
reader = DbReader(input_list)
File "/digits/MS/plugins/DIGITS/digits/utils/lmdbreader.py", line 21, in __init__
lock=False)
lmdb.Error: None: No such file or directory
```
Can anyone help me with this?

**Comment by gheinrich** [comment]
Thanks for the report @imrael202 can you try the fix in #1237 please?
