### ISSUE TITLE
Error installing digits from scratch

### ISSUE THREAD

**Issue by SharifAmit** [NVIDIA/DIGITS#1238]
I tried to install branch 5.0 with the instruction given in the BuildDigits.md
But when i give the command "./digits-devserver"
I get the following output
```
/home/sharif/anaconda2/lib/python2.7/site-packages/flask/exthook.py:71: ExtDeprecationWarning: Importing flask.ext.socketio is deprecated, use flask_socketio instead.
  .format(x=modname), ExtDeprecationWarning
/home/sharif/anaconda2/lib/python2.7/site-packages/flask/exthook.py:71: ExtDeprecationWarning: Importing flask.ext.wtf is deprecated, use flask_wtf instead.
  .format(x=modname), ExtDeprecationWarning
Traceback (most recent call last):
  File "/home/sharif/anaconda2/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/home/sharif/anaconda2/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/sharif/Desktop/DIGITS-digits-5.0/digits/__main__.py", line 66, in <module>
    main()
  File "/home/sharif/Desktop/DIGITS-digits-5.0/digits/__main__.py", line 51, in main
    import digits.webapp
  File "digits/webapp.py", line 46, in <module>
    import digits.views
  File "/home/sharif/anaconda2/lib/python2.7/site-packages/gevent/builtins.py", line 93, in __import__
    result = _import(*args, **kwargs)
  File "digits/views.py", line 620, in <module>
    app.register_error_handler(code, handle_error)
  File "/home/sharif/anaconda2/lib/python2.7/site-packages/flask/app.py", line 1186, in register_error_handler
    self._register_error_handler(None, code_or_exception, f)
  File "/home/sharif/anaconda2/lib/python2.7/site-packages/flask/app.py", line 65, in wrapper_func
    return f(self, *args, **kwargs)
  File "/home/sharif/anaconda2/lib/python2.7/site-packages/flask/app.py", line 1201, in _register_error_handler
    exc_class, code = self._get_exc_class_and_code(code_or_exception)
  File "/home/sharif/anaconda2/lib/python2.7/site-packages/flask/app.py", line 1121, in _get_exc_class_and_code
    exc_class = default_exceptions[exc_class_or_code]
KeyError: 300
```

**Comment by lukeyeager** [comment]
You're obviously not following the instructions exactly if you're using anaconda.

You've almost certainly got some versions of Python modules which don't line up with these requirements:
https://github.com/NVIDIA/DIGITS/blob/digits-5.0/requirements.txt

**Comment by SharifAmit** [comment]
Thank you. Some packages were needed to downgrade.

**Comment by lukeyeager** [comment]
Glad to hear you found a solution.
