### ISSUE TITLE
could not get standard data inside docker container

### ISSUE THREAD

**Issue by wanghaisheng** [NVIDIA/DIGITS#1259]
setup like this
```
nvidia-docker run --name digits-dns --net=host --dns 192.168.18.20  -d -p 5000:34448 nvidia/digits
```

error  like this
```
root@dataclear:/usr/share/digits# cat /etc/resolv.conf   
search lan
nameserver 192.168.18.20
nameserver 172.17.0.1
nameserver 192.168.2.225

root@dataclear:/usr/share/digits# ping yann.lecun.com      
PING yann.lecun.com (128.122.47.89) 56(84) bytes of data.
64 bytes from djvu.cs.nyu.edu (128.122.47.89): icmp_seq=1 ttl=42 time=441 ms
64 bytes from djvu.cs.nyu.edu (128.122.47.89): icmp_seq=3 ttl=42 time=377 ms
64 bytes from djvu.cs.nyu.edu (128.122.47.89): icmp_seq=4 ttl=42 time=516 ms
^C
--- yann.lecun.com ping statistics ---
4 packets transmitted, 3 received, 25% packet loss, time 3003ms
rtt min/avg/max/mdev = 377.495/445.034/516.519/56.827 ms
root@dataclear:/usr/share/digits# python tools/download_data/main.py mnist ~/mnist                 
Downloading url=http://yann.lecun.com/exdb/mnist/train-images-idx3-ubyte.gz ...
Traceback (most recent call last):
  File "tools/download_data/main.py", line 40, in <module>
    d.getData()
  File "/usr/share/digits/tools/download_data/downloader.py", line 30, in getData
    self.__downloadFile(url)
  File "/usr/share/digits/tools/download_data/downloader.py", line 62, in __downloadFile
    urllib.urlretrieve(url, download_path)
  File "/usr/lib/python2.7/urllib.py", line 94, in urlretrieve
    return _urlopener.retrieve(url, filename, reporthook, data)
  File "/usr/lib/python2.7/urllib.py", line 240, in retrieve
    fp = self.open(url, data)
  File "/usr/lib/python2.7/urllib.py", line 208, in open
    return getattr(self, name)(url)
  File "/usr/lib/python2.7/urllib.py", line 345, in open_http
    h.endheaders(data)
  File "/usr/lib/python2.7/httplib.py", line 975, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 835, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 797, in send
    self.connect()
  File "/usr/lib/python2.7/httplib.py", line 778, in connect
    self.timeout, self.source_address)
  File "/usr/lib/python2.7/socket.py", line 553, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
IOError: [Errno socket error] [Errno -2] Name or service not known

```

**Comment by wanghaisheng** [comment]
now it came to 
```
<s# python tools/download_data/main.py mnist ~/mnist
Downloading url=http://yann.lecun.com/exdb/mnist/train-labels-idx1-ubyte.gz ...
Downloading url=http://yann.lecun.com/exdb/mnist/t10k-images-idx3-ubyte.gz ...
Downloading url=http://yann.lecun.com/exdb/mnist/t10k-labels-idx1-ubyte.gz ...
Uncompressing file=train-images-idx3-ubyte.gz ...
Traceback (most recent call last):
  File "tools/download_data/main.py", line 40, in <module>
    d.getData()
  File "/usr/share/digits/tools/download_data/downloader.py", line 32, in getData
    self.uncompressData()
  File "/usr/share/digits/tools/download_data/mnist.py", line 39, in uncompressData
    outfile.write(infile.read())
  File "/usr/lib/python2.7/gzip.py", line 254, in read
    self._read(readsize)
  File "/usr/lib/python2.7/gzip.py", line 308, in _read
    self._read_eof()
  File "/usr/lib/python2.7/gzip.py", line 347, in _read_eof
    hex(self.crc)))
IOError: CRC check failed 0x7ffe39da != 0x4c43dd73L

```

**Comment by lukeyeager** [comment]
The tool works fine from my host machine and from within a normal docker container (no extra network-related flags). I'm pretty sure your problem is with your network configuration. Sorry, but I'm not a Docker expert. Your best bet is probably StackOverflow.

**Comment by wanghaisheng** [comment]
now it came to 
```
<s# python tools/download_data/main.py mnist ~/mnist
Downloading url=http://yann.lecun.com/exdb/mnist/train-labels-idx1-ubyte.gz ...
Downloading url=http://yann.lecun.com/exdb/mnist/t10k-images-idx3-ubyte.gz ...
Downloading url=http://yann.lecun.com/exdb/mnist/t10k-labels-idx1-ubyte.gz ...
Uncompressing file=train-images-idx3-ubyte.gz ...
Traceback (most recent call last):
  File "tools/download_data/main.py", line 40, in <module>
    d.getData()
  File "/usr/share/digits/tools/download_data/downloader.py", line 32, in getData
    self.uncompressData()
  File "/usr/share/digits/tools/download_data/mnist.py", line 39, in uncompressData
    outfile.write(infile.read())
  File "/usr/lib/python2.7/gzip.py", line 254, in read
    self._read(readsize)
  File "/usr/lib/python2.7/gzip.py", line 308, in _read
    self._read_eof()
  File "/usr/lib/python2.7/gzip.py", line 347, in _read_eof
    hex(self.crc)))
IOError: CRC check failed 0x7ffe39da != 0x4c43dd73L

```

**Comment by wanghaisheng** [comment]
fixed through 
rerun docker run
```
data-clear@dataclear:~$ nvidia-docker run  --name digits-dns  --dns 192.168.18.20  -d -p 5000:34448 nvidia/digits
root@da6a6e279534:/usr/share/digits# cat /etc/resolv.conf 
search lan
nameserver 192.168.18.20
```
then delete the ~/minist directory
```
root@da6a6e279534:/usr/share/digits# sudo rm -R ~/mnist/
root@da6a6e279534:/usr/share/digits# python tools/download_data/main.py mnist ~/mnist      
Downloading url=http://yann.lecun.com/exdb/mnist/train-images-idx3-ubyte.gz ...
Downloading url=http://yann.lecun.com/exdb/mnist/train-labels-idx1-ubyte.gz ...
Downloading url=http://yann.lecun.com/exdb/mnist/t10k-images-idx3-ubyte.gz ...
Downloading url=http://yann.lecun.com/exdb/mnist/t10k-labels-idx1-ubyte.gz ...
Uncompressing file=train-images-idx3-ubyte.gz ...
Uncompressing file=train-labels-idx1-ubyte.gz ...
Uncompressing file=t10k-images-idx3-ubyte.gz ...
Uncompressing file=t10k-labels-idx1-ubyte.gz ...
Reading labels from /root/mnist/train-labels.bin ...
Reading images from /root/mnist/train-images.bin ...
Reading labels from /root/mnist/test-labels.bin ...
Reading images from /root/mnist/test-images.bin ...
Dataset directory is created successfully at '/root/mnist'
Done after 353.917651892 seconds.

```
