### ISSUE TITLE
Issue Exploring Train/Validation Label DBs built from Greyscale PNG Labels

### ISSUE THREAD

**Issue by philferriere** [NVIDIA/DIGITS#1293]
Using latest DIGITS bits (as 11/23/2016), I cannot explore the labels in my train_db without hitting the following error:

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/phil/DIGITS/digits/webapp.py", line 81, in decorated
    return f(*args, **kwargs)
  File "/home/phil/DIGITS/digits/dataset/generic/views.py", line 180, in explore
    raise RuntimeError("Expected encoded database")
RuntimeError: Expected encoded database
```

The DBs were built from **greyscale PNG files for the labels** and 24-bit RGB PNGs for the images. Both validation and training DBs were built without errors, as shown in the following snippets from `create_train_db_db.log`:

```
2016-11-23 11:42:28 [INFO ] Created features db for stage train_db in train_db/features
2016-11-23 11:42:32 [INFO ] Created labels db for stage train_db in train_db/labels
2016-11-23 11:42:32 [INFO ] Processed 1/122
...
2016-11-23 11:43:29 [INFO ] Processed 114/122
2016-11-23 11:43:29 [INFO ] Feature shape for stage train_db: (3, 406, 438)
2016-11-23 11:43:29 [INFO ] Label shape for stage train_db: (1, 406, 438)
2016-11-23 11:43:29 [INFO ] Processed 115/122
...2016-11-23 11:43:31 [INFO ] Processed 122/122
2016-11-23 11:43:32 [INFO ] Found 3879 entries for stage train_db
2016-11-23 11:43:32 [INFO ] Generic DB creation Done
```

The UI page for my dataset only exposes an `Explore the db` button for the `features DB`. There is no such button for the `labels DB`.

It could be that the button is not exposed because this feature (greyscale labels) is just not supported yet, and you've disabled exploration while you're working on it. Or, it could be that it isn't displayed because of whatever issue is at the root of the problem I'm hitting.

If the button is not exposed, how did I hit the issue reported here, you may ask? Simply by building the URL manually, from:

```
http://serverp:5000/datasets/generic/explore?db=train_db%2Ffeatures&job_id=20161123-103642-a9a5
```
to
```
http://serverp:5000/datasets/generic/explore?db=train_db%2Flabels&job_id=20161123-103642-a9a5
```

I would love to know if the button doesn't appear because the work on the "greyscale label" feature is simply incomplete or if this is an actual bug.

Either way, I want to thank you for your hard work providing us with this AWESOME tool!

**Comment by gheinrich** [comment]
Hello, I think the button is not exposed because you probably selected "none" encoding for the labels DB when creating your dataset. As a result you can't explore the labels DB since DIGITS has no idea what the data represent. If so, try to re-create your dataset and select "PNG" encoding for the labels, as recommended [there](https://github.com/NVIDIA/DIGITS/blob/master/digits/extensions/data/imageSegmentation/template.html#L99) (for segmentation datasets).

**Comment by philferriere** [comment]
Doh! That was it! Thank you for the prompt response, Greg.
