### ISSUE TITLE
math domain error

### ISSUE THREAD

**Issue by avalada** [NVIDIA/DIGITS#13]
I created my dataset and used the default AlexNet definitions. I get the error below and the caffe log says 
"Memory required for data: 0"

Not sure why? The LMDB's seem to exist.

ERROR: math domain error

Traceback (most recent call last):
  File "/home/valada/digits/digits/scheduler.py", line 386, in task_thread
    task.run(**options)
  File "/home/valada/digits/digits/task.py", line 196, in run
    if not self.process_output(line):
  File "/home/valada/digits/digits/model/tasks/caffe_train.py", line 475, in process_output
    self.logger.debug('memory required: %s' % utils.sizeof_fmt(bytes_required))
  File "/home/valada/digits/digits/utils/__init__.py", line 100, in sizeof_fmt
    i = int(math.floor(math.log(size,1024)))
ValueError: math domain error

**Comment by avalada** [comment]
Looks like Caffe bug rather than DIGITS so closing.
