### ISSUE TITLE
DetectNet Training Error:   'ascii' codec can't decode

### ISSUE THREAD

**Issue by Jmx5200** [NVIDIA/DIGITS#1321]
When I try to train the detection model, the error is occur.
```
ERROR: 'ascii' codec can't decode byte 0xe4 in position 68: ordinal not in range(128)

Traceback (most recent call last):
  File "digits/scheduler.py", line 512, in run_task
    task.run(resources)
  File "digits/task.py", line 227, in run
    for line in utils.nonblocking_readlines(self.p.stdout):
  File "digits/utils/__init__.py", line 71, in nonblocking_readlines
    yield buf[:(n + 1)].decode(enc)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe4 in position 68: ordinal not in range(128)

```

**Comment by Jmx5200** [comment]
I have solved the problem, all the file name and path can not include any chinese character, such as "下载".

**Comment by lukeyeager** [comment]
See https://github.com/NVIDIA/DIGITS/issues/353, https://github.com/NVIDIA/DIGITS/issues/1100. This is not related to DetectNet.
