### ISSUE TITLE
Test a Database leads to 'No such file or directory' error (DIGITS 4)

### ISSUE THREAD

**Issue by desertnaut** [NVIDIA/DIGITS#1351]
Hi all,

I am using the NVIDIA DIGITS 4 AMI for training an object detection network (DetectNet). While I am able to test single images, when I try the 'Test a Database' option with path `/usr/share/digits/digits/jobs/20161213-115858-3f44/val_db` (my validation database, as provided in the respective dataset page), I get the following error:

```
libdc1394 error: Failed to initialize libdc1394
WARNING: log_file config option not found - no log file is being saved
2016-12-14 11:12:33 [ERROR] Error: /usr/share/digits/digits/jobs/20161213-115858-3f44/val_db: No such file or directory
Traceback (most recent call last):
File "/usr/share/digits/tools/inference.py", line 240, in <module>
args['db'],
File "/usr/share/digits/tools/inference.py", line 83, in infer
reader = DbReader(input_list)
File "/usr/share/digits/digits/utils/lmdbreader.py", line 21, in __init__
lock=False)
lmdb.Error: /usr/share/digits/digits/jobs/20161213-115858-3f44/val_db: No such file or directory
```
while the directory exists in the path specified:

```
ubuntu@ip-172-31-28-9:~$ cd /usr/share/digits/digits/jobs/20161213-115858-3f44/val_db
ubuntu@ip-172-31-28-9:/usr/share/digits/digits/jobs/20161213-115858-3f44/val_db$ ll
total 10820
drwxr-xr-x 4 www-data www-data     4096 Dec 13 12:02 ./
drwxr-xr-x 4 www-data www-data     4096 Dec 14 07:26 ../
drwxr-xr-x 2 www-data www-data     4096 Dec 13 11:59 features/
drwxr-xr-x 2 www-data www-data     4096 Dec 13 11:59 labels/
-rw-r--r-- 1 www-data www-data 11059215 Dec 13 12:02 mean.binaryproto
```
The behavior is the same both while I still have a net under training, as well as when no training is taking place.

Any ideas?

Thanks a lot in advance.

**Comment by gheinrich** [comment]
Admittedly the error is inexplicit. You need to provide the path to the `features` db from your `val_db` folder. The timeout error you get when using `features` probably comes from the fact that your features DB is very large and the web server times out. Try a smaller dataset (you don't have to re-train your model).
