### ISSUE TITLE
DIGITS is always stuck at the last minute when generating a categorized database.

### ISSUE THREAD

**Issue by vivichina** [NVIDIA/DIGITS#1385]
Recently, a problem plaguing me, I have about 700,000 sample pictures in a total of more than 1,000 categories, tried several times no way to generate a database, who can tell me where the problem is, thank you very much?

The following is the log information of the generated training set:
2017-01-05 18:39:25 [DEBUG] 547225 total lines in file
2017-01-05 18:39:25 [INFO] 547225 valid lines in file
2017-01-05 18:39:25 [DEBUG] Category 0 has 26 images.
2017-01-05 18:39:25 [DEBUG] Category 1 has 21 images.
2017-01-05 18:39:25 [DEBUG] Category 2 has 269 images.
2017-01-05 18:39:25 [DEBUG] Category 3 has 5 images.
2017-01-05 18:39:25 [DEBUG] Category 4 has 1307 images.
2017-01-05 18:39:25 [DEBUG] Category 5 has 216 images.
2017-01-05 18:39:25 [DEBUG] Category 6 has 1157 images.
2017-01-05 18:39:25 [DEBUG] Category 7 has 1600 images.
2017-01-05 18:39:25 [DEBUG] Category 8 has 136 images.
2017-01-05 18:39:25 [DEBUG] Category 9 has 295 images.
...
2017-01-06 01:30:00 [DEBUG] Processed 546800/547225
2017-01-06 01:30:02 [DEBUG] Processed 546800/547225
2017-01-06 01:30:04 [DEBUG] Processed 546900/547225
2017-01-06 01:30:06 [DEBUG] Processed 546900/547225
2017-01-06 01:30:08 [DEBUG] Processed 547000/547225
2017-01-06 01:30:10 [DEBUG] Processed 547100/547225
2017-01-06 01:30:12 [DEBUG] Processed 547100/547225
2017-01-06 01:30:14 [DEBUG] Processed 547200/547225
2017-01-06 01:30:16 [DEBUG] Processed 547200/547225
2017-01-06 01:30:18 [DEBUG] Processed 547200/547225
2017-01-06 01:30:20 [DEBUG] Processed 547200/547225
2017-01-06 01:30:22 [DEBUG] Processed 547200/547225
2017-01-06 01:30:24 [DEBUG] Processed 547200/547225
2017-01-06 01:30:26 [DEBUG] Processed 547200/547225
2017-01-06 01:30:28 [DEBUG] Processed 547200/547225
2017-01-06 01:30:30 [DEBUG] Processed 547200/547225
2017-01-06 01:30:32 [DEBUG] Processed 547200/547225
...
2017-01-06 09:12:54 [DEBUG] Processed 547200/547225
2017-01-06 09:12:56 [DEBUG] Processed 547200/547225
2017-01-06 09:12:58 [DEBUG] Processed 547200/547225
2017-01-06 09:13:00 [DEBUG] Processed 547200/547225
2017-01-06 09:13:02 [DEBUG] Processed 547200/547225
2017-01-06 09:13:04 [DEBUG] Processed 547200/547225
2017-01-06 09:13:06 [DEBUG] Processed 547200/547225

**Comment by gheinrich** [comment]
I think I've seen this before in cases when we are unable to read some images. Can you see any warning in the log? To debug this issue you might want to change these [lines](https://github.com/NVIDIA/DIGITS/blob/master/digits/tools/create_db.py#L582-L584) to something like:

```
except:
    raise
```

**Comment by vivichina** [comment]
@gheinrich 
Thank you!!!
According to your suggestion, I re-examine the log and found that there are several exceptions I ignored, like this:
```
2017-01-11 19:12:29 [DEBUG] Processed 18600/657109
Exception in thread Thread-2:
Traceback (most recent call last):
File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
Self.run ()
File "/usr/lib/python2.7/threading.py", line 763, in run
Self .__ target (* self .__ args, ** self .__ kwargs)
File "/usr/share/digits/tools/create_db.py", line 569, in _load_thread
Image = utils.image.load_image (path)
File "/usr/share/digits/digits/utils/image.py", line 63, in load_image
Image.load ()
File "/usr/lib/python2.7/dist-packages/PIL/ImageFile.py", line 206, in load
Raise IndexError (ie)
IndexError: string index out of range
2017-01-11 19:12:31 [DEBUG] Processed 18700/657109
```

I'm trying to modify /usr/share/digits/tools/create_db.py as follows:
```
568 try:
569     image = utils.image.load_image (path)
570 except utils.errors.LoadImageError as e:
571     logger.warning ('[% s]% s:% s'% (path, type (e) .__ name__, e))
572     continue
573 except Exception as e:                                                                    #added
574     logger.warning ('[% s]% s:% s'% (path, type (e) .__ name__, e)) #added
575     continue                                                                                     #added
```
There is no problem now, but I'm not sure if changing code like this will cause other problems to occur.
Bad pictures are also found out, they are some incomplete picture, but do not know why the original code did not catch this exception.
Once again, sincere thanks gheinrich！
