### ISSUE TITLE
CAFFE_ROOT not being picked up?

### ISSUE THREAD

**Issue by drcrook1** [NVIDIA/DIGITS#1390]
Hey All,

I have digits 5 on an Ubuntu 16.04 box.  I have had it running before, but I had to reboot the box and now it is no longer running.  I try the following commands:

cd digits (gets me into digits folder)
sudo -H ./digits-devserver --port 8888

I get back that Caffe executable is not found in PATH, I should try setting CAFFE_ROOT.

I do echo $CAFFE_ROOT and it gives me back /home/drcrook/caffe 

I can cd $CAFFE_ROOT and sure enough caffe is there.

My path is as below:
drcrook@SERVER:~/digits$ echo $PATH
/home/drcrook/bin:/home/drcrook/.local/bin:/home/drcrook/caffe/build/tools:/usr/local/cuda/bin:/home/drcrook/caffe/build/tools:/home/drcrook/bin:/home/drcrook/.local/bin:/home/drcrook/caffe/build/tools:/usr/local/cuda/bin:/home/drcrook/bin:/home/drcrook/.local/bin:/home/drcrook/caffe/build/tools:/usr/local/cuda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin

Not too sure what else to try here... insights are welcome.

The full error can be found here...

 |   \_ _/ __|_ _|_   _/ __|
 | |) | | (_ || |  | | \__ \
 |___/___\___|___| |_| |___/ 5.0.0-rc.1

A valid Caffe installation was not found on your system.
Use the envvar CAFFE_ROOT to indicate a valid installation.
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/drcrook/digits/digits/__main__.py", line 66, in <module>
    main()
  File "/home/drcrook/digits/digits/__main__.py", line 49, in main
    import digits.config
  File "digits/config/__init__.py", line 7, in <module>
    from . import caffe
  File "digits/config/caffe.py", line 229, in <module>
    executable, version, flavor = load_from_path()
  File "digits/config/caffe.py", line 51, in load_from_path
    raise ValueError('Caffe executable not found in PATH')
ValueError: Caffe executable not found in PATH

**Comment by drcrook1** [comment]
Looks like you have a few key items...
1.  PYTHONPATH must onlycontain one caffe thing in it:  /home/usrname/caffe/python
   a.  if it has any other caffe stuff, it implodes.
2.  CAFFE_ROOT must be: /home/usrname/caffe/
