### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'async_mode'

### ISSUE THREAD

**Issue by zhixianGuo** [NVIDIA/DIGITS#1392]
Hello --Recently,I have some problems installing digits!!!
      I'm running digits 5.1-dev on Ubuntu14.04 and Caffe 0.15.9.

The Error is:
```
root@dell-Precision-Tower-7810:/home/dell/gzx/digits# ./digits-devserver 
  ___ ___ ___ ___ _____ ___
 |   \_ _/ __|_ _|_   _/ __|
 | |) | | (_ || |  | | \__ \
 |___/___\___|___| |_| |___/ 5.1-dev

Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/dell/gzx/digits/digits/__main__.py", line 70, in <module>
    main()
  File "/home/dell/gzx/digits/digits/__main__.py", line 55, in main
    import digits.webapp
  File "digits/webapp.py", line 26, in <module>
    socketio = SocketIO(app, async_mode='gevent')
TypeError: __init__() got an unexpected keyword argument 'async_mode'
Exception KeyError: KeyError(140508908690800,) in <module 'threading' from '/usr/lib/python2.7/threading.pyc'> ignored

I have installed the requirements like this:
pip install -r requirements.txt

root@dell-Precision-Tower-7810:/home/dell/gzx/digits# pip install -r requirements.txt 
Requirement already satisfied (use --upgrade to upgrade): Pillow<=3.1.2,>=2.3.0 in /usr/lib/python2.7/dist-packages (from -r requirements.txt (line 1))
Requirement already satisfied (use --upgrade to upgrade): numpy<=1.11.0,>=1.8.1 in /usr/lib/python2.7/dist-packages (from -r requirements.txt (line 2))
Requirement already satisfied (use --upgrade to upgrade): scipy<=0.17.0,>=0.13.3 in /usr/lib/python2.7/dist-packages (from -r requirements.txt (line 3))
Requirement already satisfied (use --upgrade to upgrade): protobuf<=2.6.1,>=2.5.0 in /usr/lib/python2.7/dist-packages (from -r requirements.txt (line 4))
Requirement already satisfied (use --upgrade to upgrade): six<=1.10.0,>=1.5.2 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 5))
Requirement already satisfied (use --upgrade to upgrade): requests<=2.9.1,>=2.2.1 in /usr/lib/python2.7/dist-packages (from -r requirements.txt (line 6))
Requirement already satisfied (use --upgrade to upgrade): gevent<=1.1.0,>=1.0 in /usr/lib/python2.7/dist-packages (from -r requirements.txt (line 7))
Requirement already satisfied (use --upgrade to upgrade): gevent-websocket==0.9.3 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 8))
Requirement already satisfied (use --upgrade to upgrade): Flask==0.10.1 in /usr/lib/python2.7/dist-packages (from -r requirements.txt (line 9))
Requirement already satisfied (use --upgrade to upgrade): Flask-WTF<=0.12,>=0.11 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 10))
Requirement already satisfied (use --upgrade to upgrade): wtforms<=2.1,>=2.0 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 11))
Requirement already satisfied (use --upgrade to upgrade): Flask-SocketIO==2.6 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 12))
Requirement already satisfied (use --upgrade to upgrade): setuptools<=20.7.0,>=3.3 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 13))
Requirement already satisfied (use --upgrade to upgrade): lmdb==0.87 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 14))
Requirement already satisfied (use --upgrade to upgrade): h5py<=2.6.0,>=2.2.1 in /usr/lib/python2.7/dist-packages (from -r requirements.txt (line 15))
Requirement already satisfied (use --upgrade to upgrade): pydot<=1.0.29,>=1.0.28 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 16))
Requirement already satisfied (use --upgrade to upgrade): psutil<=3.4.2,>=1.2.1 in /usr/lib/python2.7/dist-packages (from -r requirements.txt (line 17))
Requirement already satisfied (use --upgrade to upgrade): matplotlib<=1.5.1,>=1.3.1 in /usr/lib/pymodules/python2.7 (from -r requirements.txt (line 18))
Requirement already satisfied (use --upgrade to upgrade): scikit-fmm>=0.0.9 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 19))
Requirement already satisfied (use --upgrade to upgrade): Werkzeug>=0.7 in /usr/local/lib/python2.7/dist-packages (from Flask==0.10.1->-r requirements.txt (line 9))
Requirement already satisfied (use --upgrade to upgrade): Jinja2>=2.4 in /usr/lib/python2.7/dist-packages (from Flask==0.10.1->-r requirements.txt (line 9))
Requirement already satisfied (use --upgrade to upgrade): itsdangerous>=0.21 in /usr/lib/python2.7/dist-packages (from Flask==0.10.1->-r requirements.txt (line 9))
Requirement already satisfied (use --upgrade to upgrade): python-socketio>=1.4 in /usr/local/lib/python2.7/dist-packages (from Flask-SocketIO==2.6->-r requirements.txt (line 12))
Requirement already satisfied (use --upgrade to upgrade): python-engineio>=0.9.2 in /usr/local/lib/python2.7/dist-packages (from Flask-SocketIO==2.6->-r requirements.txt (line 12))
Requirement already satisfied (use --upgrade to upgrade): pyparsing==1.5.7 in /usr/local/lib/python2.7/dist-packages (from pydot<=1.0.29,>=1.0.28->-r requirements.txt (line 16))
Requirement already satisfied (use --upgrade to upgrade): python-dateutil in /usr/lib/python2.7/dist-packages (from matplotlib<=1.5.1,>=1.3.1->-r requirements.txt (line 18))
Requirement already satisfied (use --upgrade to upgrade): tornado in /usr/local/lib/python2.7/dist-packages (from matplotlib<=1.5.1,>=1.3.1->-r requirements.txt (line 18))
Requirement already satisfied (use --upgrade to upgrade): nose in /usr/lib/python2.7/dist-packages (from matplotlib<=1.5.1,>=1.3.1->-r requirements.txt (line 18))
Requirement already satisfied (use --upgrade to upgrade): markupsafe in /usr/lib/python2.7/dist-packages (from Jinja2>=2.4->Flask==0.10.1->-r requirements.txt (line 9))
Requirement already satisfied (use --upgrade to upgrade): backports.ssl_match_hostname in /usr/local/lib/python2.7/dist-packages (from tornado->matplotlib<=1.5.1,>=1.3.1->-r requirements.txt (line 18))
Requirement already satisfied (use --upgrade to upgrade): singledispatch in /usr/local/lib/python2.7/dist-packages (from tornado->matplotlib<=1.5.1,>=1.3.1->-r requirements.txt (line 18))
Requirement already satisfied (use --upgrade to upgrade): certifi in /usr/local/lib/python2.7/dist-packages (from tornado->matplotlib<=1.5.1,>=1.3.1->-r requirements.txt (line 18))
Requirement already satisfied (use --upgrade to upgrade): backports_abc>=0.4 in /usr/local/lib/python2.7/dist-packages (from tornado->matplotlib<=1.5.1,>=1.3.1->-r requirements.txt (line 18))
Cleaning up...
```
I also found this same problem and done it!     [https://github.com/NVIDIA/DIGITS/issues/1195](url)

Best Wishes!
   Thanks!

**Comment by lukeyeager** [comment]
So you solved it already? Thanks for letting us know.

**Comment by zhixianGuo** [comment]
@lukeyeager    Thank you for your reply.  I'm sorry I didn't solve it. But when I use digits4.0, it's OK！
