### ISSUE TITLE
installing text classifier or medicall image ....

### ISSUE THREAD

**Issue by balouji** [NVIDIA/DIGITS#1414]
Hi
I have the same problem also
am using ubuntu 14.04.5
when I install the pip install -e $DIGITS_ROOT
Usage:
pip install [options] ...
pip install [options] -r ...
pip install [options] [-e] ...
pip install [options] [-e] ...
pip install [options] <archive url/path> ...
have above mentioned lines
and then this is going to happen
pip install $DIGITS_ROOT/plugins/data/sunnybrook/
Exception:
Traceback (most recent call last):
File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 122, in main
status = self.run(options, args)
File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 257, in run
InstallRequirement.from_line(name, None))
File "/usr/lib/python2.7/dist-packages/pip/req.py", line 173, in from_line
return cls(req, comes_from, url=url, prereleases=prereleases)
File "/usr/lib/python2.7/dist-packages/pip/req.py", line 71, in init
req = pkg_resources.Requirement.parse(req)
File "/usr/local/lib/python2.7/dist-packages/pkg_resources/init.py", line 2833, in parse
req, = parse_requirements(s)
File "/usr/local/lib/python2.7/dist-packages/pkg_resources/init.py", line 2781, in parse_requirements
yield Requirement(line)
File "/usr/local/lib/python2.7/dist-packages/pkg_resources/init.py", line 2790, in init
raise RequirementParseError(str(e))
RequirementParseError: Invalid requirement, parse error at "'/plugins'"

Storing debug log for failure in /tmp/tmpm_CQsC

it would be wonderful if you could help me out

**Comment by gheinrich** [comment]
Hello, you need to set `DIGITS_ROOT` to something that makes sense, i.e. the actual root of our DIGITS repository - see this [doc](https://github.com/NVIDIA/DIGITS/blob/master/docs/BuildDigits.md#download-source).

**Comment by balouji** [comment]
I already saw that and installed my digits based on that 
now I wanted to add the text classifier and sunnybrook

**Comment by gheinrich** [comment]
Closing due to inactivity.
