### ISSUE TITLE
Unable to create custom dataset on Digits4 using AWS ami 

### ISSUE THREAD

**Issue by BhushanGarware** [NVIDIA/DIGITS#1423]
Hello,
I was trying to test Object Detection feature of Digits4 using AWS ami as mentioned [here](https://aws.amazon.com/marketplace/pp/B01LZN28VD).
However, I am getting error while creating custom dataset.  Here is the error log 

libdc1394 error: Failed to initialize libdc1394
WARNING: log_file config option not found - no log file is being saved
2017-01-28 08:37:21 [INFO ] Created features db for stage train_db in train_db/features
Exception in thread Thread-2:
Traceback (most recent call last):
File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
self.run()
File "/usr/share/digits/tools/create_generic_db.py", line 244, in run
feature, label = self.extension.encode_entry(entry_id)
File "/usr/share/digits/digits/extensions/data/objectDetection/data.py", line 57, in encode_entry
img = digits.utils.image.load_image(image_filename)
File "/usr/share/digits/digits/utils/image.py", line 65, in load_image
raise errors.LoadImageError, 'IOError: %s' % e.message
LoadImageError: IOError:
2017-01-28 08:37:21 [ERROR] LoadImageError: IOError:
2017-01-28 08:37:21 [ERROR] Exception: LoadImageError: IOError:
Traceback (most recent call last):
File "/usr/share/digits/tools/create_generic_db.py", line 458, in <module>
args['stage']
File "/usr/share/digits/tools/create_generic_db.py", line 423, in create_generic_db
label_encoding)
File "/usr/share/digits/tools/create_generic_db.py", line 326, in create_db
raise Exception(err)
Exception: LoadImageError: IOError:

Best Regards,
Bhushan G.

**Comment by MarcGyongyosi** [comment]
Did you double check the path to the "images" folder?

**Comment by BhushanGarware** [comment]
Yes. All the images are accessible. Please find the following image for reference.   ![abc](https://cloud.githubusercontent.com/assets/22560857/22422309/ad9169b2-e711-11e6-8c1a-776a693d8f3c.jpg)

Thanks,
BhushanG.

**Comment by snuffysasa** [comment]
Did you solve this? I am having the same problem
