### ISSUE TITLE
Install digits problem

### ISSUE THREAD

**Issue by lindafan129** [NVIDIA/DIGITS#1455]
"/home/ubuntu/a/caffe/" from CAFFE_ROOT does not point to a valid installation of Caffe.
Use the envvar CAFFE_ROOT to indicate a valid installation.
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/ubuntu/digits/digits/__main__.py", line 70, in <module>
    main()
  File "/home/ubuntu/digits/digits/__main__.py", line 53, in main
    import digits.config
  File "digits/config/__init__.py", line 7, in <module>
    from . import (  # noqa
  File "digits/config/caffe.py", line 226, in <module>
    executable, version, flavor = load_from_envvar('CAFFE_ROOT')
  File "digits/config/caffe.py", line 33, in load_from_envvar
    % executable_dir)
ValueError: Caffe executable not found at "/home/ubuntu/a/caffe/build/t

my caffe_root:/home/ubuntu/caffe/

**Comment by gheinrich** [comment]
did you try to do `export CAFFE_ROOT=/home/ubuntu/caffe/` before starting DIGITS?

**Comment by lindafan129** [comment]
Yes,I have tried,therefore show this error 
this is a caffe install problem?or other?

**Comment by MKYucel** [comment]
Check the fist line you posted: "/home/ubuntu/a/caffe" whereas you state in the end your caffe_root is "home/ubuntu/caffe".

**Comment by lindafan129** [comment]
oh no ,i have modify ,but also error
ubuntu@tegra-ubuntu:~/digits$ ./digits-devserver 
  ___ ___ ___ ___ _____ ___
 |   \_ _/ __|_ _|_   _/ __|
 | |) | | (_ || |  | | \__ \
 |___/___\___|___| |_| |___/ 5.1-dev

"/home/ubuntu/caffe/" from CAFFE_ROOT does not point to a valid installation of Caffe.
Use the envvar CAFFE_ROOT to indicate a valid installation.
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/ubuntu/digits/digits/__main__.py", line 70, in <module>
    main()
  File "/home/ubuntu/digits/digits/__main__.py", line 53, in main
    import digits.config
  File "digits/config/__init__.py", line 7, in <module>
    from . import (  # noqa
  File "digits/config/caffe.py", line 226, in <module>
    executable, version, flavor = load_from_envvar('CAFFE_ROOT')
  File "digits/config/caffe.py", line 33, in load_from_envvar
    % executable_dir)
ValueError: Caffe executable not found at "/home/ubuntu/caffe/build/tools"

**Comment by lukeyeager** [comment]
It seems you are not comfortable with command-line instructions and/or manual builds. Why not try one of the other installation options to get everything set up for you? The deb packages and the docker images both come with Caffe built and DIGITS configured to use it.
