### ISSUE TITLE
Update existing datasets by adding more data

### ISSUE THREAD

**Issue by lukeyeager** [NVIDIA/DIGITS#146]
> I think adding an endpoint in the API to batch update datasets would really help and this would also be useful for retraining classifiers without posting a new dataset each time. 

The request is to enable updating of a dataset by adding more images without having to rebuild the whole database. There are some outstanding questions to be answered first:

* Can you update a dataset which is being used by a model for training? Does LMDB even allow for it? Does Caffe?
* How do you keep a history of which data was used to train a model if the dataset may change?

**Comment by mrgloom** [comment]
Maybe simplest solution is to use just .txt file with list of images? it also will save HDD space. Some Caffe forks allow this (not sure about official branch).

For example https://github.com/alexgkendall/caffe-segnet , but it used for semantic segmentation, not classification.
Here is input layer of type `DenseImageData` accepting .txt
https://github.com/alexgkendall/SegNet-Tutorial/blob/master/Models/segnet_basic_train.prototxt

**Comment by Bardo91** [comment]
I am trying to use segnet with DIGITS but when I train the model it throws

```
Traceback (most recent call last):
  File "digits/scheduler.py", line 512, in run_task
    task.run(resources)
  File "digits/task.py", line 189, in run
    self.before_run()
  File "digits/model/tasks/caffe_train.py", line 220, in before_run
    self.save_files_generic()
  File "digits/model/tasks/caffe_train.py", line 632, in save_files_generic
    network = cleanedUpGenericNetwork(self.network)
  File "digits/model/tasks/caffe_train.py", line 1701, in cleanedUpGenericNetwork
    'Unsupported data layer type %s' % layer.type
AssertionError: Unsupported data layer type DenseImageData
```
Have you experienced it @mrgloom ?
