### ISSUE TITLE
Digits - WIndows

### ISSUE THREAD

**Issue by satishknl** [NVIDIA/DIGITS#1484]
Am facing with the syntax error:

C:\DIGITS>python digits-devserver
  File "digits-devserver", line 6
    python2 -m digits $@
                    ^
SyntaxError: invalid syntax

**Comment by lukeyeager** [comment]
Right, that's a bash script - not a python script:
https://github.com/NVIDIA/DIGITS/blob/v5.0.0/digits-devserver#L1

Look at the contents of the script. You want something like this instead:
```
python -m digits
```

Why did you try that command? Do we need to update our docs somewhere?

**Comment by satishknl** [comment]
i got this..........

C:\DIGITS>python -m digits
  ___ ___ ___ ___ _____ ___
 |   \_ _/ __|_ _|_   _/ __|
 | |) | | (_ || |  | | \__ \
 |___/___\___|___| |_| |___/ 5.1-dev

Traceback (most recent call last):
  File "C:\Anaconda\lib\runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "C:\Anaconda\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\DIGITS\digits\__main__.py", line 70, in <module>
    main()
  File "C:\DIGITS\digits\__main__.py", line 53, in main
    import digits.config
  File "digits\config\__init__.py", line 7, in <module>
    from . import (  # noqa
  File "digits\config\caffe.py", line 13, in <module>
    from digits.utils import parse_version
  File "digits\utils\__init__.py", line 167, in <module>
    from . import constants, image, time_filters, errors, forms, routing, auth
# noqa
  File "digits\utils\image.py", line 15, in <module>
    import PIL.Image
ImportError: No module named PIL.Image

**Comment by satishknl** [comment]
is digits installed  lukeyeager
?

**Comment by lukeyeager** [comment]
Please follow the windows instructions that @IsaacYangSLA contributed:
https://github.com/NVIDIA/DIGITS/blob/digits-5.0/docs/BuildDigitsWindows.md

**Comment by AleiLmy** [comment]
I got this:
xuelei@xuelei-Z97-HD3:~/digits$ ./digits-devserver
  ___ ___ ___ ___ _____ ___
 |   \_ _/ __|_ _|_   _/ __|
 | |) | | (_ || |  | | \__ \
 |___/___\___|___| |_| |___/ 5.1-dev

Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/xuelei/digits/digits/__main__.py", line 70, in <module>
    main()
  File "/home/xuelei/digits/digits/__main__.py", line 53, in main
    import digits.config
  File "digits/config/__init__.py", line 7, in <module>
    from . import (  # noqa
  File "digits/config/caffe.py", line 13, in <module>
    from digits.utils import parse_version
  File "digits/utils/__init__.py", line 167, in <module>
    from . import constants, image, time_filters, errors, forms, routing, auth  # noqa
  File "digits/utils/forms.py", line 8, in <module>
    from wtforms.compat import string_types
ImportError: No module named compat

**Comment by vanmunch** [comment]
@lukeyeager Is there anything more recent information on installing Digits for Windows than the link from Aug 2016?  When you're presented with the option to install it on Windows it appears that it's a simple down load and install....

**Comment by prajy** [comment]
I have also received the, "No module named PIL.Image command" However, isn't PIL outdated and if using Pillow,, shouldn't it be "from PIL import Image" If still using PIL won't the import statement be just "import Image".

**Comment by prajy** [comment]
@satishknl I have found the fix for the no module Pil.Image. You need to use the old version of Pillow (3.1.1 or 3.1.2), not the new one.
