### ISSUE TITLE
Run digits problem

### ISSUE THREAD

**Issue by AleiLmy** [NVIDIA/DIGITS#1489]
When I run this command ~/digits$ ./digits-devserver
The following error will occur

 xuelei@xuelei-Z97-HD3:~/digits$ ./digits-devserver
  ___ ___ ___ ___ _____ ___
 |   \_ _/ __|_ _|_   _/ __|
 | |) | | (_ || |  | | \__ \
 |___/___\___|___| |_| |___/ 5.1-dev

A valid Caffe installation was not found on your system.
Use the envvar CAFFE_ROOT to indicate a valid installation.
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/xuelei/digits/digits/__main__.py", line 70, in <module>
    main()
  File "/home/xuelei/digits/digits/__main__.py", line 53, in main
    import digits.config
  File "digits/config/__init__.py", line 7, in <module>
    from . import (  # noqa
  File "digits/config/caffe.py", line 230, in <module>
    executable, version, flavor = load_from_path()
  File "digits/config/caffe.py", line 54, in load_from_path
    raise ValueError('Caffe executable not found in PATH')
ValueError: Caffe executable not found in PATH

**Comment by m5061125** [comment]
Just read the install guide carefully, It is the problem of env setting of caffe root.

**Comment by gheinrich** [comment]
Closing due to inactivity.
