### ISSUE TITLE
Some of the questions about the installation

### ISSUE THREAD

**Issue by AleiLmy** [NVIDIA/DIGITS#1496]
When I run 
xuelei@xuelei-Z97-HD3:~/digits$ ./digits-devserver
  ___ ___ ___ ___ _____ ___
 |   \_ _/ __|_ _|_   _/ __|
 | |) | | (_ || |  | | \__ \
 |___/___\___|___| |_| |___/ 5.1-dev

Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/xuelei/digits/digits/__main__.py", line 70, in <module>
    main()
  File "/home/xuelei/digits/digits/__main__.py", line 55, in main
    import digits.webapp
  File "digits/webapp.py", line 26, in <module>
    socketio = SocketIO(app, async_mode='gevent')
TypeError: __init__() got an unexpected keyword argument 'async_mode'
Exception KeyError: KeyError(140466184254480,) in <module 'threading' from '/usr/lib/python2.7/threading.pyc'> ignored
Please give me some effective ways to resolve these errors!

**Comment by rodrigoberriel** [comment]
Did you try #1195?

**Comment by gheinrich** [comment]
Closing due to inactivity.
