### ISSUE TITLE
Exception KeyError: KeyError(28050128,) in <module 'threading' from '/usr/lib/python2.7/threading.pyc'> ignored

### ISSUE THREAD

**Issue by mrgloom** [NVIDIA/DIGITS#1502]
When I run `./digits-devserver` on Ubuntu 12.04 I get following error:

```
    ./digits-devserver
      ___ ___ ___ ___ _____ ___
     |   \_ _/ __|_ _|_   _/ __|
     | |) | | (_ || |  | | \__ \
     |___/___\___|___| |_| |___/ 5.1-dev
    
    Traceback (most recent call last):
      File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
        "__main__", fname, loader, pkg_name)
      File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
        exec code in run_globals
      File "/home/myuser/Desktop/DIGITS/digits/__main__.py", line 70, in <module>
        main()
      File "/home/myuser/Desktop/DIGITS/digits/__main__.py", line 55, in main
        import digits.webapp
      File "digits/webapp.py", line 47, in <module>
        import digits.views  # noqa
      File "digits/views.py", line 18, in <module>
        from digits import dataset, extensions, model, utils, pretrained_model
      File "digits/extensions/__init__.py", line 4, in <module>
        from .data import *  # noqa
      File "digits/extensions/data/__init__.py", line 7, in <module>
        from . import imageProcessing
      File "digits/extensions/data/imageProcessing/__init__.py", line 4, in <module>
        from .data import DataIngestion
      File "digits/extensions/data/imageProcessing/data.py", line 12, in <module>
        from .forms import DatasetForm
      File "digits/extensions/data/imageProcessing/forms.py", line 6, in <module>
        from flask.ext.wtf import Form
      File "/usr/lib/python2.7/dist-packages/flask/exthook.py", line 62, in load_module
        __import__(realname)
      File "/usr/lib/python2.7/dist-packages/flaskext/wtf/__init__.py", line 72, in <module>
        __all__ += fields.__all__
    AttributeError: 'module' object has no attribute '__all__'
    Exception KeyError: KeyError(28050128,) in <module 'threading' from '/usr/lib/python2.7/threading.pyc'> ignored
```

What can be the source of this error and how can it be fixed?

Seems this is related:
http://stackoverflow.com/questions/8774958/keyerror-in-module-threading-after-a-successful-py-test-run

So it's 'conflict' of `gevent` and `threading` modules?

**Comment by lukeyeager** [comment]
As I answered [here](http://stackoverflow.com/a/42701740/2404152),

1. We only officially support 14.04 and 16.04, not 12.04
2. Looks like probably a Python dependency version mismatch
