### ISSUE TITLE
Can not start digits devserver - caffe executable not found

### ISSUE THREAD

**Issue by machomachopadre** [NVIDIA/DIGITS#1513]
Hi,
I am facing a peculiar error when launching the digits devserver. It's telling me thaat it can't find the caffe executable. However, I have caffe up and running, with all the paths configured correctly. CAFFE_ROOT also points to my caffe installation. In attempts to fix this I also rebuilt caffe using make (not cmake). What could be going wrong?

Output:

```
"/home/me/folder/caffe" from CAFFE_ROOT does not point to a valid installation of Caffe.
Use the envvar CAFFE_ROOT to indicate a valid installation.
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/me/digits/digits/__main__.py", line 70, in <module>
    main()
  File "/home/me/digits/digits/__main__.py", line 53, in main
    import digits.config
  File "digits/config/__init__.py", line 7, in <module>
    from . import (  # noqa
  File "digits/config/caffe.py", line 226, in <module>
    executable, version, flavor = load_from_envvar('CAFFE_ROOT')
  File "digits/config/caffe.py", line 33, in load_from_envvar
    % executable_dir)
ValueError: Caffe executable not found at "/home/me/folder/caffe/build/tools"

```
System specifications:
OS- Ubuntu 14.04 LTS
Cuda version- 7.5
Digits version- 5
GPU- Nvidia Geforce GTX 960 4GB
CPU- AMD FX-4350

Thanks

**Comment by rodrigoberriel** [comment]
Did you check it Caffe executable is at `/home/me/folder/caffe/build/tools`? Did you run `make install` after `make` when building Caffe?

**Comment by machomachopadre** [comment]
@rodrigoberriel I originally built caffe with the officially supported `make` instead of the community driven `cmake`. From what I understand, `make` doesn't utilize the `build` folder at all. That might have been the problem. When I tried with cmake I faced a weird error regarding linking caffe executables (https://github.com/BVLC/caffe/issues/5396). So currently I'm just in a loop of errors :(
Thanks for responding, though :+1:

**Comment by rodrigoberriel** [comment]
Well, I'd consider installing NVIDIA-Caffe on another dir and proceed to the DIGITS installation. Remember to check if Caffe is working before installing DIGITS. If your problem is about the Caffe installation, this issue may be closed, right @machomachopadre? This is not a DIGITS problem.

**Comment by machomachopadre** [comment]
Sure @rodrigoberriel. No problem as it is irrelevant here :+1:

**Comment by eric8730** [comment]
i have received this error. I have installed all of the prerequisites. I have the CAFFE_ROOT in /home/user/caffe which is a path.

  ___ ___ ___ ___ _____ ___
 |   \_ _/ __|_ _|_   _/ __|
 | |) | | (_ || |  | | \__ \
 |___/___\___|___| |_| |___/ 6.1.1

A valid Caffe installation was not found on your system.
Use the envvar CAFFE_ROOT to indicate a valid installation.
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/mikulis/digits/digits/__main__.py", line 70, in <module>
    main()
  File "/home/mikulis/digits/digits/__main__.py", line 53, in main
    import digits.config
  File "digits/config/__init__.py", line 7, in <module>
    from . import (  # noqa
  File "digits/config/caffe.py", line 230, in <module>
    executable, version, flavor = load_from_path()
  File "digits/config/caffe.py", line 54, in load_from_path
    raise ValueError('Caffe executable not found in PATH')
ValueError: Caffe executable not found in PATH

**Comment by eric8730** [comment]
after months of trying to fix this issue, I am now here at this error when I type ./digits-devserver -p 5000

 ```
 File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/mikulis/digits/digits/__main__.py", line 70, in <module>
    main()
  File "/home/mikulis/digits/digits/__main__.py", line 53, in main
    import digits.config
  File "digits/config/__init__.py", line 7, in <module>
    from . import (  # noqa
  File "digits/config/caffe.py", line 13, in <module>
    from digits.utils import parse_version
  File "digits/utils/__init__.py", line 5, in <module>
    from io import BlockingIOError
  File "/home/mikulis/caffe/python/caffe/io.py", line 1, in <module>
    import numpy as np
  File "/home/mikulis/caffe/python/caffe/numpy/__init__.py", line 142, in <module>
    from . import add_newdocs
  File "/home/mikulis/caffe/python/caffe/numpy/add_newdocs.py", line 13, in <module>
    from numpy.lib import add_newdoc
  File "/home/mikulis/caffe/python/caffe/numpy/lib/__init__.py", line 24, in <module>
    from .npyio import *
  File "/home/mikulis/caffe/python/caffe/numpy/lib/npyio.py", line 14, in <module>
    from ._datasource import DataSource
  File "/home/mikulis/caffe/python/caffe/numpy/lib/_datasource.py", line 220, in <module>
    _file_openers = _FileOpeners()
  File "/home/mikulis/caffe/python/caffe/numpy/lib/_datasource.py", line 162, in __init__
    self._file_openers = {None: io.open}

```

**Comment by eric8730** [comment]
@lukeyeager i was told that you could help me.
after months of trying to fix this issue, I am now here at this error when I type ./digits-devserver -p 5000

 ```
 File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/mikulis/digits/digits/__main__.py", line 70, in <module>
    main()
  File "/home/mikulis/digits/digits/__main__.py", line 53, in main
    import digits.config
  File "digits/config/__init__.py", line 7, in <module>
    from . import (  # noqa
  File "digits/config/caffe.py", line 13, in <module>
    from digits.utils import parse_version
  File "digits/utils/__init__.py", line 5, in <module>
    from io import BlockingIOError
  File "/home/mikulis/caffe/python/caffe/io.py", line 1, in <module>
    import numpy as np
  File "/home/mikulis/caffe/python/caffe/numpy/__init__.py", line 142, in <module>
    from . import add_newdocs
  File "/home/mikulis/caffe/python/caffe/numpy/add_newdocs.py", line 13, in <module>
    from numpy.lib import add_newdoc
  File "/home/mikulis/caffe/python/caffe/numpy/lib/__init__.py", line 24, in <module>
    from .npyio import *
  File "/home/mikulis/caffe/python/caffe/numpy/lib/npyio.py", line 14, in <module>
    from ._datasource import DataSource
  File "/home/mikulis/caffe/python/caffe/numpy/lib/_datasource.py", line 220, in <module>
    _file_openers = _FileOpeners()
  File "/home/mikulis/caffe/python/caffe/numpy/lib/_datasource.py", line 162, in __init__
    self._file_openers = {None: io.open}

```

**Comment by vihari1729** [comment]
___ ___ ___ ___ _____ ___
 |   \_ _/ __|_ _|_   _/ __|
 | |) | | (_ || |  | | \__ \
 |___/___\___|___| |_| |___/ 6.1.1

"/home/lenovo/caffe" from CAFFE_ROOT does not point to a valid installation of Caffe.
Use the envvar CAFFE_ROOT to indicate a valid installation.
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/lenovo/digits/digits/__main__.py", line 70, in <module>
    main()
  File "/home/lenovo/digits/digits/__main__.py", line 53, in main
    import digits.config
  File "digits/config/__init__.py", line 7, in <module>
    from . import (  # noqa
  File "digits/config/caffe.py", line 226, in <module>
    executable, version, flavor = load_from_envvar('CAFFE_ROOT')
  File "digits/config/caffe.py", line 33, in load_from_envvar
    % executable_dir)
ValueError: Caffe executable not found at "/home/lenovo/caffe/build/tools"

**Comment by vihari1729** [comment]
can anyone help me in getting the solution.thanks

**Comment by tuskiomi** [comment]
I'm also having the same issue, I think this should be re-opened, as there is no definite solution posted. My CAFFE_ROOT variable points to a place such that $CAFFE_ROOT/build/tools/caffe is the correct path to the executable. CAFFE_ROOT is set in /etc/environment, so it is very much global.

Here is my digits output:

  ___ ___ ___ ___ _____ ___
 |   \_ _/ __|_ _|_   _/ __|
 | |) | | (_ || |  | | \__ \
 |___/___\___|___| |_| |___/ 6.1.1

"/home/par/caffe/build" from CAFFE_ROOT does not point to a valid installation of Caffe.
Use the envvar CAFFE_ROOT to indicate a valid installation.
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/par/digits/digits/__main__.py", line 70, in <module>
    main()
  File "/home/par/digits/digits/__main__.py", line 53, in main
    import digits.config
  File "digits/config/__init__.py", line 7, in <module>
    from . import (  # noqa
  File "digits/config/caffe.py", line 226, in <module>
    executable, version, flavor = load_from_envvar('CAFFE_ROOT')
  File "digits/config/caffe.py", line 33, in load_from_envvar
    % executable_dir)
ValueError: Caffe executable not found at "/home/par/caffe/build/build/tools"

**Comment by tuskiomi** [comment]
After checking the file system, I can run caffe, and no chmod was needed, so the pathing is valid. I suspect this is an issue with the python script
