### ISSUE TITLE
ERROR: 'SolverParameter' object has no attribute 'RMSPROP'

### ISSUE THREAD

**Issue by shanYanGuan** [NVIDIA/DIGITS#1518]
when I try the [Getting Started](https://github.com/NVIDIA/DIGITS/blob/master/docs/GettingStarted.md),a bug shows up.
`Traceback (most recent call last):
  File "digits/scheduler.py", line 512, in run_task
    task.run(resources)
  File "digits/task.py", line 189, in run
    self.before_run()
  File "digits/model/tasks/caffe_train.py", line 218, in before_run
    self.save_files_classification()
  File "digits/model/tasks/caffe_train.py", line 597, in save_files_classification
    if solver.solver_type == solver.RMSPROP:
AttributeError: 'SolverParameter' object has no attribute 'RMSPROP'
`
system:ubuntu16.04 ;
I used the caffe which have been rewrited.
Is something wrong in caffe I used or digits?  Could someone help me?

**Comment by shanYanGuan** [comment]
when I delete this code:if solver.solver_type == solver.RMSPROP: AttributeError: 'SolverParameter
my train recovered.
But I want konw the real reason why this bug arised.

**Comment by mahfuj9346449** [comment]
How you delete this code ?
