### ISSUE TITLE
Can't launch server on Mac OSX

### ISSUE THREAD

**Issue by noradaiko** [NVIDIA/DIGITS#154]
Hi, I'm working on Mac OSX.
Successfully built Nvidia fork of Caffe enabled CUDA.
I have configured the server with `./digits-devserver --config`.
I got an error when launching it like below:

```
$ ./digits-devserver
  ___ ___ ___ ___ _____ ___
 |   \_ _/ __|_ _|_   _/ __|
 | |) | | (_ || |  | | \__ \
 |___/___\___|___| |_| |___/

Traceback (most recent call last):
  File "./digits-devserver", line 41, in <module>
    from digits.webapp import app, socketio, scheduler
  File "/.../digits/digits/webapp.py", line 44, in <module>
    import digits.views
  File "/.../digits/digits/views.py", line 15, in <module>
    import model.views
  File "/.../digits/digits/model/views.py", line 24, in <module>
    import images.views
  File "/.../digits/digits/model/images/views.py", line 4, in <module>
    import classification.views
  File "/.../digits/digits/model/images/classification/views.py", line 25, in <module>
    from forms import ImageClassificationModelForm
  File "/.../digits/digits/model/images/classification/forms.py", line 6, in <module>
    from ..forms import ImageModelForm
  File "/.../digits/digits/model/images/forms.py", line 6, in <module>
    from ..forms import ModelForm
  File "/.../digits/digits/model/forms.py", line 20, in <module>
    class ModelForm(Form):
  File "/.../digits/digits/model/forms.py", line 204, in ModelForm
    ) for index in config_value('gpu_list').split(',') if index],
TypeError: argument of type 'NoneType' is not iterable
```

It seems an error occurs here due to fail to load `libnvidia-ml`:
https://github.com/NVIDIA/DIGITS/blob/master/digits/device_query.py#L181

This library is a part of [NVIDIA Management Library (NVML)](https://developer.nvidia.com/nvidia-management-library-nvml) and it's included in [GPU Deployment Kit](https://developer.nvidia.com/gpu-deployment-kit) but it is NOT provided for Mac OSX.

Is there a way to avoid it, or should I use CPU_ONLY mode?

**Comment by lukeyeager** [comment]
Quick question: are you working with the latest version of the code?

> It seems an error occurs here due to fail to load libnvidia-ml ... NVML is NOT provided for Mac OSX

I know, DIGITS should work if NVML isn't found on the system.

When you configured your application, did you choose any GPUs? It's strange that you built caffe with CUDA support and yet selected nothing for your "gpu_list". There shouldn't be any errors anyway - that's a bug. I'm just trying to figure out what you're doing.

**Comment by lukeyeager** [comment]
Found the bug. Thanks for reporting it!
