### ISSUE TITLE
ImportError: No module named store.views

### ISSUE THREAD

**Issue by ontheway16** [NVIDIA/DIGITS#1575]
Hello, I am facing the following issue and have no idea what caused such an error? I appreciate any comments. It was working well, just a couple of hours ago.

```
./digits-devserver
  ___ ___ ___ ___ _____ ___
 |   \_ _/ __|_ _|_   _/ __|
 | |) | | (_ || |  | | \__ \
 |___/___\___|___| |_| |___/ 5.1-dev

Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/alper/digits/digits/__main__.py", line 70, in <module>
    main()
  File "/home/alper/digits/digits/__main__.py", line 55, in main
    import digits.webapp
  File "digits/webapp.py", line 70, in <module>
    import digits.store.views  # noqa
ImportError: No module named store.views
Exception KeyError: KeyError(139676465870160,) in <module 'threading' from '/usr/lib/python2.7/threading.pyc'> ignored

```

**Comment by ontheway16** [comment]
Ok, problem solved by reinstalling DIGITS.
