### ISSUE TITLE
ERROR: Exception: LoadImageError: IOError:

### ISSUE THREAD

**Issue by zisianw** [NVIDIA/DIGITS#1583]
Has anyone encountered this error and know the way to solve it? Below is a log file from create_train_db_db.log

> 2017-04-17 15:56:31 [INFO ] Created features db for stage train_db in train_db/features
Exception in thread Thread-4:
Traceback (most recent call last):
File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
self.run()
File "/usr/lib/python2.7/dist-packages/digits/tools/create_generic_db.py", line 242, in run
feature, label = self.extension.encode_entry(entry_id)
File "/usr/lib/python2.7/dist-packages/digits/extensions/data/imageSegmentation/data.py", line 79, in encode_entry
image.load_image(feature_image_file),
File "/usr/lib/python2.7/dist-packages/digits/utils/image.py", line 65, in load_image
raise errors.LoadImageError, 'IOError: %s' % e.message
LoadImageError: IOError:
Exception in thread Thread-2:
Traceback (most recent call last):
File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
self.run()
File "/usr/lib/python2.7/dist-packages/digits/tools/create_generic_db.py", line 242, in run
feature, label = self.extension.encode_entry(entry_id)
File "/usr/lib/python2.7/dist-packages/digits/extensions/data/imageSegmentation/data.py", line 79, in encode_entry
image.load_image(feature_image_file),
File "/usr/lib/python2.7/dist-packages/digits/utils/image.py", line 65, in load_image
raise errors.LoadImageError, 'IOError: %s' % e.message
LoadImageError: IOError:
2017-04-17 15:56:32 [ERROR] LoadImageError: IOError:
2017-04-17 15:56:32 [ERROR] LoadImageError: IOError:
2017-04-17 15:56:32 [ERROR] Exception: LoadImageError: IOError:
Traceback (most recent call last):
File "/usr/lib/python2.7/dist-packages/digits/tools/create_generic_db.py", line 467, in <module>
args['stage']
File "/usr/lib/python2.7/dist-packages/digits/tools/create_generic_db.py", line 432, in create_generic_db
force_same_shape)
File "/usr/lib/python2.7/dist-packages/digits/tools/create_generic_db.py", line 333, in create_db
raise Exception(err)
Exception: LoadImageError: IOError:

**Comment by zisianw** [comment]
Update:
In case someone faces this in the future, here's a solution that worked for me.
Change the permission of the folders with the following line:
sudo chown -R username /path/to/directory

**Comment by prefpkg21** [comment]
I'm having a similar error i believe. Did you run that command inside the container or on the host? I am trying to do image detection, but get ERROR: Exception: LoadImageError: IOError: Trying to load "train/val/images/._<original-filename>"  I don't know why it is appending the "._" to the filename either
