### ISSUE TITLE
Error when load CAFFE_ROOT

### ISSUE THREAD

**Issue by shixpGit** [NVIDIA/DIGITS#1598]
Hi,@lukeyeager
I find a curious problem.

when I execute:
sudo ./digits-devserver, I got this:

Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/shixp/deep-learning/digits/digits/__main__.py", line 70, in <module>
    main()
  File "/home/shixp/deep-learning/digits/digits/__main__.py", line 53, in main
    import digits.config
  File "digits/config/__init__.py", line 7, in <module>
    from . import (  # noqa
  File "digits/config/caffe.py", line 237, in <module>
    executable, version, flavor = load_from_envvar('CAFFE_ROOT')
  File "digits/config/caffe.py", line 20, in load_from_envvar
    **value = os.environ[envvar].strip().strip("\"' ")**
  File "/usr/lib/python2.7/UserDict.py", line 23, in __getitem__
    raise KeyError(key)
KeyError: 'CAFFE_ROOT'

but When I use this command in python ，I got the right value:
>>> value = os.environ['CAFFE_ROOT'].strip().strip("\"' ")
>>> print value
/home/shixp/deep-learning/digits/caffe_nv/build/tools/caffe:/home/shixp/deep-learning/digits/caffe_nv/python/caffe/

so,is there any errors of my python enviroment?

thanks a lot:)

**Comment by ozkanmertozturk** [comment]
Hi,

You need a proper caffe installation(if you dont have) and CAFFE_ROOT variable have to include only caffe folder path. 

Take a look here,
https://github.com/NVIDIA/DIGITS/blob/master/docs/BuildCaffe.md
