### ISSUE TITLE
Net_Surgery

### ISSUE THREAD

**Issue by Alqazzaz** [NVIDIA/DIGITS#1626]
Hi,
In semantic _ segmentation example when I ran this command `$ ./net_surgery.py `
I got the following error :
```
I0504 19:57:51.662225  5823 net.cpp:791] Ignoring source layer data
I0504 19:57:51.698412  5823 net.cpp:791] Ignoring source layer loss
Loading FCN-Alexnet prototxt...
Traceback (most recent call last):
  File "/home/salma/DIGITS-master/examples/semantic-segmentation/net_surgery.py", line 65, in <module>
    generate_fcn()
  File "/home/salma/DIGITS-master/examples/semantic-segmentation/net_surgery.py", line 37, in generate_fcn
    fcn_alexnet = caffe.Net(FCN_ALEXNET_PROTOTXT_FILENAME, caffe.TEST)
RuntimeError: Could not open file fcn_alexnet.deploy.prototxt


```
Could you help me to solve that please?
I appreciate any help.

**Comment by RSly** [comment]
the error is written there:
=> Could not open file fcn_alexnet.deploy.prototxt

so make sure to put the fcn_alexnet files in the correct directory

**Comment by Alqazzaz** [comment]
Thank you , it worked
