### ISSUE TITLE
/site-packages/google/protobuf/descriptor.py", line 824, in __new__     return _message.default_pool.AddSerializedFile(serialized_pb)

### ISSUE THREAD

**Issue by aysegulucar2016** [NVIDIA/DIGITS#1627]
After successful build of bvlc/caffe, I  run digits. There was no problem.
But after install tensorflow I received below error:

 |   \_ _/ __|_ _|_   _/ __|
 | |) | | (_ || |  | | \__ \
 |___/___\___|___| |_| |___/ 5.1-dev

Traceback (most recent call last):
  File "/home/selman/anaconda2/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/home/selman/anaconda2/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/selman/digits/digits/__main__.py", line 70, in <module>
    main()
  File "/home/selman/digits/digits/__main__.py", line 55, in main
    import digits.webapp
  File "digits/webapp.py", line 15, in <module>
    import digits.scheduler  # noqa
  File "/home/selman/anaconda2/lib/python2.7/site-packages/gevent/builtins.py", line 93, in __import__
    result = _import(*args, **kwargs)
  File "digits/scheduler.py", line 20, in <module>
    from .model import ModelJob
  File "/home/selman/anaconda2/lib/python2.7/site-packages/gevent/builtins.py", line 93, in __import__
    result = _import(*args, **kwargs)
  File "digits/model/__init__.py", line 4, in <module>
    from .images import (
  File "/home/selman/anaconda2/lib/python2.7/site-packages/gevent/builtins.py", line 93, in __import__
    result = _import(*args, **kwargs)
  File "digits/model/images/__init__.py", line 4, in <module>
    from .classification import ImageClassificationModelJob
  File "/home/selman/anaconda2/lib/python2.7/site-packages/gevent/builtins.py", line 93, in __import__
    result = _import(*args, **kwargs)
  File "digits/model/images/classification/__init__.py", line 4, in <module>
    from .job import ImageClassificationModelJob
  File "/home/selman/anaconda2/lib/python2.7/site-packages/gevent/builtins.py", line 93, in __import__
    result = _import(*args, **kwargs)
  File "digits/model/images/classification/job.py", line 6, in <module>
    from ..job import ImageModelJob
  File "/home/selman/anaconda2/lib/python2.7/site-packages/gevent/builtins.py", line 93, in __import__
    result = _import(*args, **kwargs)
  File "digits/model/images/job.py", line 5, in <module>
    from ..job import ModelJob
  File "/home/selman/anaconda2/lib/python2.7/site-packages/gevent/builtins.py", line 93, in __import__
    result = _import(*args, **kwargs)
  File "digits/model/job.py", line 4, in <module>
    from . import tasks
  File "/home/selman/anaconda2/lib/python2.7/site-packages/gevent/builtins.py", line 93, in __import__
    result = _import(*args, **kwargs)
  File "digits/model/tasks/__init__.py", line 4, in <module>
    from .caffe_train import CaffeTrainTask
  File "/home/selman/anaconda2/lib/python2.7/site-packages/gevent/builtins.py", line 93, in __import__
    result = _import(*args, **kwargs)
  File "digits/model/tasks/caffe_train.py", line 28, in <module>
    import caffe_pb2
  File "/home/selman/anaconda2/lib/python2.7/site-packages/gevent/builtins.py", line 93, in __import__
    result = _import(*args, **kwargs)
  File "/home/selman/caffe/python/caffe/proto/caffe_pb2.py", line 21, in <module>
    12\x17\n\x0cnew_channels\x18= \x01(\x05:\x01\x30\x12\x15\n\nnew_height\x18> \x01(\x05:\x01\x30\x12\x14\n\tnew_width\x18? \x01(\x05:\x01\x30\x12\x1d\n\x0eshuffle_images\x18@ \x01(\x08:\x05\x66\x61lse\x12\x15\n\nconcat_dim\x18\x41 \x01(\r:\x01\x31\x12\x36\n\x11hdf5_output_param\x18\xe9\x07 \x01(\x0b\x32\x1a.caffe.HDF5OutputParameter\".\n\nPoolMethod\x12\x07\n\x03MAX\x10\x00\x12\x07\n\x03\x41VE\x10\x01\x12\x0e\n\nSTOCHASTIC\x10\x02\"W\n\x0ePReLUParameter\x12&\n\x06\x66iller\x18\x01 \x01(\x0b\x32\x16.caffe.FillerParameter\x12\x1d\n\x0e\x63hannel_shared\x18\x02 \x01(\x08:\x05\x66\x61lse*\x1c\n\x05Phase\x12\t\n\x05TRAIN\x10\x00\x12\x08\n\x04TEST\x10\x01'
  File "/home/selman/anaconda2/lib/python2.7/site-packages/google/protobuf/descriptor.py", line 824, in __new__
    return _message.default_pool.AddSerializedFile(serialized_pb)
TypeError: Couldn't build proto file into descriptor pool!
Invalid proto descriptor for file "caffe.proto":
  caffe.proto: A file with this name is already in the pool.

what is problem.

**Comment by artemiialessandrini** [comment]
Have you solved this problem?
@aysegulucar2016
