### ISSUE TITLE
The gevent-socketio package is incompatible with this version of the Flask-SocketIO extension. Please uninstall it, and then install the latest version of python-socketio in its place.

### ISSUE THREAD

**Issue by aysegulucar2016** [NVIDIA/DIGITS#1638]
The gevent-socketio package is incompatible with this version of the Flask-SocketIO extension. Please uninstall it, and then install the latest version of python-socketio in its place.

selman@selman-Inspiron-7559:~/digits$ ./digits-devserver
  ___ ___ ___ ___ _____ ___
 |   \_ _/ __|_ _|_   _/ __|
 | |) | | (_ || |  | | \__ \
 |___/___\___|___| |_| |___/ 5.1-dev

"/home/selman/caffe2/" from CAFFE_ROOT does not point to a valid installation of Caffe.
Use the envvar CAFFE_ROOT to indicate a valid installation.
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/selman/digits/digits/__main__.py", line 70, in <module>
    main()
  File "/home/selman/digits/digits/__main__.py", line 53, in main
    import digits.config
  File "digits/config/__init__.py", line 7, in <module>
    from . import (  # noqa
  File "digits/config/caffe.py", line 226, in <module>
    executable, version, flavor = load_from_envvar('CAFFE_ROOT')
  File "digits/config/caffe.py", line 33, in load_from_envvar
    % executable_dir)
ValueError: Caffe executable not found at "/home/selman/caffe2/build/tools"
selman@selman-Inspiron-7559:~/digits$ source ~/.profile
selman@selman-Inspiron-7559:~/digits$ echo $CAFFE_ROOT
/home/selman/caffe/
selman@selman-Inspiron-7559:~/digits$ ./digits-devserver
  ___ ___ ___ ___ _____ ___
 |   \_ _/ __|_ _|_   _/ __|
 | |) | | (_ || |  | | \__ \
 |___/___\___|___| |_| |___/ 5.1-dev

The gevent-socketio package is incompatible with this version of the Flask-SocketIO extension. Please uninstall it, and then install the latest version of python-socketio in its place.
selman@selman-Inspiron-7559:~/digits$ pip list
DEPRECATION: The default format will switch to columns in the future. You can use --format=(legacy|columns) (or define a format=(legacy|columns) in your pip.conf under the [list] section) to disable this warning.
actionlib (1.11.8)
adium-theme-ubuntu (0.3.4)
appdirs (1.4.3)
attrs (15.2.0)
autobahn (0.10.3)
backports-abc (0.5)
backports.shutil-get-terminal-size (1.0.0)
base-local-planner (1.14.0)
bleach (2.0.0)
blessings (1.6)
bondpy (1.7.18)
bzr (2.7.0)
camera-calibration (1.12.19)
camera-calibration-parsers (1.11.12)
camera-info-manager-py (0.2.3)
catkin (0.7.6)
catkin-pkg (0.3.1)
catkin-pkg-modules (0.3.1)
certifi (2017.4.17)
chardet (2.3.0)
charm-tools (2.1.2)
Cheetah (2.4.4)
colander (1.0b1)
configobj (5.0.6)
configparser (3.5.0)
cryptography (1.2.3)
cv-bridge (1.12.4)
cycler (0.9.0)
Cython (0.25.2)
decorator (4.0.6)
defusedxml (0.4.1)
diagnostic-analysis (1.8.10)
diagnostic-common-diagnostics (1.8.10)
diagnostic-updater (1.8.10)
docutils (0.12)
dynamic-reconfigure (1.5.46)
ecdsa (0.13)
empy (3.3.2)
entrypoints (0.2.2)
enum34 (1.1.2)
Flask (0.10.1)
Flask-SocketIO (2.6)
Flask-WTF (0.12)
funcsigs (0.4)
functools32 (3.2.3.post2)
futures (3.0.5)
gazebo-plugins (2.5.10)
gazebo-ros (2.5.10)
gencpp (0.5.5)
geneus (2.2.5)
genlisp (0.4.16)
genmsg (0.5.8)
gennodejs (2.0.1)
genpy (0.6.5)
gevent (1.1.0)
gevent-socketio (0.3.6)
gevent-websocket (0.9.3)
graphviz (0.7)
greenlet (0.4.9)
gunicorn (19.4.5)
h5py (2.6.0)
html5lib (0.999999999)
httplib2 (0.9.1)
hypothesis (3.8.3)
idna (2.0)
image-geometry (1.12.4)
iniparse (0.4)
interactive-markers (1.11.3)
ipaddress (1.0.16)
ipykernel (4.6.1)
ipython (5.3.0)
ipython-genutils (0.2.0)
ipywidgets (6.0.0)
itsdangerous (0.24)
Jinja2 (2.8)
jsonschema (2.5.1)
jujubundlelib (0.4.1)
jupyter (1.0.0)
jupyter-client (5.0.1)
jupyter-console (5.1.0)
jupyter-core (4.3.0)
keyring (7.3)
laser-geometry (1.6.4)
launchpadlib (1.10.3)
lazr.restfulclient (0.13.4)
lazr.uri (1.0.3)
leveldb (0.194)
libcharmstore (0.0.3)
linecache2 (1.0.0)
lmdb (0.87)
lz4 (0.7.0)
Markdown (2.6.6)
MarkupSafe (0.23)
matplotlib (1.5.1)
mercurial (3.7.3)
message-filters (1.12.7)
mistune (0.7.4)
mock (1.3.0)
mpi4py (1.3.1)
msgpack-python (0.4.6)
nao-apps (0.5.15)
naoqi-driver-py (0.5.5)
naoqi-pose (0.5.5)
naoqi-sensors-py (0.5.5)
naoqi-tools (0.5.5)
nbconvert (5.1.1)
nbformat (4.3.0)
ndg-httpsclient (0.4.0)
netifaces (0.10.4)
networkx (1.11)
nose (1.3.7)
notebook (5.0.0)
numpy (1.11.0)
oauth (1.0.1)
otherstuf (1.1.0)
packaging (16.8)
PAM (0.4.2)
pandas (0.19.2)
pandocfilters (1.4.1)
paramiko (1.16.0)
parse (1.6.6)
path.py (8.1.2)
pathlib2 (2.2.1)
pathspec (0.3.4)
pbr (1.8.0)
pexpect (4.2.1)
pickleshare (0.7.4)
Pillow (3.1.2)
pip (9.0.1)
pluginlib (1.10.4)
prompt-toolkit (1.0.14)
protobuf (2.6.1)
protobuf.socketrpc (1.3.2)
psutil (3.4.2)
ptyprocess (0.5.1)
pyasn1 (0.1.9)
pyasn1-modules (0.0.7)
pycrypto (2.6.1)
pycurl (7.43.0)
pydot (1.0.29)
Pygments (2.1)
pygobject (3.20.0)
pygpgme (0.3)
pyliblzma (0.5.3)
PyOpenGL (3.0.2)
pyOpenSSL (0.15.1)
pyparsing (2.2.0)
pyserial (3.0.1)
pysqlite (1.0.1)
Pyste (0.9.10)
python-apt (1.1.0b1)
python-dateutil (2.6.0)
python-engineio (1.3.2)
python-gflags (3.1.1)
python-nvd3 (0.14.2)
python-qt-binding (0.3.2)
python-slugify (1.1.4)
python-snappy (0.5)
python-socketio (1.7.4)
pytz (2014.10)
PyWavelets (0.5.2)
pyxdg (0.25)
PyYAML (3.11)
pyzmq (16.0.2)
qt-dotgraph (0.3.4)
qt-gui (0.3.4)
qt-gui-cpp (0.3.4)
qt-gui-py-common (0.3.4)
qtconsole (4.3.0)
requests (2.9.1)
resource-retriever (1.12.3)
roman (2.0.0)
rosbag (1.12.7)
rosboost-cfg (1.13.5)
rosclean (1.13.5)
roscreate (1.13.5)
rosdep (0.11.5)
rosdistro (0.6.2)
rosdistro-modules (0.6.2)
rosgraph (1.12.7)
rosinstall (0.7.8)
roslaunch (1.12.7)
roslib (1.13.5)
roslint (0.11.0)
roslz4 (1.12.7)
rosmake (1.13.5)
rosmaster (1.12.7)
rosmsg (1.12.7)
rosnode (1.12.7)
rosparam (1.12.7)
rospkg (1.1.0)
rospkg-modules (1.1.0)
rospy (1.12.7)
rosservice (1.12.7)
rostest (1.12.7)
rostopic (1.12.7)
rosunit (1.13.5)
roswtf (1.12.7)
rpm-python (4.12.0.1)
rqt-action (0.4.7)
rqt-bag (0.4.7)
rqt-bag-plugins (0.4.7)
rqt-console (0.4.7)
rqt-dep (0.4.7)
rqt-graph (0.4.7)
rqt-gui (0.3.2)
rqt-gui-py (0.3.2)
rqt-image-view (0.4.7)
rqt-launch (0.4.7)
rqt-logger-level (0.4.7)
rqt-moveit (0.5.6)
rqt-msg (0.4.7)
rqt-nav-view (0.5.6)
rqt-plot (0.4.7)
rqt-pose-view (0.5.6)
rqt-publisher (0.4.7)
rqt-py-common (0.4.7)
rqt-py-console (0.4.7)
rqt-reconfigure (0.4.7)
rqt-robot-dashboard (0.5.6)
rqt-robot-monitor (0.5.6)
rqt-robot-steering (0.5.6)
rqt-runtime-monitor (0.5.6)
rqt-rviz (0.5.6)
rqt-service-caller (0.4.7)
rqt-shell (0.4.7)
rqt-srv (0.4.7)
rqt-tf-tree (0.5.6)
rqt-top (0.4.7)
rqt-topic (0.4.7)
rqt-web (0.4.7)
ruamel.ordereddict (0.4.9)
ruamel.yaml (0.10.23)
rviz (1.12.4)
scandir (1.5)
scikit-fmm (0.0.9)
scikit-image (0.10.1)
scikit-learn (0.18.1)
scipy (0.17.0)
SecretStorage (2.1.3)
sensor-msgs (1.12.5)
service-identity (16.0.0)
setuptools (20.7.0)
simplegeneric (0.8.1)
simplejson (3.8.1)
singledispatch (3.4.0.3)
six (1.10.0)
smach (2.0.0)
smach-ros (2.0.0)
smclib (1.7.18)
stevedore (1.21.0)
stuf (0.9.16)
tensorflow-gpu (1.1.0)
terminado (0.6)
testpath (0.3)
testresources (1.0.0)
tf (1.11.8)
tf-conversions (1.11.8)
tf2-geometry-msgs (0.5.15)
tf2-kdl (0.5.15)
tf2-py (0.5.15)
tf2-ros (0.5.15)
theblues (0.2.0)
topic-tools (1.12.7)
tornado (4.5.1)
traceback2 (1.4.0)
traitlets (4.3.2)
translationstring (1.3)
trollius (2.0.1)
Twisted (16.0.0)
txaio (1.0.0)
udo (4.2.12)
Unidecode (0.4.20)
unittest2 (1.1.0)
unity-lens-photos (1.0)
urlgrabber (3.9.1)
urllib3 (1.13.1)
vcstools (0.1.39)
virtualenv (15.0.1)
virtualenv-clone (0.2.6)
virtualenvwrapper (4.7.2)
wadllib (1.3.2)
wcwidth (0.1.7)
webencodings (0.5.1)
Werkzeug (0.12.1)
wheel (0.29.0)
widgetsnbextension (2.0.0)
wstool (0.1.13)
WTForms (2.1)
xacro (1.11.2)
yum-metadata-parser (1.1.4)
zope.interface (4.1.3)

**Comment by lukeyeager** [comment]
> If you wish to continue using gevent, then uninstall gevent-socketio from your virtual environment, as this package is not used anymore and may collide with its replacement, python-socketio.
https://flask-socketio.readthedocs.io/en/latest/

You need to uninstall `gevent-socketio`. Your Python environment is pretty dirty (tons of packages). Consider using a clean virtualenv, deb packages, or a docker image.

**Comment by aysegulucar2016** [comment]
In fact present error was  appeared after tensorflow installtion and many many tring._
my previous gevent-socketio unistallation had not work for digit.  That time, error was no moudle sketio.

I will intestigate virtualenv for digits or flash-soketio. 
 Many thanks

**Comment by aysegulucar2016** [comment]
sudo apt-get remove python-gevent-socketio
deactivate
rm -rf venv

# make and activate a new one (without the --sytem-site-packages flag)
virtualenv venv
source venv/bin/activate

# install only what you need
pip install -r $CAFFE_ROOT/python/requirements.txt
pip install -r $DIGITS_ROOT/requirements.txt
then 
root@selman-Inspiron-7559:/home/selman/DIGITS# ./digits-devserver
  ___ ___ ___ ___ _____ ___
 |   \_ _/ __|_ _|_   _/ __|
 | |) | | (_ || |  | | \__ \
 |___/___\___|___| |_| |___/ 5.1-dev

Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/selman/DIGITS/digits/__main__.py", line 70, in <module>
    main()
  File "/home/selman/DIGITS/digits/__main__.py", line 55, in main
    import digits.webapp
  File "digits/webapp.py", line 7, in <module>
    from flask.ext.socketio import SocketIO
  File "/usr/local/lib/python2.7/dist-packages/flask/exthook.py", line 81, in load_module
    reraise(exc_type, exc_value, tb.tb_next)
  File "/usr/local/lib/python2.7/dist-packages/flask_socketio/__init__.py", line 16, in <module>
    import socketio
ImportError: No module named socketio

**Comment by lukeyeager** [comment]
Why are you running as root? When you switch your user to root, you lose most of your environment settings, possibly including the ones set up by your virtualenv.

**Comment by aysegulucar2016** [comment]
Without sudo
selman@selman-Inspiron-7559:~$ virtualenv venv
Running virtualenv with interpreter /usr/bin/python2
New python executable in /home/selman/venv/bin/python2
Not overwriting existing python script /home/selman/venv/bin/python (you must use /home/selman/venv/bin/python2)
Installing setuptools, pkg_resources, pip, wheel...
  Complete output from command /home/selman/venv/bin/python2 - setuptools pkg_resources pip wheel:
  Traceback (most recent call last):
  File "<stdin>", line 7, in <module>
  File "/usr/share/python-wheels/pip-8.1.1-py2.py3-none-any.whl/pip/__init__.py", line 16, in <module>
  File "/usr/share/python-wheels/pip-8.1.1-py2.py3-none-any.whl/pip/vcs/subversion.py", line 9, in <module>
  File "/usr/share/python-wheels/pip-8.1.1-py2.py3-none-any.whl/pip/index.py", line 30, in <module>
  File "/usr/share/python-wheels/pip-8.1.1-py2.py3-none-any.whl/pip/wheel.py", line 39, in <module>
  File "/home/selman/venv/share/python-wheels/distlib-0.2.2-py2.py3-none-any.whl/distlib/scripts.py", line 14, in <module>
  File "/home/selman/venv/share/python-wheels/distlib-0.2.2-py2.py3-none-any.whl/distlib/compat.py", line 31, in <module>
ImportError: cannot import name HTTPSHandler
----------------------------------------
...Installing setuptools, pkg_resources, pip, wheel...done.
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/virtualenv.py", line 2363, in <module>
    main()
  File "/usr/lib/python2.7/dist-packages/virtualenv.py", line 719, in main
    symlink=options.symlink)
  File "/usr/lib/python2.7/dist-packages/virtualenv.py", line 988, in create_environment
    download=download,
  File "/usr/lib/python2.7/dist-packages/virtualenv.py", line 918, in install_wheel
    call_subprocess(cmd, show_stdout=False, extra_env=env, stdin=SCRIPT)
  File "/usr/lib/python2.7/dist-packages/virtualenv.py", line 812, in call_subprocess
    % (cmd_desc, proc.returncode))
OSError: Command /home/selman/venv/bin/python2 - setuptools pkg_resources pip wheel failed with error code 1
selman@selman-Inspiron-7559:~$ virtualenv venv
Running virtualenv with interpreter /usr/bin/python2
New python executable in /home/selman/venv/bin/python2
Not overwriting existing python script /home/selman/venv/bin/python (you must use /home/selman/venv/bin/python2)
Installing setuptools, pkg_resources, pip, wheel...
  Complete output from command /home/selman/venv/bin/python2 - setuptools pkg_resources pip wheel:
  Traceback (most recent call last):
  File "<stdin>", line 7, in <module>
  File "/usr/share/python-wheels/pip-8.1.1-py2.py3-none-any.whl/pip/__init__.py", line 16, in <module>
  File "/usr/share/python-wheels/pip-8.1.1-py2.py3-none-any.whl/pip/vcs/subversion.py", line 9, in <module>
  File "/usr/share/python-wheels/pip-8.1.1-py2.py3-none-any.whl/pip/index.py", line 30, in <module>
  File "/usr/share/python-wheels/pip-8.1.1-py2.py3-none-any.whl/pip/wheel.py", line 39, in <module>
  File "/home/selman/venv/share/python-wheels/distlib-0.2.2-py2.py3-none-any.whl/distlib/scripts.py", line 14, in <module>
  File "/home/selman/venv/share/python-wheels/distlib-0.2.2-py2.py3-none-any.whl/distlib/compat.py", line 31, in <module>
ImportError: cannot import name HTTPSHandler
----------------------------------------
...Installing setuptools, pkg_resources, pip, wheel...done.
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/virtualenv.py", line 2363, in <module>
    main()
  File "/usr/lib/python2.7/dist-packages/virtualenv.py", line 719, in main
    symlink=options.symlink)
  File "/usr/lib/python2.7/dist-packages/virtualenv.py", line 988, in create_environment
    download=download,
  File "/usr/lib/python2.7/dist-packages/virtualenv.py", line 918, in install_wheel
    call_subprocess(cmd, show_stdout=False, extra_env=env, stdin=SCRIPT)
  File "/usr/lib/python2.7/dist-packages/virtualenv.py", line 812, in call_subprocess
    % (cmd_desc, proc.returncode))
OSError: Command /home/selman/venv/bin/python2 - setuptools pkg_resources pip wheel failed with error code 1
selman@selman-Inspiron-7559:~$
