### ISSUE TITLE
Jetson TK1: create_db.py: OverflowError: Integer argument exceeds limit.

### ISSUE THREAD

**Issue by coreyt** [NVIDIA/DIGITS#164]
I am working on getting DIGITS running on the Jetson TK1.

I ran into a problem when creating the training and validation databases:
```
127.0.0.1 - - [2015-07-11 11:39:04] "POST /datasets/images/classification HTTP/1.1" 302 450 0.444721
127.0.0.1 - - [2015-07-11 11:39:04] "GET /datasets/20150711-113903-e21a HTTP/1.1" 200 16142 0.263104
2015-07-11 11:39:04 [20150711-113903-e21a] [DEBUG] Parse Folder (train/val) task started.
2015-07-11 11:39:04 [20150711-113903-e21a] [INFO ] Parse Folder (train/val) task started.
2015-07-11 11:39:09 [20150711-113903-e21a] [INFO ] Parse Folder (train/val) task completed.
2015-07-11 11:39:09 [20150711-113903-e21a] [DEBUG] Create DB (train) task started.
2015-07-11 11:39:09 [20150711-113903-e21a] [DEBUG] Create DB (val) task started.
2015-07-11 11:39:09 [20150711-113903-e21a] [INFO ] Create DB (train) task started.
2015-07-11 11:39:09 [20150711-113903-e21a] [INFO ] Create DB (val) task started.
2015-07-11 11:39:11 [20150711-113903-e21a] [WARNING] Create DB (train) unrecognized output: Traceback (most recent call last):
2015-07-11 11:39:11 [20150711-113903-e21a] [WARNING] Create DB (train) unrecognized output: File "/home/ubuntu/DIGITS/tools/create_db.py", line 539, in <module>
2015-07-11 11:39:11 [20150711-113903-e21a] [WARNING] Create DB (train) unrecognized output: backend=args['backend'])
2015-07-11 11:39:11 [20150711-113903-e21a] [WARNING] Create DB (train) unrecognized output: File "/home/ubuntu/DIGITS/tools/create_db.py", line 66, in __init__
2015-07-11 11:39:11 [20150711-113903-e21a] [WARNING] Create DB (train) unrecognized output: max_dbs=0)
2015-07-11 11:39:11 [20150711-113903-e21a] [WARNING] Create DB (train) unrecognized output: OverflowError: Integer argument exceeds limit.
2015-07-11 11:39:11 [20150711-113903-e21a] [WARNING] Create DB (val) unrecognized output: Traceback (most recent call last):
2015-07-11 11:39:11 [20150711-113903-e21a] [WARNING] Create DB (val) unrecognized output: File "/home/ubuntu/DIGITS/tools/create_db.py", line 539, in <module>
2015-07-11 11:39:11 [20150711-113903-e21a] [WARNING] Create DB (val) unrecognized output: backend=args['backend'])
2015-07-11 11:39:11 [20150711-113903-e21a] [WARNING] Create DB (val) unrecognized output: File "/home/ubuntu/DIGITS/tools/create_db.py", line 66, in __init__
2015-07-11 11:39:11 [20150711-113903-e21a] [WARNING] Create DB (val) unrecognized output: max_dbs=0)
2015-07-11 11:39:11 [20150711-113903-e21a] [WARNING] Create DB (val) unrecognized output: OverflowError: Integer argument exceeds limit.
2015-07-11 11:39:11 [20150711-113903-e21a] [ERROR] Create DB (train) task failed with error code 1
2015-07-11 11:39:11 [20150711-113903-e21a] [ERROR] Create DB (val) task failed with error code 1
```

This is resolved by editing the file ```DIGITS/tools/create_db.py```:
```
            self.db = lmdb.open(self.output_path,
                    map_size=2147483647, # 2^31-1. was: map_size=1000000000000,  ~1TB for 64-bit machines
                    map_async=True,
 ```

This is not the only place where we run into magic number problems on the Jetson.

**Comment by coreyt** [comment]
Since the solution is in the issue, closing.  Hopefully others will be able to search and find the answer here!
