### ISSUE TITLE
digits error

### ISSUE THREAD

**Issue by wozqh** [NVIDIA/DIGITS#1641]
# when I input ./digits-devserver, an error occur,

# this is the error information, my caffe is in /home/mx/caffe/

"/home/ubuntu/caffe/" from CAFFE_ROOT does not point to a valid installation of Caffe.
Use the envvar CAFFE_ROOT to indicate a valid installation.
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/ubuntu/disk1/DIGITS/digits/__main__.py", line 70, in <module>
    main()
  File "/home/ubuntu/disk1/DIGITS/digits/__main__.py", line 53, in main
    import digits.config
  File "digits/config/__init__.py", line 7, in <module>
    from . import (  # noqa
  File "digits/config/caffe.py", line 226, in <module>
    executable, version, flavor = load_from_envvar('CAFFE_ROOT')
  File "digits/config/caffe.py", line 33, in load_from_envvar
    % executable_dir)
ValueError: Caffe executable not found at "/home/ubuntu/caffe/build/tools"

**Comment by lukeyeager** [comment]
Looks like your `CAFFE_ROOT` envvar points to `/home/ubuntu/caffe`. If your caffe build is at `/home/mx/caffe`, then change your envvar.
