### ISSUE TITLE
Jetson TK1: scikit-image or matplotlib: compile error

### ISSUE THREAD

**Issue by coreyt** [NVIDIA/DIGITS#165]
When on a Jetson board, caffe can compile with no errors. However, when importing the caffe module, the following error is thrown:
```
>>> import caffe
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "caffe/__init__.py", line 1, in <module>
    from .pycaffe import Net, SGDSolver
  File "caffe/pycaffe.py", line 13, in <module>
    import caffe.io
  File "caffe/io.py", line 2, in <module>
    import skimage.io
ImportError: No module named skimage.io
```

In this case, ```scikit-image``` was not installed, likely due to a compilation error for ```matplotlib```. However, when trying to install scikit-image, you may see an error like this:
```
(venv)ubuntu@tegra-ubuntu:~/DIGITS$ pip install matplotlib
Collecting matplotlib
/home/ubuntu/DIGITS/venv/local/lib/python2.7/site-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
  Downloading matplotlib-1.4.3.tar.gz (50.4MB)
    99% |████████████████████████████████| 50.4MB 1.1MB/s eta 0:00:01Exception:
Traceback (most recent call last):
  File "/home/ubuntu/DIGITS/venv/local/lib/python2.7/site-packages/pip/basecommand.py", line 223, in main
    status = self.run(options, args)
  File "/home/ubuntu/DIGITS/venv/local/lib/python2.7/site-packages/pip/commands/install.py", line 293, in run
    wb.build(autobuilding=True)
  File "/home/ubuntu/DIGITS/venv/local/lib/python2.7/site-packages/pip/wheel.py", line 705, in build
    self.requirement_set.prepare_files(self.finder)
  File "/home/ubuntu/DIGITS/venv/local/lib/python2.7/site-packages/pip/req/req_set.py", line 334, in prepare_files
    functools.partial(self._prepare_file, finder))
  File "/home/ubuntu/DIGITS/venv/local/lib/python2.7/site-packages/pip/req/req_set.py", line 321, in _walk_req_to_install
    more_reqs = handler(req_to_install)
  File "/home/ubuntu/DIGITS/venv/local/lib/python2.7/site-packages/pip/req/req_set.py", line 491, in _prepare_file
    session=self.session)
  File "/home/ubuntu/DIGITS/venv/local/lib/python2.7/site-packages/pip/download.py", line 825, in unpack_url
    session,
  File "/home/ubuntu/DIGITS/venv/local/lib/python2.7/site-packages/pip/download.py", line 673, in unpack_http_url
    from_path, content_type = _download_http_url(link, session, temp_dir)
  File "/home/ubuntu/DIGITS/venv/local/lib/python2.7/site-packages/pip/download.py", line 886, in _download_http_url
    _download_url(resp, link, content_file)
  File "/home/ubuntu/DIGITS/venv/local/lib/python2.7/site-packages/pip/download.py", line 621, in _download_url
    for chunk in progress_indicator(resp_read(4096), 4096):
  File "/home/ubuntu/DIGITS/venv/local/lib/python2.7/site-packages/pip/utils/ui.py", line 133, in iter
    for x in it:
  File "/home/ubuntu/DIGITS/venv/local/lib/python2.7/site-packages/pip/download.py", line 586, in resp_read
    decode_content=False):
  File "/home/ubuntu/DIGITS/venv/local/lib/python2.7/site-packages/pip/_vendor/requests/packages/urllib3/response.py", line 307, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "/home/ubuntu/DIGITS/venv/local/lib/python2.7/site-packages/pip/_vendor/requests/packages/urllib3/response.py", line 243, in read
    data = self._fp.read(amt)
  File "/home/ubuntu/DIGITS/venv/local/lib/python2.7/site-packages/pip/_vendor/cachecontrol/filewrapper.py", line 54, in read
    self.__callback(self.__buf.getvalue())
  File "/home/ubuntu/DIGITS/venv/local/lib/python2.7/site-packages/pip/_vendor/cachecontrol/controller.py", line 224, in cache_response
    self.serializer.dumps(request, response, body=body),
  File "/home/ubuntu/DIGITS/venv/local/lib/python2.7/site-packages/pip/_vendor/cachecontrol/serialize.py", line 81, in dumps
    ).encode("utf8"),
MemoryError
```

To resolve the installation / compilation issue on the Jetson, a swapdisk will resolve the issue.  A related Q&A is here, with a good answer you should be able to cut-and-paste as root:
http://stackoverflow.com/a/29467260/307084

i.e.
```
# create swap file of 512 MB
dd if=/dev/zero of=/swapfile bs=1024 count=524288
# modify permissions
chown root:root /swapfile
chmod 0600 /swapfile
# setup swap area
mkswap /swapfile
# turn swap on
swapon /swapfile
```

**Comment by coreyt** [comment]
Since the solution is in the issue, closing.  Hopefully others will be able to search and find the answer here!
