### ISSUE TITLE
Create Dataset issues on ubuntu 16.04 ("folder does not exist")

### ISSUE THREAD

**Issue by alushnikov** [NVIDIA/DIGITS#1666]
Hi!

Decided to give DIGITS 5 a try on Ubuntu 16.04.2
On clean installation of 16.04.2 installed everything as described on [nvidia's website](https://developer.nvidia.com/rdp/digits-download)

When trying to run DIGITS got the following error:
```
$ digits-devserver 
  ___ ___ ___ ___ _____ ___
 |   \_ _/ __|_ _|_   _/ __|
 | |) | | (_ || |  | | \__ \
 |___/___\___|___| |_| |___/ 5.0.0

"/usr/lib/python2.7/dist-packages/digits/jobs" is not a valid value for jobs_dir.
Set the envvar DIGITS_JOBS_DIR to fix your configuration.
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/lib/python2.7/dist-packages/digits/__main__.py", line 66, in <module>
    main()
  File "/usr/lib/python2.7/dist-packages/digits/__main__.py", line 49, in main
    import digits.config
  File "/usr/lib/python2.7/dist-packages/digits/config/__init__.py", line 9, in <module>
    from . import jobs_dir
  File "/usr/lib/python2.7/dist-packages/digits/config/jobs_dir.py", line 27, in <module>
    os.makedirs(value)
  File "/usr/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 13] Permission denied: '/usr/lib/python2.7/dist-packages/digits/jobs'
```

Even though config file shows different jobs dir
```
# DIGITS systemd service
[Unit]
Description=DIGITS server
After=local-fs.target network.target

[Service]
User=www-data
Environment="DIGITS_JOBS_DIR=/var/lib/digits/jobs"
Environment="DIGITS_LOGFILE_FILENAME=/var/log/digits/digits.log"
ExecStart=/usr/bin/python -m digits -p 34448
Restart=on-failure
ExecStop=/bin/kill -INT $MAINPID

[Install]
WantedBy=multi-user.target
```

Nevertheless DIGITS runs fine with sudo.

**Comment by lukeyeager** [comment]
`digits-devserver` is just a thin wrapper around the command `python -m digits`. It's not going to use any systemd settings. It will start on port 5000 by default.

The deb package installs a systemd service (check status with `systemctl status digits.service`). It should be running at ports 34448 and 80.

**Comment by alushnikov** [comment]
Cool, thanks!
