### ISSUE TITLE
DetectNet for 5 classes Error -1 Unexpected number of classes: 5 != 1

### ISSUE THREAD

**Issue by GabrielGlzSa** [NVIDIA/DIGITS#1669]
Hello,

I want my network to detect five classes. I was able to train without problems, but when I try to Test One image I get the following error:
`2017-06-05 15:19:47 [ERROR] ValueError: Unexpected number of classes: 5 != 1, bottom[0] shape=(1, 5, 3, 10)
Traceback (most recent call last):
File "/usr/lib/python2.7/dist-packages/digits/tools/inference.py", line 293, in <module>
args['resize']
File "/usr/lib/python2.7/dist-packages/digits/tools/inference.py", line 159, in infer
resize=resize)
File "/usr/lib/python2.7/dist-packages/digits/model/tasks/caffe_train.py", line 1239, in infer_one
resize=resize
File "/usr/lib/python2.7/dist-packages/digits/model/tasks/caffe_train.py", line 1262, in infer_one_image
net = self.get_net(snapshot_epoch, gpu=gpu)
File "/usr/lib/python2.7/dist-packages/digits/model/tasks/caffe_train.py", line 1507, in get_net
caffe.TEST)
File "/usr/lib/python2.7/dist-packages/caffe/layers/detectnet/clustering.py", line 125, in reshape
raise ValueError("Unexpected number of classes: %d != %d, bottom[0] shape=%s" % (num_classes, self.num_classes, repr(bottom[0].data.shape)))
ValueError: Unexpected number of classes: 5 != 1, bottom[0] shape=(1, 5, 3, 10)
        `

I modified [detectnet_network-2classes.prototxt](https://github.com/NVIDIA/caffe/blob/caffe-0.15/examples/kitti/detectnet_network-2classes.prototxt) for detecting 5 classes (numbers from 1 to 4 and an object). The changes I made were:

- Added 3 more classes after line [83](https://github.com/NVIDIA/caffe/blob/caffe-0.15/examples/kitti/detectnet_network-2classes.prototxt#L83)

- Added  3 more classes after line [123](https://github.com/NVIDIA/caffe/blob/caffe-0.15/examples/kitti/detectnet_network-2classes.prototxt#L123)

- Changed to 5 the value in line [2388](https://github.com/NVIDIA/caffe/blob/caffe-0.15/examples/kitti/detectnet_network-2classes.prototxt#L2388)

Thanks in advance for your help.

**Comment by GabrielGlzSa** [comment]
I used https://www.diffchecker.com/diff to check the differences between 1 class and 2 classes. Making corrections :)
