### ISSUE TITLE
ValueError when trying to create a new classification model

### ISSUE THREAD

**Issue by jjm0022** [NVIDIA/DIGITS#1679]
So digits was running great up until yesterday afternoon. I was playing around with custom networks and and a situation very similar to #831 occurred. This morning I removed the faulty job like was recommended in #831 and the models are showing up again.
Now when I try to create a new classification model I get "ValueError too many values to unpack". The same thing happens when I try to clone a previous model.  There's nothing useful showing up in digits.log to give me any idea as to what's causing this. Also, I have no problems reaching any of the other network types, it's only classification that is throwing this error.

**Comment by jjm0022** [comment]
Here's the traceback: 
```
 Traceback (most recent call last):
  File "/rgroup/dsig/pkgs/anaconda/envs/digits/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/rgroup/dsig/pkgs/anaconda/envs/digits/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/nas/rgroup/dsig/pkgs/DIGITS/digits/webapp.py", line 82, in decorated
    return f(*args, **kwargs)
  File "/nas/rgroup/dsig/pkgs/DIGITS/digits/utils/auth.py", line 55, in decorated
    return f(*args, **kwargs)
  File "/nas/rgroup/dsig/pkgs/DIGITS/digits/model/images/classification/views.py", line 85, in new
    multi_gpu=config_value('caffe')['multi_gpu'],
  File "/rgroup/dsig/pkgs/anaconda/envs/digits/lib/python2.7/site-packages/flask/templating.py", line 128, in render_template
    context, ctx.app)
  File "/rgroup/dsig/pkgs/anaconda/envs/digits/lib/python2.7/site-packages/flask/templating.py", line 110, in _render
    rv = template.render(context)
  File "/rgroup/dsig/pkgs/anaconda/envs/digits/lib/python2.7/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/rgroup/dsig/pkgs/anaconda/envs/digits/lib/python2.7/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/nas/rgroup/dsig/pkgs/DIGITS/digits/templates/models/images/classification/new.html", line 7, in top-level template code
    {% extends "layout.html" %}
  File "/nas/rgroup/dsig/pkgs/DIGITS/digits/templates/layout.html", line 86, in top-level template code
    {% block content %}
  File "/nas/rgroup/dsig/pkgs/DIGITS/digits/templates/models/images/classification/new.html", line 517, in block "content"
    {% include "models/images/classification/partials/new/network_tab_standard.html" %}
  File "/nas/rgroup/dsig/pkgs/DIGITS/digits/templates/models/images/classification/partials/new/network_tab_standard.html", line 23, in top-level template code
    {% for network in form.standard_networks %}
  File "/rgroup/dsig/pkgs/anaconda/envs/digits/lib/python2.7/site-packages/wtforms/fields/core.py", line 429, in __iter__
    for i, (value, label, checked) in enumerate(self.iter_choices()):
  File "/rgroup/dsig/pkgs/anaconda/envs/digits/lib/python2.7/site-packages/wtforms/fields/core.py", line 451, in iter_choices
    for value, label in self.choices:
ValueError: too many values to unpack
```

**Comment by lukeyeager** [comment]
You're using anaconda, so I bet the wrong version of some of the requirements. I'd check wtforms based on that traceback.

**Comment by jjm0022** [comment]
I tried creating a new environment and made sure the dependencies were all correct and I'm still getting the same error. Here is the output from `conda list` 
```
packages in environment at /rgroup/dsig/pkgs/anaconda/envs/digits_test:

backports                 1.0                      py27_0  
cycler                    0.10.0                    <pip>
decorator                 4.0.11                   py27_0  
enum34                    1.1.6                    py27_0  
Flask                     0.10.1                    <pip>
Flask-SocketIO            2.6                       <pip>
Flask-WTF                 0.12                      <pip>
get_terminal_size         1.0.0                    py27_0  
gevent                    1.1.0                     <pip>
gevent-websocket          0.9.3                     <pip>
greenlet                  0.4.12                    <pip>
h5py                      2.6.0                     <pip>
ipython                   5.3.0                    py27_0  
ipython_genutils          0.2.0                    py27_0  
itsdangerous              0.24                      <pip>
Jinja2                    2.9.6                     <pip>
libpng                    1.6.27                        0  
lmdb                      0.87                      <pip>
MarkupSafe                1.0                       <pip>
matplotlib                1.5.1                     <pip>
networkx                  1.11                      <pip>
numpy                     1.11.0                    <pip>
openssl                   1.0.2l                        0  
path.py                   10.3.1                   py27_0  
pathlib2                  2.2.1                    py27_0  
pexpect                   4.2.1                    py27_0  
pickleshare               0.7.4                    py27_0  
Pillow                    3.1.2                     <pip>
pip                       9.0.1                    py27_1  
prompt_toolkit            1.0.14                   py27_0  
protobuf                  2.6.1                     <pip>
psutil                    3.4.2                     <pip>
ptyprocess                0.5.1                    py27_0  
pydot                     1.0.29                    <pip>
pygments                  2.2.0                    py27_0  
pyparsing                 1.5.7                     <pip>
pyside                    1.2.1                    py27_1  
python                    2.7.13                        0  
python-dateutil           2.6.0                     <pip>
python-engineio           1.5.4                     <pip>
python-socketio           1.7.5                     <pip>
pytz                      2017.2                    <pip>
PyWavelets                0.5.2                     <pip>
qt                        4.8.5                         0  
readline                  6.2                           2  
requests                  2.9.1                     <pip>
scandir                   1.5                      py27_0  
scikit-fmm                0.0.9                     <pip>
scikit-image              0.13.0                    <pip>
scipy                     0.17.0                    <pip>
setuptools                20.7.0                   py27_0  
shiboken                  1.2.1                    py27_0  
simplegeneric             0.8.1                    py27_1  
six                       1.10.0                   py27_0  
sqlite                    3.13.0                        0  
tk                        8.5.18                        0  
traitlets                 4.3.2                    py27_0  
wcwidth                   0.1.7                    py27_0  
Werkzeug                  0.12.2                    <pip>
wheel                     0.29.0                   py27_0  
WTForms                   2.1                       <pip>
zlib                      1.2.8                         3 
```

I'm not very familiar with Flask or wtforms so I'm pretty lost on how to fix this.

**Comment by lukeyeager** [comment]
I suggest actually following the installation instructions we provide. While you should be able to make it work with Conda, that's not an installation path that we officially support or provide instructions for.
