### ISSUE TITLE
ValueError: could not broadcast input array from shape (51,5) into shape (50,5)

### ISSUE THREAD

**Issue by caleale90** [NVIDIA/DIGITS#1682]
Hi, I am facing the same error of the  #1235 issue.
I followed the @lukeyeager instruction and changed the variable MAX_BOXES = 150 in both files clustering.py and mean_ap.py. Then I recompiled the entire caffe library, but I obtain the same error.
This is the last part of my caffe_output.log file:

I0616 09:35:50.296716 5248 sgd_solver.cpp:106] Iteration 20000, lr = 0.0001
I0616 09:40:43.958341 5248 solver.cpp:362] Iteration 20759, Testing net (#0)
I0616 09:40:43.958425 5248 net.cpp:723] Ignoring source layer train-data
I0616 09:40:43.958427 5248 net.cpp:723] Ignoring source layer train-label
I0616 09:40:43.958429 5248 net.cpp:723] Ignoring source layer train-transform
Traceback (most recent call last):
File "/usr/lib/python2.7/dist-packages/caffe/layers/detectnet/clustering.py", line 133, in forward
bbox = cluster(self, data0, bottom[1].data)
File "/usr/lib/python2.7/dist-packages/caffe/layers/detectnet/clustering.py", line 232, in cluster
boxes[i, 0:r, 0:c] = boxes_cur_image
ValueError: could not broadcast input array from shape (51,5) into shape (50,5)

Can anyone help me to solve this problem?

**Comment by ontheway16** [comment]
Yes. :)

Actually I have experienced this problem for a long time and my solution was defining necessary paths like DIGITS_ROOT and CAFFE_ROOT. Cannot remember now if there were other paths to define, but try these two first.

**Comment by caleale90** [comment]
How did you set these two variables?

**Comment by ontheway16** [comment]
see here:
[#1440](https://github.com/NVIDIA/DIGITS/issues/1440#issuecomment-278211506)
