### ISSUE TITLE
TypeError when exploring classification DB

### ISSUE THREAD

**Issue by groundflyer** [NVIDIA/DIGITS#1689]
Exploring Image Classification DB and trying to filter items by class I get an error:
```python
TypeError

unsupported operand type(s) for -: 'dict' and 'int'

Traceback (most recent call last):
  File "/home/roman/.local/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/roman/.local/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/work/Soft/DIGITS/digits/webapp.py", line 81, in decorated
    return f(*args, **kwargs)
  File "/work/Soft/DIGITS/digits/dataset/images/classification/views.py", line 397, in explore
    max_page = min((total_entries - 1) / size, page + 5)
TypeError: unsupported operand type(s) for -: 'dict' and 'int'
```

**Comment by IvyGongoogle** [comment]
I got the same error.

**Comment by niaoyu** [comment]
I meet the same error, could anyone help?

**Comment by piotrkochan** [comment]
same here

**Comment by ividal** [comment]
Same here: Digits 6, used from within docker container (nvidia/digits:latest, SHA c2faf5).
Created DB succesfully with Digits; error occurred while filtering by label.

**Comment by juanluisrosaramos** [comment]
I got the same error.

**Comment by Aminullah6264** [comment]
I have the same problem
