### ISSUE TITLE
Create classification datasets occurred erros. 

### ISSUE THREAD

**Issue by Seakia** [NVIDIA/DIGITS#1721]
Hi, I recently occurred one problem about creating datasets.

Log as following:
>2017-07-11 17:49:02 [20170711-174900-746e] [INFO ] Parse Folder (train/val) task started.
2017-07-11 17:49:02 [20170711-174900-746e] [INFO ] Task subprocess args: "/usr/bin/python2 /home/ws/digits/digits/tools/parse_folder.py /home/ws/deep_learning/dual/Flow4/integrate/tmp/train /home/ws/digits/digits/jobs/20170711-174900-746e/labels.txt --min=2 --train_file=/home/ws/digits/digits/jobs/20170711-174900-746e/train.txt --val_file=/home/ws/digits/digits/jobs/20170711-174900-746e/val.txt --percent_val=25.0"
2017-07-11 17:49:03 [20170711-174900-746e] [INFO ] Parse Folder (train/val) task completed.
2017-07-11 17:49:03 [20170711-174900-746e] [INFO ] Create DB (train) task started.
2017-07-11 17:49:03 [20170711-174900-746e] [INFO ] Task subprocess args: "/usr/bin/python2 /home/ws/digits/digits/tools/create_db.py /home/ws/digits/digits/jobs/20170711-174900-746e/train.txt /home/ws/digits/digits/jobs/20170711-174900-746e/train_db 480 270 --backend=lmdb --channels=1 --resize_mode=squash --mean_file=/home/ws/digits/digits/jobs/20170711-174900-746e/mean.binaryproto --mean_file=/home/ws/digits/digits/jobs/20170711-174900-746e/mean.jpg --shuffle"
2017-07-11 17:49:03 [20170711-174900-746e] [INFO ] Create DB (val) task started.
2017-07-11 17:49:03 [20170711-174900-746e] [INFO ] Task subprocess args: "/usr/bin/python2 /home/ws/digits/digits/tools/create_db.py /home/ws/digits/digits/jobs/20170711-174900-746e/val.txt /home/ws/digits/digits/jobs/20170711-174900-746e/val_db 480 270 --backend=lmdb --channels=1 --resize_mode=squash --shuffle"
2017-07-11 17:49:06 [20170711-174900-746e] [ERROR] Create DB (val): LoadError: no images loaded from input file
2017-07-11 17:49:06 [20170711-174900-746e] [WARNING] Create DB (val) unrecognized output: Traceback (most recent call last):
2017-07-11 17:49:06 [20170711-174900-746e] [WARNING] Create DB (val) unrecognized output: File "/home/ws/digits/digits/tools/create_db.py", line 792, in <module>
2017-07-11 17:49:06 [20170711-174900-746e] [WARNING] Create DB (val) unrecognized output: hdf5_dset_limit=args['hdf5_dset_limit'],
2017-07-11 17:49:06 [20170711-174900-746e] [WARNING] Create DB (val) unrecognized output: File "/home/ws/digits/digits/tools/create_db.py", line 294, in create_db
2017-07-11 17:49:06 [20170711-174900-746e] [WARNING] Create DB (val) unrecognized output: mean_files, **kwargs)
2017-07-11 17:49:06 [20170711-174900-746e] [WARNING] Create DB (val) unrecognized output: File "/home/ws/digits/digits/tools/create_db.py", line 371, in _create_lmdb
2017-07-11 17:49:06 [20170711-174900-746e] [WARNING] Create DB (val) unrecognized output: raise LoadError('no images loaded from input file')
2017-07-11 17:49:06 [20170711-174900-746e] [WARNING] Create DB (val) unrecognized output: __main__.LoadError: no images loaded from input file
2017-07-11 17:49:06 [20170711-174900-746e] [ERROR] Create DB (val) task failed with error code 1
2017-07-11 17:49:08 [20170711-174900-746e] [ERROR] Create DB (train): LoadError: no images loaded from input file
2017-07-11 17:49:08 [20170711-174900-746e] [WARNING] Create DB (train) unrecognized output: Traceback (most recent call last):
2017-07-11 17:49:08 [20170711-174900-746e] [WARNING] Create DB (train) unrecognized output: File "/home/ws/digits/digits/tools/create_db.py", line 792, in <module>
2017-07-11 17:49:08 [20170711-174900-746e] [WARNING] Create DB (train) unrecognized output: hdf5_dset_limit=args['hdf5_dset_limit'],
2017-07-11 17:49:08 [20170711-174900-746e] [WARNING] Create DB (train) unrecognized output: File "/home/ws/digits/digits/tools/create_db.py", line 294, in create_db
2017-07-11 17:49:08 [20170711-174900-746e] [WARNING] Create DB (train) unrecognized output: mean_files, **kwargs)
2017-07-11 17:49:08 [20170711-174900-746e] [WARNING] Create DB (train) unrecognized output: File "/home/ws/digits/digits/tools/create_db.py", line 371, in _create_lmdb
2017-07-11 17:49:08 [20170711-174900-746e] [WARNING] Create DB (train) unrecognized output: raise LoadError('no images loaded from input file')
2017-07-11 17:49:08 [20170711-174900-746e] [WARNING] Create DB (train) unrecognized output: __main__.LoadError: no images loaded from input file
2017-07-11 17:49:08 [20170711-174900-746e] [ERROR] Create DB (train) task failed with error code 1

The directory content is as following:

![screenshot from 2017-07-11 18 20 44](https://user-images.githubusercontent.com/9548796/28064044-cf93c914-6665-11e7-8d31-5d3493b9c64d.png)

What is the problem? 
Thank you.

**Comment by linuzlover** [comment]
Hi, 

it seems to me that the directory structure is not following the required one. 
The error is the following:

> 2017-07-11 17:49:06 [20170711-174900-746e] [ERROR] Create DB (val): LoadError: no images loaded from input file

The application can not find the images. Did you see the examples tutorials [here](https://github.com/dusty-nv/jetson-inference#locating-object-coordinates-using-detectnet) and [here](https://github.com/NVIDIA/DIGITS/blob/master/examples/object-detection/README.md#dataset-creation)?

**Comment by Seakia** [comment]
Thanks for your help. But the problem is the version of pillow. The version which is required in the requrements.txt is not correct for me and the command i used to install Pillow is "sudo pip install Pillow". The version is newer than the version described in the requirements.txt
