### ISSUE TITLE
Splitting the Kitti Dataset using prepare_kitti_data.py

### ISSUE THREAD

**Issue by Harshitha94** [NVIDIA/DIGITS#1733]
When using the given script 'prepare_kitti_data.py' to split the dataset into training and validation images, I am getting the following error...

Extracting zipfiles ...
Unzipping data_object_label_2.zip ...
Unzipping data_object_image_2.zip ...
Unzipping devkit_object.zip ...
Calculating image to video mapping ...
Traceback (most recent call last):
  File "prepare_kitti_data.py", line 182, in <module>
    os.path.join(args.output_dir, 'raw'),
  File "prepare_kitti_data.py", line 39, in get_image_to_video_mapping
    with open(os.path.join(devkit_dir, 'mapping', 'train_mapping.txt'), 'r') as infile:
IOError: [Errno 2] No such file or directory: 'kitti-data/raw/mapping/train_mapping.txt'

Line 182 in the script is:

os.path.join(args.output_dir, 'raw')

Changing this line to

os.path.join(args.output_dir, 'raw', 'devkit')

solved this issue.

Just letting you know :)

**Comment by TheMikeyR** [comment]
I've encountered this issue when I stopped the script (before completion) and then executed it again, I fixed the issue by removing the folder kitti-data and then executed the script.
