### ISSUE TITLE
Error on building Digits

### ISSUE THREAD

**Issue by philipperemy** [NVIDIA/DIGITS#1743]
I'm having this error when building Digits. Caffe installation went fine.

Can you guys help?

Thanks! 

```
  ___ ___ ___ ___ _____ ___
 |   \_ _/ __|_ _|_   _/ __|
 | |) | | (_ || |  | | \__ \
 |___/___\___|___| |_| |___/ 6.0.0-rc.1

Tensorflow support disabled.
RuntimeError: module compiled against API version 0xb but this version of numpy is 0xa
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/premy/digits/digits/__main__.py", line 70, in <module>
    main()
  File "/home/premy/digits/digits/__main__.py", line 55, in main
    import digits.webapp
  File "digits/webapp.py", line 47, in <module>
    import digits.views  # noqa
  File "/home/premy/.local/lib/python2.7/site-packages/gevent/builtins.py", line 93, in __import__
    result = _import(*args, **kwargs)
  File "digits/views.py", line 18, in <module>
    from digits import dataset, extensions, model, utils, pretrained_model
  File "/home/premy/.local/lib/python2.7/site-packages/gevent/builtins.py", line 93, in __import__
    result = _import(*args, **kwargs)
  File "digits/extensions/__init__.py", line 5, in <module>
    from .view import *  # noqa
  File "/home/premy/.local/lib/python2.7/site-packages/gevent/builtins.py", line 93, in __import__
    result = _import(*args, **kwargs)
  File "digits/extensions/view/__init__.py", line 9, in <module>
    from . import imageSegmentation
  File "/home/premy/.local/lib/python2.7/site-packages/gevent/builtins.py", line 93, in __import__
    result = _import(*args, **kwargs)
  File "digits/extensions/view/imageSegmentation/__init__.py", line 4, in <module>
    from .view import Visualization
  File "/home/premy/.local/lib/python2.7/site-packages/gevent/builtins.py", line 93, in __import__
    result = _import(*args, **kwargs)
  File "digits/extensions/view/imageSegmentation/view.py", line 11, in <module>
    import skfmm
  File "/home/premy/.local/lib/python2.7/site-packages/gevent/builtins.py", line 93, in __import__
    result = _import(*args, **kwargs)
  File "/home/premy/.local/lib/python2.7/site-packages/skfmm/__init__.py", line 51, in <module>
    from .pfmm import distance, travel_time, extension_velocities
  File "/home/premy/.local/lib/python2.7/site-packages/gevent/builtins.py", line 93, in __import__
    result = _import(*args, **kwargs)
  File "/home/premy/.local/lib/python2.7/site-packages/skfmm/pfmm.py", line 4, in <module>
    from .cfmm import cFastMarcher
  File "/home/premy/.local/lib/python2.7/site-packages/gevent/builtins.py", line 93, in __import__
    result = _import(*args, **kwargs)
ImportError: numpy.core.multiarray failed to import
```

**Comment by ethantang95** [comment]
What is the version of your numpy? The current build uses numpy 1.13. It looks like your version of numpy might be outdated.

**Comment by philipperemy** [comment]
I've installed the numpy version inside the requirements.txt file of DIGITS.

It was 1.11.0.

**Comment by ethantang95** [comment]
check what version is numpy with pip show numpy. If it's different, then pip uninstall numpy and pip uninstall numpy==1.11.0

**Comment by philipperemy** [comment]
Ok it works!!

We should definitely update the numpy version of the requirements.txt:

https://github.com/NVIDIA/DIGITS/blob/master/requirements.txt

Here was the compilation script I used:

```
rm -rf digits caffe

# example location - can be customized

git clone https://github.com/NVIDIA/caffe.git
pip install -r caffe/python/requirements.txt --user
pip install numpy==1.13.0 --upgrade --user

# example location - can be customized
git clone https://github.com/NVIDIA/DIGITS.git digits
pip install -r digits/requirements.txt --user
pip install numpy==1.13.0 --upgrade --user

cd caffe
mkdir build
cd build
cmake ..
make --jobs=4

cd

cd digits
./digits-devserver
```

@ethantang95 thanks for the great support!
