### ISSUE TITLE
Digits issue with CAFFE_ROOT variable

### ISSUE THREAD

**Issue by gunju** [NVIDIA/DIGITS#1761]
I am getting following issue while using digits 5.0. My caffe installation is at /home/ubuntu/caffe.

```
"/home/ubuntu/caffe" from CAFFE_ROOT does not point to a valid installation of Caffe.
Use the envvar CAFFE_ROOT to indicate a valid installation.
Traceback (most recent call last):
  File "/home/ubuntu/anaconda2/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/home/ubuntu/anaconda2/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/ubuntu/download/DIGITS-digits-5.0/digits/__main__.py", line 66, in <module>
    main()
  File "/home/ubuntu/download/DIGITS-digits-5.0/digits/__main__.py", line 49, in main
    import digits.config
  File "digits/config/__init__.py", line 7, in <module>
    from . import caffe
  File "digits/config/caffe.py", line 225, in <module>
    executable, version, flavor = load_from_envvar('CAFFE_ROOT')
  File "digits/config/caffe.py", line 34, in load_from_envvar
    import_pycaffe(python_dir)
  File "digits/config/caffe.py", line 123, in import_pycaffe
    import caffe
  File "/home/ubuntu/caffe/python/caffe/__init__.py", line 1, in <module>
    from .pycaffe import Net, SGDSolver, NesterovSolver, AdaGradSolver, RMSPropSolver, AdaDeltaSolver, AdamSolver
  File "/home/ubuntu/caffe/python/caffe/pycaffe.py", line 15, in <module>
    import caffe.io
  File "/home/ubuntu/caffe/python/caffe/io.py", line 8, in <module>
    from caffe.proto import caffe_pb2
  File "/home/ubuntu/caffe/python/caffe/proto/caffe_pb2.py", line 23, in <module>
    0\x64\x65t_fg_threshold\x18\x36 \x01(\x02:\x03\x30.5\x12\x1d\n\x10\x64\x65t_bg_threshold\x18\x37 \x01(\x02:\x03\x30.5\x12\x1d\n\x0f\x64\x65t_fg_fraction\x18\x38 \x01(\x02:\x04\x30.25\x12\x1a\n\x0f\x64\x65t_context_pad\x18: \x01(\r:\x01\x30\x12\x1b\n\rdet_crop_mode\x18; \x01(\t:\x04warp\x12\x12\n\x07new_num\x18< \x01(\x05:\x01\x30\x12\x17\n\x0cnew_channels\x18= \x01(\x05:\x01\x30\x12\x15\n\nnew_height\x18> \x01(\x05:\x01\x30\x12\x14\n\tnew_width\x18? \x01(\x05:\x01\x30\x12\x1d\n\x0eshuffle_images\x18@ \x01(\x08:\x05\x66\x61lse\x12\x15\n\nconcat_dim\x18\x41 \x01(\r:\x01\x31\x12\x36\n\x11hdf5_output_param\x18\xe9\x07 \x01(\x0b\x32\x1a.caffe.HDF5OutputParameter\".\n\nPoolMethod\x12\x07\n\x03MAX\x10\x00\x12\x07\n\x03\x41VE\x10\x01\x12\x0e\n\nSTOCHASTIC\x10\x02\"W\n\x0ePReLUParameter\x12&\n\x06\x66iller\x18\x01 \x01(\x0b\x32\x16.caffe.FillerParameter\x12\x1d\n\x0e\x63hannel_shared\x18\x02 \x01(\x08:\x05\x66\x61lse*\x1c\n\x05Phase\x12\t\n\x05TRAIN\x10\x00\x12\x08\n\x04TEST\x10\x01')
TypeError: __init__() got an unexpected keyword argument 'syntax'

```
`./digits-devserver` is working for Digits 4.0

Please help me to solve this issue.

**Comment by ethantang95** [comment]
Possibly a problem with protobuf. Try rebuilding protobuf from source. DIGITS currently targets PB 3.2
