### ISSUE TITLE
import error when i use dice-metric in medical example

### ISSUE THREAD

**Issue by doubridge** [NVIDIA/DIGITS#1772]
I0810 15:15:31.895124 27431 layer_factory.hpp:77] Creating layer dice
Traceback (most recent call last):
File "/home/wsq/work/digits/DIGITS/digits/jobs/20170810-151528-3299/digits_python_layers.py", line 12, in <module>
import caffe
File "/home/wsq/work/digits/caffe/python/caffe/__init__.py", line 1, in <module>
from .pycaffe import Net, SGDSolver, NesterovSolver, AdaGradSolver, RMSPropSolver, AdaDeltaSolver, AdamSolver
File "/home/wsq/work/digits/caffe/python/caffe/pycaffe.py", line 13, in <module>
from ._caffe import Net, SGDSolver, NesterovSolver, AdaGradSolver, \
ImportError: /home/wsq/work/digits/caffe/python/caffe/_caffe.so: undefined symbol: _ZN5caffe34_PythonParameter_default_instance_E

**Comment by doubridge** [comment]
@lukeyeager can you help me? thank you.

**Comment by lukeyeager** [comment]
That's not much to go on. I'd try clearing out your Caffe build and re-building it.

**Comment by doubridge** [comment]
@lukeyeager hi,i rebuild the caffe,while i got the same error.
my caffe and digits version is:
DIGITS version:
6.0.0-rc.1
Caffe version:
0.15.13
Caffe flavor:
NVIDIA
 thank you.

**Comment by lukeyeager** [comment]
Ok, can you tell me your versions of:
* Ubuntu
* Python
* numpy

Read through these instructions carefully: https://github.com/NVIDIA/DIGITS/blob/master/docs/BuildDigits.md

**Comment by doubridge** [comment]
@lukeyeager 
Ubuntu 16.04
Python 2.7.12
numpy 1.11.0

**Comment by PennySHE** [comment]
@doubridge 
is there any update on this issue? how you got it fixed? i found the exactly same error prompt when i import caffe. your experience might help me get through.
