### ISSUE TITLE
Loading pretrained tensorflow model

### ISSUE THREAD

**Issue by AWilcke** [NVIDIA/DIGITS#1791]
Using DIGITS-6.0-rc, with the new tensorflow support, I am trying to port nets from [TF-slim](https://github.com/tensorflow/models/tree/master/slim) into DIGITS. I have implemented InceptionV1, and it trains from scratch in DIGITS, however when trying to load a pretrained model I get the following error.

```
2017-08-22 11:22:00 [INFO] Train batch size is 16 and validation batch size is 16
2017-08-22 11:22:00 [INFO] Training epochs to be completed for each validation : 1
2017-08-22 11:22:00 [INFO] Training epochs to be completed before taking a snapshot : 1.0
2017-08-22 11:22:00 [INFO] Model weights will be saved as snapshot_<EPOCH>_Model.ckpt
2017-08-22 11:22:00 [INFO] Loading mean tensor from /jobs/20170613-080203-895a/mean.binaryproto file
2017-08-22 11:22:00 [INFO] Loading label definitions from /jobs/20170613-080203-895a/labels.txt file
2017-08-22 11:22:00 [INFO] Found 69 classes
2017-08-22 11:22:00 [INFO] Found 4189 images in db /jobs/20170613-080203-895a/train_db
2017-08-22 11:22:00.593158: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.
2017-08-22 11:22:00.593188: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
2017-08-22 11:22:00.593201: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
2017-08-22 11:22:00.593213: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX2 instructions, but these are available on your machine and could speed up CPU computations.
2017-08-22 11:22:00.593226: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use FMA instructions, but these are available on your machine and could speed up CPU computations.
2017-08-22 11:22:00.836922: I tensorflow/core/common_runtime/gpu/gpu_device.cc:940] Found device 0 with properties:
name: GeForce GTX 970
major: 5 minor: 2 memoryClockRate (GHz) 1.253
pciBusID 0000:04:00.0
Total memory: 3.94GiB
Free memory: 3.88GiB
2017-08-22 11:22:00.836979: I tensorflow/core/common_runtime/gpu/gpu_device.cc:961] DMA: 0
2017-08-22 11:22:00.836997: I tensorflow/core/common_runtime/gpu/gpu_device.cc:971] 0:   Y
2017-08-22 11:22:00.837029: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1030] Creating TensorFlow device (/gpu:0) -> (device: 0, name: GeForce GTX 970, pci bus id: 0000:04:00.0)
2017-08-22 11:22:02 [INFO] Optimizer:sgd
2017-08-22 11:22:03 [INFO] Found 1429 images in db /jobs/20170613-080203-895a/val_db
2017-08-22 11:22:03.471877: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1030] Creating TensorFlow device (/gpu:0) -> (device: 0, name: GeForce GTX 970, pci bus id: 0000:04:00.0)
2017-08-22 11:22:03.973740: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1030] Creating TensorFlow device (/gpu:0) -> (device: 0, name: GeForce GTX 970, pci bus id: 0000:04:00.0)
2017-08-22 11:22:04 [INFO] Loading weights from pretrained model - /nfs/home/arthur/models/inception_v1.ckpt
2017-08-22 11:22:05 [INFO] NOT restoring global_step -> global_step:0
2017-08-22 11:22:05 [INFO] Restoring 0 variable ops.
Traceback (most recent call last):
File "/usr/local/lib/python2.7/dist-packages/digits/tools/tensorflow/main.py", line 707, in <module>
tf.app.run()
File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 48, in run
_sys.exit(main(_sys.argv[:1] + flags_passthrough))
File "/usr/local/lib/python2.7/dist-packages/digits/tools/tensorflow/main.py", line 544, in main
load_snapshot(sess, FLAGS.weights, tf.get_collection(tf.GraphKeys.GLOBAL_VARIABLES))
File "/usr/local/lib/python2.7/dist-packages/digits/tools/tensorflow/main.py", line 264, in load_snapshot
tf.train.Saver(vars_restore, max_to_keep=0, sharded=FLAGS.serving_export).restore(sess, weight_path)
File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 1139, in __init__
self.build()
File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 1161, in build
raise ValueError("No variables to save")
ValueError: No variables to save
```

Would it be possible to add support for restoring from non-DIGITS checkpoints?

**Comment by ethantang95** [comment]
Tensorflow is a bit finnicky like that in a way that the weights are saved not in 1 but in 3 files. The latest commit on the master branch now takes in account of that and when you upload, it will process all the .ckpt files (data, index, meta). But by reference, it will still refer to .ckpt. Basically when you are loading a pre trained weight, ensure that the extension is just .ckpt and the backend will search for all those 3 files.

**Comment by ividal** [comment]
Does this still stand for the released v6? I see only options to upload Torch or Caffe pre-trained models.

**Comment by ethantang95** [comment]
You should be able to upload Tensorflow pre-trained models now in V6

**Comment by ividal** [comment]
If it's meant to be alongside the options for Torch and Caffe, it doesn't seem to be there. Attached is a screenshot of my options under "Pretrained models" > "Upload...", for Digits v6.0.0 (installed from the docker hub image: nvidia/digits:latest, which currently points to :6.0.0). 

I'd expect a third "Tensorflow" option to enable loading a checkpoint. Is this incorrect? (And if so, how should one load the tensorflow pre-trained model?)

![digits60_snapshot_pretrained](https://user-images.githubusercontent.com/2930596/31555089-0557ade4-b040-11e7-98ef-9fd4daf5ca73.png)

Thanks for your help!

**Comment by michaeldong** [comment]
Seem issue.   Wonder Digits when to support pre-trained tensorflow model?

**Comment by Dexter123193** [comment]
Hi. I am uploading a pretrained network on DIGITS . 
![image](https://user-images.githubusercontent.com/30825115/39965393-49ab34c6-56b1-11e8-8d38-8feddcf82aee.png)
And I am getting this error
![image](https://user-images.githubusercontent.com/30825115/39965399-5fe7204c-56b1-11e8-8c49-7c1b09c9ddb8.png)

Can I get some help on this

**Comment by DFreeMind** [comment]
> Hi. I am uploading a pretrained network on DIGITS .
> ![image](https://user-images.githubusercontent.com/30825115/39965393-49ab34c6-56b1-11e8-8d38-8feddcf82aee.png)
> And I am getting this error
> ![image](https://user-images.githubusercontent.com/30825115/39965399-5fe7204c-56b1-11e8-8c49-7c1b09c9ddb8.png)
> 
> Can I get some help on this

you should add a lables.txt files. the file can be empty, but must have. this can solve you problem

**Comment by agoila** [comment]
> If it's meant to be alongside the options for Torch and Caffe, it doesn't seem to be there. Here's a screenshot of my options under "Pretrained models" > "Upload...", for Digits v6.0.0 (installed from the docker hub image: nvidia/digits:latest, which currently points to :6.0.0).
> 
> ![digits60_snapshot_pretrained](https://user-images.githubusercontent.com/2930596/31555089-0557ade4-b040-11e7-98ef-9fd4daf5ca73.png)
> 
> I'd expect a third "Tensorflow" option to enable loading a checkpoint. Is this incorrect? (And if so, how should one load the tensorflow pre-trained model?)
> 
> Thanks for your help!

Any updates to this? I am seeing the same two options when trying to manually upload a pretrained Tensorflow model.
