### ISSUE TITLE
Infer Model unrecognized output: ValueError: range parameter must be finite.

### ISSUE THREAD

**Issue by IvyGongoogle** [NVIDIA/DIGITS#1828]
hello, after I create my model, I want to classify one image. If I use `Show visualizations and statistics`, it will shows error:

```
2017-09-18 17:19:17 [20170918-171913-e9d7] [WARNING] Infer Model unrecognized output: 2017-09-18 17:19:17 [ERROR] ValueError: range parameter must be finite.
2017-09-18 17:19:17 [20170918-171913-e9d7] [WARNING] Infer Model unrecognized output: Traceback (most recent call last):
2017-09-18 17:19:17 [20170918-171913-e9d7] [WARNING] Infer Model unrecognized output: File "/home/xxx/DIGITS/digits/tools/inference.py", line 293, in <module>
2017-09-18 17:19:17 [20170918-171913-e9d7] [WARNING] Infer Model unrecognized output: args['resize']
2017-09-18 17:19:17 [20170918-171913-e9d7] [WARNING] Infer Model unrecognized output: File "/home/xxx/DIGITS/digits/tools/inference.py", line 159, in infer
2017-09-18 17:19:17 [20170918-171913-e9d7] [WARNING] Infer Model unrecognized output: resize=resize)
2017-09-18 17:19:17 [20170918-171913-e9d7] [WARNING] Infer Model unrecognized output: File "/home/xxx/DIGITS/digits/model/tasks/caffe_train.py", line 1251, in infer_one
2017-09-18 17:19:17 [20170918-171913-e9d7] [WARNING] Infer Model unrecognized output: resize=resize
2017-09-18 17:19:17 [20170918-171913-e9d7] [WARNING] Infer Model unrecognized output: File "/home/xxx/DIGITS/digits/model/tasks/caffe_train.py", line 1298, in infer_one_image
2017-09-18 17:19:17 [20170918-171913-e9d7] [WARNING] Infer Model unrecognized output: visualizations = self.get_layer_visualizations(net, layers)
2017-09-18 17:19:17 [20170918-171913-e9d7] [WARNING] Infer Model unrecognized output: File "/home/xxx/DIGITS/digits/model/tasks/caffe_train.py", line 1338, in get_layer_visualizations
2017-09-18 17:19:17 [20170918-171913-e9d7] [WARNING] Infer Model unrecognized output: mean, std, hist = self.get_layer_statistics(data)
2017-09-18 17:19:17 [20170918-171913-e9d7] [WARNING] Infer Model unrecognized output: File "/home/xxx/DIGITS/digits/model/tasks/caffe_train.py", line 1408, in get_layer_statistics
2017-09-18 17:19:17 [20170918-171913-e9d7] [WARNING] Infer Model unrecognized output: y, x = np.histogram(data, bins=20)
2017-09-18 17:19:17 [20170918-171913-e9d7] [WARNING] Infer Model unrecognized output: File "/home/ztgong/.virtualenvs/zhuge/lib/python2.7/site-packages/numpy/lib/function_base.py", line 505, in histogram
2017-09-18 17:19:17 [20170918-171913-e9d7] [WARNING] Infer Model unrecognized output: 'range parameter must be finite.')
2017-09-18 17:19:17 [20170918-171913-e9d7] [WARNING] Infer Model unrecognized output: ValueError: range parameter must be finite.
2017-09-18 17:19:17 [20170918-171913-e9d7] [ERROR] Infer Model task failed with error code 1
2017-09-18 17:19:17 [20170918-171913-e9d7] [INFO ] Job deleted.
```

how to solve it?

**Comment by mrgloom** [comment]
Same error

```
2017-11-04 22:42:54 [ERROR] ValueError: range parameter must be finite.
Traceback (most recent call last):
File "/media/myuser/B/PROJECTS/GITHUB/dog-breed-classification/DIGITS/digits/tools/inference.py", line 293, in <module>
args['resize']
File "/media/myuser/B/PROJECTS/GITHUB/dog-breed-classification/DIGITS/digits/tools/inference.py", line 159, in infer
resize=resize)
File "/media/myuser/B/PROJECTS/GITHUB/dog-breed-classification/DIGITS/digits/model/tasks/caffe_train.py", line 1251, in infer_one
resize=resize
File "/media/myuser/B/PROJECTS/GITHUB/dog-breed-classification/DIGITS/digits/model/tasks/caffe_train.py", line 1298, in infer_one_image
visualizations = self.get_layer_visualizations(net, layers)
File "/media/myuser/B/PROJECTS/GITHUB/dog-breed-classification/DIGITS/digits/model/tasks/caffe_train.py", line 1338, in get_layer_visualizations
mean, std, hist = self.get_layer_statistics(data)
File "/media/myuser/B/PROJECTS/GITHUB/dog-breed-classification/DIGITS/digits/model/tasks/caffe_train.py", line 1408, in get_layer_statistics
y, x = np.histogram(data, bins=20)
File "/usr/local/lib/python2.7/dist-packages/numpy/lib/function_base.py", line 670, in histogram
'range parameter must be finite.')
```

**Comment by durka** [comment]
Why was this closed? It seems to happen when the predictions are NaN. This shouldn't crash the job.
