### ISSUE TITLE
classify script failure

### ISSUE THREAD

**Issue by danbuckler** [NVIDIA/DIGITS#184]
When I try to use the classify script it fails as follows:
```
root@ubuntu4caffe:~/NVIDIA-caffe-0.12.0/caffe/DIGITS/examples/classification# ./use_archive.py /root/NVIDIA-caffe-0.12.0/caffe/DIGITS/digits/jobs/20150727-143817-5fa8.tar.gz /root/NVIDIA-caffe-0.12.0/caffe/DIGITS/data/mnist/test/8/08787.png
Traceback (most recent call last):
  File "./use_archive.py", line 15, in <module>
    from example import classify
  File "/root/NVIDIA-caffe-0.12.0/caffe/DIGITS/examples/classification/example.py", line 20, in <module>
    import caffe
  File "/root/caffe-master/install/python/caffe/__init__.py", line 1, in <module>
    from .pycaffe import Net, SGDSolver
  File "/root/caffe-master/install/python/caffe/pycaffe.py", line 14, in <module>
    import caffe.io
  File "/root/caffe-master/install/python/caffe/io.py", line 8, in <module>
    from caffe.proto import caffe_pb2
  File "/root/caffe-master/install/python/caffe/proto/caffe_pb2.py", line 23, in <module>
    g_fraction\x18\x38 \x01(\x02:\x04\x30.25\x12\x1a\n\x0f\x64\x65t_context_pad\x18: \x01(\r:\x01\x30\x12\x1b\n\rdet_crop_mode\x18; \x01(\t:\x04warp\x12\x12\n\x07new_num\x18< \x01(\x05:\x01\x30\x12\x17\n\x0cnew_channels\x18= \x01(\x05:\x01\x30\x12\x15\n\nnew_height\x18> \x01(\x05:\x01\x30\x12\x14\n\tnew_width\x18? \x01(\x05:\x01\x30\x12\x1d\n\x0eshuffle_images\x18@ \x01(\x08:\x05\x66\x61lse\x12\x15\n\nconcat_dim\x18\x41 \x01(\r:\x01\x31\x12\x36\n\x11hdf5_output_param\x18\xe9\x07 \x01(\x0b\x32\x1a.caffe.HDF5OutputParameter\".\n\nPoolMethod\x12\x07\n\x03MAX\x10\x00\x12\x07\n\x03\x41VE\x10\x01\x12\x0e\n\nSTOCHASTIC\x10\x02\"W\n\x0ePReLUParameter\x12&\n\x06\x66iller\x18\x01 \x01(\x0b\x32\x16.caffe.FillerParameter\x12\x1d\n\x0e\x63hannel_shared\x18\x02 \x01(\x08:\x05\x66\x61lse*\x1c\n\x05Phase\x12\t\n\x05TRAIN\x10\x00\x12\x08\n\x04TEST\x10\x01')
TypeError: __init__() got an unexpected keyword argument 'syntax'
root@ubuntu4caffe:~/NVIDIA-caffe-0.12.0/caffe/DIGITS/examples/classification#
```

**Comment by lukeyeager** [comment]
That's the same problem you were having in https://github.com/NVIDIA/DIGITS/issues/178 and at https://github.com/BVLC/caffe/issues/2092#issuecomment-124581366.
