### ISSUE TITLE
Zero display during training segmentation

### ISSUE THREAD

**Issue by AdamKisgergely** [NVIDIA/DIGITS#1902]
Hi,

 I am facing an issue with digits 6.0. I have installed following the guide and when I trying to train my network i got an error at the start of the training procedure:
Receive error
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/engineio/socket.py", line 210, in _websocket_handler
    self.receive(pkt)
  File "/usr/local/lib/python2.7/dist-packages/engineio/socket.py", line 54, in receive
    self.send(packet.Packet(packet.PONG, pkt.data))
  File "/usr/local/lib/python2.7/dist-packages/engineio/socket.py", line 68, in send
    raise IOError('Socket is closed')
IOError: Socket is closed
2017-12-02 11:48:55 [20171202-113846-88b4] [DEBUG] Training 1.22% complete.
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/gevent/pywsgi.py", line 884, in handle_one_response
    self.run_application()
  File "/usr/local/lib/python2.7/dist-packages/geventwebsocket/handler.py", line 88, in run_application
    return super(WebSocketHandler, self).run_application()
  File "/usr/lib/python2.7/dist-packages/gevent/pywsgi.py", line 870, in run_application
    self.result = self.application(self.environ, self.start_response)
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/flask_socketio/__init__.py", line 37, in __call__
    start_response)
  File "/usr/local/lib/python2.7/dist-packages/engineio/middleware.py", line 47, in __call__
    return self.engineio_app.handle_request(environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/socketio/server.py", line 360, in handle_request
    return self.eio.handle_request(environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/engineio/server.py", line 271, in handle_request
    socket = self._get_socket(sid)
  File "/usr/local/lib/python2.7/dist-packages/engineio/server.py", line 421, in _get_socket
    raise KeyError('Session is disconnected')
KeyError: 'Session is disconnected'
{'GATEWAY_INTERFACE': 'CGI/1.1',
 'HTTP_ACCEPT': '*/*',
 'HTTP_ACCEPT_ENCODING': 'gzip, deflate, br',
 'HTTP_ACCEPT_LANGUAGE': 'hu-HU,hu;q=0.9,en-US;q=0.8,en;q=0.7',
 'HTTP_CONNECTION': 'keep-alive',
 'HTTP_COOKIE': 'io=a4aceb0a5dfc4509a4d6f21a1e2abbb9; username=kadam',
 'HTTP_HOST': 'localhost:5000',
 'HTTP_REFERER': 'http://localhost:5000/models/20171202-113846-88b4',
 'HTTP_USER_AGENT': 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36',
 'PATH_INFO': '/socket.io/',
 'QUERY_STRING': 'EIO=3&transport=polling&t=M0MrGpA&sid=a2bfae19c5c949369f54b56604c8b232',
 'REMOTE_ADDR': '127.0.0.1',
 'REMOTE_PORT': '44498',
 'REQUEST_METHOD': 'GET',
 'SCRIPT_NAME': '',
 'SERVER_NAME': 'sanyi',
 'SERVER_PORT': '5000',
 'SERVER_PROTOCOL': 'HTTP/1.1',
 'SERVER_SOFTWARE': 'gevent/1.1 Python/2.7',
 'flask.app': <Flask 'digits.webapp'>,
 'wsgi.errors': <open file '<stderr>', mode 'w' at 0x7fcadbb0e1e0>,
 'wsgi.input': <gevent.pywsgi.Input object at 0x7fca567c8668>,
 'wsgi.multiprocess': False,
 'wsgi.multithread': False,
 'wsgi.run_once': False,
 'wsgi.url_scheme': 'http',
 'wsgi.version': (1, 0)} failed with KeyError
But the training countinuous and every time digits try to display the following error coming:
Receive error
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/engineio/socket.py", line 210, in _websocket_handler
    self.receive(pkt)
  File "/usr/local/lib/python2.7/dist-packages/engineio/socket.py", line 54, in receive
    self.send(packet.Packet(packet.PONG, pkt.data))
  File "/usr/local/lib/python2.7/dist-packages/engineio/socket.py", line 68, in send
    raise IOError('Socket is closed')
IOError: Socket is closed
This dont disturb the training only bother me beacouse i cant see anything and even cant abort only by interrupting through the terminal.
Can sombody help me what am I doing wrong?

**Comment by maryamkamarun** [comment]
Pardon me for asking, but have you solved this issue? I'm facing the same problem with DIGITS 6.0.
