### ISSUE TITLE
Error with 'sudo pip install -r requirements.txt'

### ISSUE THREAD

**Issue by GustavZ** [NVIDIA/DIGITS#1931]
When i try to run `sudo pip install -r requirements.txt` after cloning the repo it gets stuck at pydot:

```
Collecting pydot<=1.0.29,>=1.0.28 (from -r requirements.txt (line 16))
  Downloading pydot-1.0.29.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-zhy2gehm/pydot/setup.py", line 6, in <module>
        import pydot
      File "/tmp/pip-build-zhy2gehm/pydot/pydot.py", line 31
        except Exception, e:
                        ^
    SyntaxError: invalid syntax
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-zhy2gehm/pydot/

```

i tried this workaround (https://github.com/NVIDIA/DIGITS/issues/1461) but it did not work for me...t pydot 1.2.4 installed on pip (for python 3.5) and pydot 1.0.29 for pip2 (python2.7).

Any Hints are highly appreciated!

i go

**Comment by LeitchP** [comment]
Same problem on Windows.

**Comment by LeitchP** [comment]
In fact - simply running this gets the error: pip install pydot==1.0.29

**Comment by adfayed** [comment]
Any solution @gustavz ?
