### ISSUE TITLE
Error on starting digits-devserver

### ISSUE THREAD

**Issue by dipsankarb** [NVIDIA/DIGITS#1932]
I am getting this error on starting the devserver. All other installations of dependencies have proceeded smoothly.

[dsb@localhost DIGITS]# ./digits-devserver 
  ___ ___ ___ ___ _____ ___
 |   \_ _/ __|_ _|_   _/ __|
 | |) | | (_ || |  | | \__ \
 |___/___\___|___| |_| |___/ 6.0.0

"/scratch/digits/deps/caffe/" from CAFFE_ROOT does not point to a valid installation of Caffe.
Use the envvar CAFFE_ROOT to indicate a valid installation.
Traceback (most recent call last):
  File "/usr/lib64/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib64/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/scratch/digits/DIGITS/digits/__main__.py", line 70, in <module>
    main()
  File "/scratch/digits/DIGITS/digits/__main__.py", line 53, in main
    import digits.config
  File "digits/config/__init__.py", line 7, in <module>
    from . import (  # noqa
  File "digits/config/caffe.py", line 226, in <module>
    executable, version, flavor = load_from_envvar('CAFFE_ROOT')
  File "digits/config/caffe.py", line 37, in load_from_envvar
    import_pycaffe(python_dir)
  File "digits/config/caffe.py", line 126, in import_pycaffe
    import caffe
  File "/scratch/digits/deps/caffe/python/caffe/__init__.py", line 1, in <module>
    from .pycaffe import Net, SGDSolver, NesterovSolver, AdaGradSolver, RMSPropSolver, AdaDeltaSolver, AdamSolver
  File "/scratch/digits/deps/caffe/python/caffe/pycaffe.py", line 15, in <module>
    import caffe.io
  File "/scratch/digits/deps/caffe/python/caffe/io.py", line 8, in <module>
    from caffe.proto import caffe_pb2
  File "/scratch/digits/deps/caffe/python/caffe/proto/caffe_pb2.py", line 919, in <module>
    options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\020\001')), file=DESCRIPTOR),
TypeError: __new__() got an unexpected keyword argument 'file'

**Comment by dipsankarb** [comment]
installed wrong protoc version
