### ISSUE TITLE
Error code 1

### ISSUE THREAD

**Issue by Wenyu1024** [NVIDIA/DIGITS#1943]
Hi, 
I am new to DIGITS and although I didn't encounter problem using example data, I kept getting ERROR CODE 1 when trainning on my custom data. I can successfully change my Kitti form label data and 1280*1024 data into LMDB. But when I started training I got this problem.

One thing I need to mention is previously I neglected setting "custom class" in data generation interface and training based on that data seems can finish the training, although due to the wrong label the network didn't learn anything.
And now the custom class blank are filled with dont'care, cell. Which is exactly the class I have in my label files. I used lowerclass in both label files and in filling the interface blank.

Any idea about how I can solve this?
Many thank!

**Comment by Wenyu1024** [comment]
P.S: infrmation from caffeoutput that might be useful:
libdc1394 error: Failed to initialize libdc1394
...
...
Traceback (most recent call last):
File "/usr/local/python/caffe/layers/detectnet/clustering.py", line 66, in forward
bbox = cluster(self, data0, bottom[1].data)
File "/usr/local/python/caffe/layers/detectnet/clustering.py", line 232, in cluster
boxes[i, 0:r, 0:c] = boxes_cur_image
ValueError: could not broadcast input array from shape (98,4) into shape (50,4)
