### ISSUE TITLE
Nvidia Digits -  Error code - 11 while running ./digits-test

### ISSUE THREAD

**Issue by chandanv2** [NVIDIA/DIGITS#1960]
The ./digits-test file when executed gives the following error.

Log File:
FAIL: digits.model.images.classification.test_views.TestCaffePythonLayer.test_python_layer
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/root/DIGITS-master/digits/model/images/classification/test_views.py", line 1340, in test_python_layer
    assert self.model_wait_completion(job_id) == 'Done', 'first job failed'
AssertionError: first job failed
-------------------- >> begin captured stdout << ---------------------
I0130 19:16:22.512895 10691 net.cpp:144] Setting up loss
I0130 19:16:22.512902 10691 net.cpp:151] Top shape: (1)
I0130 19:16:22.512907 10691 net.cpp:154]     with loss weight 1
I0130 19:16:22.512920 10691 net.cpp:159] Memory required for data: 72044
I0130 19:16:22.512925 10691 layer_factory.hpp:77] Creating layer py_test
*** Aborted at 1517319983 (unix time) try "date -d @1517319983" if you are using GNU date ***
PC: @     0x7faa1e361873 std::_Hashtable<>::clear()
*** SIGSEGV (@0x9) received by PID 10691 (TID 0x7faa65c05ac0) from PID 9; stack trace: ***
@     0x7faa63d034b0 (unknown)
@     0x7faa1e361873 std::_Hashtable<>::clear()
@     0x7faa1e353346 google::protobuf::DescriptorPool::FindFileByName()
@     0x7faa1e331ac8 google::protobuf::python::cdescriptor_pool::AddSerializedFile()
@     0x7faa6492e9f0 PyEval_EvalFrameEx
@     0x7faa64a6405c PyEval_EvalCodeEx
@     0x7faa649ba46d (unknown)
@     0x7faa6498d273 PyObject_Call
@     0x7faa649adb75 (unknown)
@     0x7faa64944173 (unknown)
@     0x7faa6498d273 PyObject_Call
@     0x7faa6492b35c PyEval_EvalFrameEx
@     0x7faa64a6405c PyEval_EvalCodeEx
@     0x7faa64925da9 PyEval_EvalCode
@     0x7faa649c7244 PyImport_ExecCodeModuleEx
@     0x7faa649c7c1f (unknown)
@     0x7faa649c9390 (unknown)
@     0x7faa649c9658 (unknown)
@     0x7faa649ca76b PyImport_ImportModuleLevel
@     0x7faa649348b8 (unknown)
@     0x7faa6498d273 PyObject_Call
@     0x7faa64a63487 PyEval_CallObjectWithKeywords
@     0x7faa649297e6 PyEval_EvalFrameEx
@     0x7faa64a6405c PyEval_EvalCodeEx
@     0x7faa64925da9 PyEval_EvalCode
@     0x7faa649c7244 PyImport_ExecCodeModuleEx
@     0x7faa649c7c1f (unknown)
@     0x7faa649c9390 (unknown)
@     0x7faa649c9658 (unknown)
@     0x7faa649ca76b PyImport_ImportModuleLevel
@     0x7faa649348b8 (unknown)
@     0x7faa6498d273 PyObject_Call

--------------------- >> end captured stdout << ----------------------
-------------------- >> begin captured logging << --------------------
socketio: INFO: emitting event "job update" to job_management [/jobs]
socketio: INFO: emitting event "job update" to 20180130-191622-cf0b [/jobs]
socketio: INFO: emitting event "job update" to job_management [/jobs]
digits.webapp: DEBUG: Network sanity check - train
digits.webapp: DEBUG: Network sanity check - val
digits.webapp: DEBUG: Network sanity check - deploy
digits.webapp: INFO: Train Caffe Model task started.
socketio: INFO: emitting event "task update" to 20180130-191622-cf0b [/jobs]
socketio: INFO: emitting event "job update" to 20180130-191622-cf0b [/jobs]
socketio: INFO: emitting event "job update" to job_management [/jobs]
digits.webapp: INFO: Task subprocess args: "/root/caffe-caffe-0.15/build/tools/caffe train --solver=/tmp/tmpjWxsw_/20180130-191622-cf0b/solver.prototxt"
socketio: INFO: emitting event "task update" to 20180130-191622-cf0b [/jobs]
digits.webapp: ERROR: Train Caffe Model task failed with error code -11
socketio: INFO: emitting event "task update" to 20180130-191622-cf0b [/jobs]
socketio: INFO: emitting event "job update" to 20180130-191622-cf0b [/jobs]
socketio: INFO: emitting event "job update" to job_management [/jobs]
socketio: INFO: emitting event "job update" to 20180130-191622-cf0b [/jobs]
socketio: INFO: emitting event "job update" to job_management [/jobs]
--------------------- >> end captured logging << ---------------------

**Comment by chandanv2** [comment]
Upgrading to a different version of Digits solved the issue!
