### ISSUE TITLE
DIGITS devserver problem

### ISSUE THREAD

**Issue by souhhano** [NVIDIA/DIGITS#1965]
Hello all,

I am trying to install the necessary for DIGITS, while trying to lunch the devserver I get this error : 

  ___ ___ ___ ___ _____ ___
 |   \_ _/ __|_ _|_   _/ __|
 | |) | | (_ || |  | | \__ \
 |___/___\___|___| |_| |___/ 6.1.0

"/home/souheil/caffe" from CAFFE_ROOT does not point to a valid installation of Caffe.
Use the envvar CAFFE_ROOT to indicate a valid installation.
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/souheil/Projets/DIGITS/digits/__main__.py", line 70, in <module>
    main()
  File "/home/souheil/Projets/DIGITS/digits/__main__.py", line 53, in main
    import digits.config
  File "digits/config/__init__.py", line 7, in <module>
    from . import (  # noqa
  File "digits/config/caffe.py", line 226, in <module>
    executable, version, flavor = load_from_envvar('CAFFE_ROOT')
  File "digits/config/caffe.py", line 37, in load_from_envvar
    import_pycaffe(python_dir)
  File "digits/config/caffe.py", line 126, in import_pycaffe
    import caffe
  File "/home/souheil/caffe/python/caffe/__init__.py", line 1, in <module>
    from .pycaffe import Net, SGDSolver, NesterovSolver, AdaGradSolver, RMSPropSolver, AdaDeltaSolver, AdamSolver
  File "/home/souheil/caffe/python/caffe/pycaffe.py", line 15, in <module>
    import caffe.io
  File "/home/souheil/caffe/python/caffe/io.py", line 8, in <module>
    from caffe.proto import caffe_pb2
  File "/home/souheil/caffe/python/caffe/proto/caffe_pb2.py", line 919, in <module>
    options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\020\001')), file=DESCRIPTOR),
TypeError: __new__() got an unexpected keyword argument 'file'

The problem seem to be coming from Caffe, however I tried reinstalling caffe with the script provided in the repository.

Any idea on what is going on ? 

I am running on an Ubuntu 16.04.

Thanks.

**Comment by JanySunny** [comment]
Hi, I have the same problem, have you solved it?

**Comment by JanySunny** [comment]
Hi, I have the same problem. Have you solved it?

**Comment by JanySunny** [comment]
Hi, I have the same problem. Have you solved it? How?

**Comment by souhhano** [comment]
Hi, no I didn't, I am still stuck on it. It is probably a version problem but I cannot figure out the library involved.
If you have any insight please let me know.

**Comment by JanySunny** [comment]
I try to set my own caffe (not the NVIDIA CAFFE)as CAFFE_ROOT and PYTHONPATH , and it works and "./digits-devserver" can output:
"Tensorflow support disabled.
2018-03-06 20:07:13 [INFO ] Loaded 0 jobs."
 However, I cannot open the link "http://localhost:5000/". It is so weird. If you have another better ideas, please let me know. Thanks~

**Comment by souhhano** [comment]
Found my problem, it was the define of CAFFE_ROOT too, it was linked to my install of Caffe where I did a "sudo make install" instead of a "make install", therefore the libraries were not accessible.

**Comment by clydebailey** [comment]
@souhhano can you elaborate on the solution? I have installed a caffe docker for the purpose of using digits
