### ISSUE TITLE
Issue in GAN-MNIST example, TypeError.

### ISSUE THREAD

**Issue by ontheway16** [NVIDIA/DIGITS#1989]
@gheinrich 
Hello, I am trying to replicate the GAN example but it throws the following error in model create stage (Tensorflow visualiser also fails with same error).
Any opinions on what may cause this ?

_Alp_

```
2018-03-07 17:01:24.584062: I tensorflow/core/platform/cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2018-03-07 17:01:24.784821: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1212] Found device 0 with properties:
name: GeForce GTX 1080 Ti major: 6 minor: 1 memoryClockRate(GHz): 1.721
pciBusID: 0000:0a:00.0
totalMemory: 10.92GiB freeMemory: 10.60GiB
2018-03-07 17:01:24.784843: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1312] Adding visible gpu devices: 0
2018-03-07 17:01:24.990362: I tensorflow/core/common_runtime/gpu/gpu_device.cc:993] Creating TensorFlow device (/device:GPU:0 with 10262 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1080 Ti, pci bus id: 0000:0a:00.0, compute capability: 6.1)
Traceback (most recent call last):
File "/home/alper/digits/digits/tools/tensorflow/main.py", line 743, in <module>
tf.app.run()
File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 126, in run
_sys.exit(main(argv))
File "/home/alper/digits/digits/tools/tensorflow/main.py", line 494, in main
train_model.create_model(UserModel, stage_scope)  # noqa
File "/home/alper/digits/digits/tools/tensorflow/model.py", line 150, in create_model
y=batch_y_split[dev_i])
File "/home/alper/digits/digits/tools/tensorflow/model.py", line 226, in add_tower
tower = obj_tower(x, y, input_shape, self.nclasses, is_training, is_inference)
File "<string>", line 220, in __init__
File "<string>", line 292, in dcgan_init
File "<string>", line 369, in build_model
File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/histogram_ops.py", line 143, in histogram_fixed_width
values, value_range, nbins, dtype=dtype, name=name)
File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/gen_math_ops.py", line 1840, in _histogram_fixed_width
nbins=nbins, dtype=dtype, name=name)
File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/op_def_library.py", line 720, in _apply_op_helper
attr_value.type = _MakeType(value, attr_def)
File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/op_def_library.py", line 179, in _MakeType
_SatisfiesTypeConstraint(i, attr_def, param_name=attr_def.name)
File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/op_def_library.py", line 60, in _SatisfiesTypeConstraint
", ".join(dtypes.as_dtype(x).name for x in allowed_list)))
TypeError: Value passed to parameter 'dtype' has DataType float32 not in list of allowed values: int32, int64

Last output:
Train batch size is 16 and validation batch size is 16
Training epochs to be completed for each validation : 1
Training epochs to be completed before taking a snapshot : 1.0
Model weights will be saved as snapshot_<EPOCH>_Model.ckpt
Found 52500 images in db /home/alper/digits/digits/jobs/20180307-162335-d97e/train_db
```
    

Here is some info about my linux:
```
$ uname -a
Linux alpcomp 4.13.0-36-generic #40~16.04.1-Ubuntu SMP Fri Feb 16 23:25:58 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```
```
$ nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2017 NVIDIA Corporation
Built on Fri_Sep__1_21:08:03_CDT_2017
Cuda compilation tools, release 9.0, V9.0.176
```
```
$ pip show tensorflow-gpu
---
Metadata-Version: 2.0
Name: tensorflow-gpu
Version: 1.6.0
Summary: TensorFlow helps the tensors flow
Home-page: https://www.tensorflow.org/
Author: Google Inc.
Author-email: opensource@google.com
Installer: pip
License: Apache 2.0
Location: /usr/local/lib/python2.7/dist-packages
Requires: astor, protobuf, gast, tensorboard, six, wheel, absl-py, backports.weakref, termcolor, enum34, numpy, grpcio, mock
Classifiers:
  Development Status :: 4 - Beta
  Intended Audience :: Developers
  Intended Audience :: Education
  Intended Audience :: Science/Research
  License :: OSI Approved :: Apache Software License
  Programming Language :: Python :: 2
  Programming Language :: Python :: 2.7
  Programming Language :: Python :: 3
  Programming Language :: Python :: 3.4
  Programming Language :: Python :: 3.5
  Programming Language :: Python :: 3.6
  Topic :: Scientific/Engineering
  Topic :: Scientific/Engineering :: Mathematics
  Topic :: Scientific/Engineering :: Artificial Intelligence
  Topic :: Software Development
  Topic :: Software Development :: Libraries
  Topic :: Software Development :: Libraries :: Python Modules
Entry-points:
  [console_scripts]
  freeze_graph = tensorflow.python.tools.freeze_graph:main
  saved_model_cli = tensorflow.python.tools.saved_model_cli:main
  tensorboard = tensorboard.main:run_main
  toco = tensorflow.contrib.lite.toco.python.toco_wrapper:main
  toco_from_protos = tensorflow.contrib.lite.toco.python.toco_from_protos:main
You are using pip version 8.1.1, however version 9.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```

**Comment by ontheway16** [comment]
Solved after downgrading to tensorflow 1.4.1.
