### ISSUE TITLE
"error: [Errno 32] Broken pipe" after connecting to digits-devserver

### ISSUE THREAD

**Issue by OlBeXTR** [NVIDIA/DIGITS#2002]
Hello,

since yesterday I get following error after I connect to the devserver via localhost:5000

`Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/gevent/pywsgi.py", line 508, in handle_one_response
    self.run_application()
  File "/usr/local/lib/python2.7/dist-packages/geventwebsocket/handler.py", line 88, in run_application
    return super(WebSocketHandler, self).run_application()
  File "/usr/lib/python2.7/dist-packages/gevent/pywsgi.py", line 495, in run_application
    self.process_result()
  File "/usr/lib/python2.7/dist-packages/gevent/pywsgi.py", line 486, in process_result
    self.write(data)
  File "/usr/lib/python2.7/dist-packages/gevent/pywsgi.py", line 376, in write
    self._write(data)
  File "/usr/lib/python2.7/dist-packages/gevent/pywsgi.py", line 369, in _write
    self._sendall(data)
  File "/usr/lib/python2.7/dist-packages/gevent/pywsgi.py", line 355, in _sendall
    self.socket.sendall(data)
  File "/usr/lib/python2.7/dist-packages/gevent/socket.py", line 458, in sendall
    data_sent += self.send(_get_memory(data, data_sent), flags)
  File "/usr/lib/python2.7/dist-packages/gevent/socket.py", line 435, in send
    return sock.send(data, flags)
error: [Errno 32] Broken pipe
{'GATEWAY_INTERFACE': 'CGI/1.1',
 'HTTP_ACCEPT': '*/*',
 'HTTP_ACCEPT_ENCODING': 'gzip, deflate',
 'HTTP_ACCEPT_LANGUAGE': 'en-US,en;q=0.5',
 'HTTP_CONNECTION': 'keep-alive',
 'HTTP_DNT': '1',
 'HTTP_HOST': 'localhost:5000',
 'HTTP_USER_AGENT': 'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:59.0) Gecko/20100101 Firefox/59.0',
 'PATH_INFO': '/static/images/nvidia.ico',
 'QUERY_STRING': '',
 'REMOTE_ADDR': '127.0.0.1',
 'REMOTE_PORT': '35538',
 'REQUEST_METHOD': 'GET',
 'SCRIPT_NAME': '',
 'SERVER_NAME': 'si-GL72-7RDX',
 'SERVER_PORT': '5000',
 'SERVER_PROTOCOL': 'HTTP/1.1',
 'SERVER_SOFTWARE': 'gevent/1.0 Python/2.7',
 'flask.app': <Flask 'digits.webapp'>,
 'werkzeug.request': None,
 'wsgi.errors': <open file '<stderr>', mode 'w' at 0x7fc97b65a1e0>,
 'wsgi.input': <gevent.pywsgi.Input object at 0x7fc928801f90>,
 'wsgi.multiprocess': False,
 'wsgi.multithread': False,
 'wsgi.run_once': False,
 'wsgi.url_scheme': 'http',
 'wsgi.version': (1, 0)} failed with error
`

DIGITS version is: 6.1.0
Caffe version is: 0.15

Installation was guided by [this](https://github.com/NVIDIA/DIGITS/blob/master/docs/BuildDigits.md) document.

Until yesterday DIGITS ran succesfully and I already trained many networks.
Testing trained networks still works.

**Additional information:**
Yesterday I trained self programmed networks on datasets with only 2 pictures.
At some point when I tested a network DIGITS tried to access a job which was not present in the job folder (.../digits/jobs)

**Comment by OlBeXTR** [comment]
Because there is no proper instruction on how to stop the digits-devserver I always stop it with Ctrl+C in the command line.
Could this be a cause?
Is there a better solution for stopping DIGITS?
