### ISSUE TITLE
CAFFE_ROOT Problem ?

### ISSUE THREAD

**Issue by earcz** [NVIDIA/DIGITS#2032]
**Hi,**

_Note:  (For a long time, I looked for the solution on the internet and asked on devtalk.nvidia but found no solution)_

First, I would like to say that in the beginning of installing DIGITS, I installed **CUDA-9.1, cuDNN-7.1, Nvidia-Driver 390.48 and so on**. I mean everything was the most updated and I followed the guide in NVIDIA/DIGITS. However, I thought that I should have installed older versions and did it in that way. And now, I installed DIGITS-6, Cuda-8.0 and cuDNN-6 regarding the installation guide of a NVIDIA's partner in Turkey. This is their installation guide website: 

When I run `./digits-devserver`

> "/home/deep/caffe" from CAFFE_ROOT does not point to a valid installation of Caffe.
> Use the envvar CAFFE_ROOT to indicate a valid installation.
> Traceback (most recent call last):
>   File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
>     "__main__", fname, loader, pkg_name)
>   File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
>     exec code in run_globals
>   File "/home/deep/digits/digits/__main__.py", line 70, in <module>
>     main()
>   File "/home/deep/digits/digits/__main__.py", line 53, in main
>     import digits.config
>   File "digits/config/__init__.py", line 7, in <module>
>     from . import (  # noqa
>   File "digits/config/caffe.py", line 226, in <module>
>     executable, version, flavor = load_from_envvar('CAFFE_ROOT')
>   File "digits/config/caffe.py", line 37, in load_from_envvar
>     import_pycaffe(python_dir)
>   File "digits/config/caffe.py", line 126, in import_pycaffe
>     import caffe
>   File "/home/deep/caffe/python/caffe/__init__.py", line 1, in <module>
>     from .pycaffe import Net, SGDSolver, NesterovSolver, AdaGradSolver, RMSPropSolver, \
>   File "/home/deep/caffe/python/caffe/pycaffe.py", line 15, in <module>
>     import caffe.io
>   File "/home/deep/caffe/python/caffe/io.py", line 8, in <module>
>     from caffe.proto import caffe_pb2
>   File "/home/deep/caffe/python/caffe/proto/caffe_pb2.py", line 1402, in <module>
>     options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\020\001')), file=DESCRIPTOR),
> TypeError: __new__() got an unexpected keyword argument 'file'

I am aware of that it is a path problem, however, I could not fix this issue. I kindly request your interest on my problem. Thanks in advance.

Ender.

**Comment by earcz** [comment]
I solved the problem. I am not a professional but the problem was most probably the wrong version of installations. Here are what I installed:
1) Cuda 9.0
2) Cudnnv7.1 for cuda 9.0
3) Caffe 0.15.14

Note: I would not brave to install Tensorflow since it seemed a little tricky to me. Because I do not know which version of tensorflow should be installed although I checked for it on the official website of tensorflow. If anyone can help about this issue, I would be appreciate.
