### ISSUE TITLE
ImportError: No module named werkzeug.datastructures while starting DIGITS server

### ISSUE THREAD

**Issue by Sawatdatta** [NVIDIA/DIGITS#2048]
while starting DIGITS server I got following error

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/mydata/DIGITS-master/digits/__main__.py", line 70, in <module>
    main()
  File "/mydata/DIGITS-master/digits/__main__.py", line 53, in main
    import digits.config
  File "digits/config/__init__.py", line 7, in <module>
    from . import (  # noqa
  File "digits/config/caffe.py", line 13, in <module>
    from digits.utils import parse_version
  File "digits/utils/__init__.py", line 167, in <module>
    from . import constants, image, time_filters, errors, forms, routing, auth  # noqa
  File "digits/utils/forms.py", line 4, in <module>
    from werkzeug.datastructures import FileStorage
ImportError: No module named werkzeug.datastructures
```
I tried installing werkzeug using  "pip install werkzeug"  I got following error message: 
It says requirement already satisfied .

```
Requirement already satisfied: werkzeug in /mydata/anaconda3/lib/python3.6/site-packages (0.14.1)
pandas 0.22.0 has requirement python-dateutil>=2, but you'll have python-dateutil 1.5 which is incompatible.
matplotlib 2.1.2 has requirement python-dateutil>=2.1, but you'll have python-dateutil 1.5 which is incompatible.
jupyter-client 5.2.2 has requirement python-dateutil>=2.1, but you'll have python-dateutil 1.5 which is incompatible.
bokeh 0.12.13 has requirement python-dateutil>=2.1, but you'll have python-dateutil 1.5 which is incompatible.
anaconda-client 1.6.9 has requirement python-dateutil>=2.6.1, but you'll have python-dateutil 1.5 which is incompatible
```
Please help me regarding this
OS: ubuntu 18.04
cuda 9.1 and caffe are already installed.

**Comment by kwincu** [comment]
I have same error,I can't find the solution.
Please help me regarding this

**Comment by paddygoat** [comment]
|   \_ _/ __|_ _|_   _/ __|
 | |) | | (_ || |  | | \__ \
 |___/___\___|___| |_| |___/ 6.1.1

Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/tegwyn/digits/digits/__main__.py", line 70, in <module>
    main()
  File "/home/tegwyn/digits/digits/__main__.py", line 53, in main
    import digits.config
  File "digits/config/__init__.py", line 7, in <module>
    from . import (  # noqa
  File "digits/config/caffe.py", line 13, in <module>
    from digits.utils import parse_version
  File "digits/utils/__init__.py", line 167, in <module>
    from . import constants, image, time_filters, errors, forms, routing, auth  # noqa
  File "digits/utils/image.py", line 6, in <module>
    import requests
ImportError: No module named requests

....... Same problem .... No solution :(

**Comment by cyrlop** [comment]
Same problem
