### ISSUE TITLE
ImportError: cannot import name _remove_dead_weakref

### ISSUE THREAD

**Issue by gfjiyue** [NVIDIA/DIGITS#2066]
I met an error when I create model on digits.
The caffe_output.log shows:

Traceback (most recent call last):
File "/home/test/dev/caffe/python/caffe/__init__.py", line 1, in <module>
from .pycaffe import Net, SGDSolver, NesterovSolver, AdaGradSolver, RMSPropSolver, AdaDeltaSolver, AdamSolver
File "/home/test/dev/caffe/python/caffe/pycaffe.py", line 11, in <module>
import numpy as np
File "/home/test/anaconda2/lib/python2.7/site-packages/numpy/__init__.py", line 142, in <module>
from . import add_newdocs
File "/home/test/anaconda2/lib/python2.7/site-packages/numpy/add_newdocs.py", line 13, in <module>
from numpy.lib import add_newdoc
File "/home/test/anaconda2/lib/python2.7/site-packages/numpy/lib/__init__.py", line 8, in <module>
from .type_check import *
File "/home/test/anaconda2/lib/python2.7/site-packages/numpy/lib/type_check.py", line 11, in <module>
import numpy.core.numeric as _nx
File "/home/test/anaconda2/lib/python2.7/site-packages/numpy/core/__init__.py", line 74, in <module>
from numpy.testing import _numpy_tester
File "/home/test/anaconda2/lib/python2.7/site-packages/numpy/testing/__init__.py", line 10, in <module>
from unittest import TestCase
File "/home/test/anaconda2/lib/python2.7/unittest/__init__.py", line 64, in <module>
from .main import TestProgram, main
File "/home/test/anaconda2/lib/python2.7/unittest/main.py", line 7, in <module>
from . import loader, runner
File "/home/test/anaconda2/lib/python2.7/unittest/runner.py", line 7, in <module>
from .signals import registerResult
File "/home/test/anaconda2/lib/python2.7/unittest/signals.py", line 2, in <module>
import weakref
File "/home/test/anaconda2/lib/python2.7/weakref.py", line 14, in <module>
from _weakref import (
ImportError: cannot import name _remove_dead_weakref

**Comment by gfjiyue** [comment]
How to tell digits not use the python2.7 in anaconda?
