### ISSUE TITLE
Error on installing digits. Tensorflow support disabled

### ISSUE THREAD

**Issue by Sprinzzzz** [NVIDIA/DIGITS#2105]
I am getting the following error on digits server while trying to install and run digits.
numpy version -1.15.1. Please help me guys!

Thanks
 ___ ___ ___ ___ _____ ___
```
 |   \_ _/ __|_ _|_   _/ __|
 | |) | | (_ || |  | | \__ \
 |___/___\___|___| |_| |___/ 6.1.1

Tensorflow support disabled.
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/nvidia/DIGITS/digits/__main__.py", line 70, in <module>
    main()
  File "/home/nvidia/DIGITS/digits/__main__.py", line 55, in main
    import digits.webapp
  File "digits/webapp.py", line 7, in <module>
    from flask.ext.socketio import SocketIO
  File "/home/nvidia/.local/lib/python2.7/site-packages/flask/exthook.py", line 87, in load_module
    raise ImportError('No module named %s' % fullname)
ImportError: No module named flask.ext.socketio
```

**Comment by mayankmahajan21** [comment]
Hi, 
have you installed the python packages from requirements.txt?

**Comment by adfayed** [comment]
> Hi,
> have you installed the python packages from requirements.txt?

Yes

**Comment by eve76** [comment]
if you have installed all the packages ,maybe you should pay attention to the path you installed Flask-SocketIO ,maybe you have installed it in another path.
