### ISSUE TITLE
Web installer does not work

### ISSUE THREAD

**Issue by howtobeahacker** [NVIDIA/DIGITS#211]
Hi all,
I followed web installer instructions to install DIGITS 2.0, but it failed to execute runme.sh. It said it could not find Cuda 6.5, while I see in folder lib that they have Cuda 7.0. I also try to make on caffe folder, and it also failed because it could not find cudnn.h. Please make the installer work perfect. Thanks.
I am starting to build DIGITS from source. :smile: 

Did you forget to "make pycaffe"?
Traceback (most recent call last):
  File "digits-devserver", line 39, in <module>
    config.load_config('quiet')
  File "/home/tranlaman/Downloads/digits-2.0/digits/digits/config/load.py", line 147, in load_config
    option.apply()
  File "/home/tranlaman/Downloads/digits-2.0/digits/digits/config/caffe_option.py", line 232, in apply
    import caffe
  File "/home/tranlaman/Downloads/digits-2.0/caffe/python/caffe/__init__.py", line 1, in <module>
    from .pycaffe import Net, SGDSolver
  File "/home/tranlaman/Downloads/digits-2.0/caffe/python/caffe/pycaffe.py", line 13, in <module>
    from ._caffe import Net, SGDSolver
ImportError: libcudart.so.6.5: cannot open shared object file: No such file or directory

**Comment by howtobeahacker** [comment]
Sorry folks,
Due to some mistakes, I reinstall opencv and it worked perfect!
