### ISSUE TITLE
DIGITS: CAFFE_ROOT does not point to a valid installation of Caffe.

### ISSUE THREAD

**Issue by PabloDIGITS** [NVIDIA/DIGITS#2124]
Hi:
Im using Ubuntu 16.04 with a GTX 860M
**I have installed CUDA 10, cuDNN 7.3, NVCaffe 0.15 and DIGITS 6.1.1.**
When I try to run the DIGITS server gives me this error:
`"/usr/home/jetson/caffe/" from CAFFE_ROOT does not point to a valid installation of Caffe.
Use the envvar CAFFE_ROOT to indicate a valid installation.
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/jetson/DIGITS/digits/__main__.py", line 70, in <module>
    main()
  File "/home/jetson/DIGITS/digits/__main__.py", line 53, in main
    import digits.config
  File "digits/config/__init__.py", line 7, in <module>
    from . import (  # noqa
  File "digits/config/caffe.py", line 226, in <module>
    executable, version, flavor = load_from_envvar('CAFFE_ROOT')
  File "digits/config/caffe.py", line 33, in load_from_envvar
    % executable_dir)
ValueError: Caffe executable not found at "/usr/home/jetson/caffe/build/tools"`

**I can find the Caffe executable** in /usr/home/jetson/caffe/build/tools and when I echo $CAFE_ROOT it gives me /usr/home/jetson/caffe
I have installed the python requierements.txt and check it doing sudo pip freeze.
I build Caffe with make all. Pass all the tests with make runtest and make pycaffe gives me no errors.

Can someone help me with this? Thanks in advance!!

**Comment by hujun777** [comment]
I am not sure if you encountered the same issue with me. so far my issue is solved. please try if OK for you?
https://github.com/NVIDIA/DIGITS/issues/2144

**Method**
Installing "protobuf 3.2.x", then re-build Caffe. then got OK.

**Other comments**
1.
We can install "protobuf 3.2.x" following the chapter 3.1.3 of the link:
https://docs.nvidia.com/deeplearning/digits/digits-installation/index.html
2.
During the protobuf installing, if failed in "make install" or "python setup.py....", please try add "sudo"
sudo make install
sudo python setup.py install --cpp_implementation
