### ISSUE TITLE
digits-deserver dosen't work

### ISSUE THREAD

**Issue by hujun777** [NVIDIA/DIGITS#2144]
Following the setup instruction in Ubuntu. Caffe v0.15 make pass. but digits-deserver dosen't work.

LOG is following.
___ ___ ___ ___ _____ ___
 |   \_ _/ __|_ _|_   _/ __|
 | |) | | (_ || |  | | \__ \
 |___/___\___|___| |_| |___/ 6.1.1

ImportError: No module named _multiarray_umath
Did you forget to "make pycaffe"?
"/home/ubuntu/caffe/" from CAFFE_ROOT does not point to a valid installation of Caffe.
Use the envvar CAFFE_ROOT to indicate a valid installation.
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/ubuntu/digits/digits/__main__.py", line 70, in <module>
    main()
  File "/home/ubuntu/digits/digits/__main__.py", line 53, in main
    import digits.config
  File "digits/config/__init__.py", line 7, in <module>
    from . import (  # noqa
  File "digits/config/caffe.py", line 226, in <module>
    executable, version, flavor = load_from_envvar('CAFFE_ROOT')
  File "digits/config/caffe.py", line 37, in load_from_envvar
    import_pycaffe(python_dir)
  File "digits/config/caffe.py", line 126, in import_pycaffe
    import caffe
  File "/home/ubuntu/caffe/python/caffe/__init__.py", line 1, in <module>
    from .pycaffe import Net, SGDSolver, NesterovSolver, AdaGradSolver, RMSPropSolver, AdaDeltaSolver, AdamSolver
  File "/home/ubuntu/caffe/python/caffe/pycaffe.py", line 13, in <module>
    from ._caffe import Net, SGDSolver, NesterovSolver, AdaGradSolver, \
ImportError: numpy.core.multiarray failed to import

**Comment by hujun777** [comment]
**Solved!!**

**Method**
Solved by Installing "protobuf 3.2.x", then re-build Caffe. then got OK.

**Other comments**
1.
We can install "protobuf 3.2.x" following the chapter 3.1.3 of the link:
https://docs.nvidia.com/deeplearning/digits/digits-installation/index.html
2.
During the protobuf installing, if failed in "make install" or "python setup.py....", please try add "sudo"
sudo make install
sudo python setup.py install --cpp_implementation
