### ISSUE TITLE
Object Detection [ERROR] Create train_db DB: OSError 

### ISSUE THREAD

**Issue by CrazyShrimp-pixelPlot** [NVIDIA/DIGITS#2206]
Hello, after 2 days of searching the Webb and trying all i can think of I've decided to ask for some help. I am new to digits so i post the terminal output and please ask for more details as needed. Thanks!

2020-01-12 07:58:09 [20200112-075807-f48d] [INFO ] Create train_db DB task started.
2020-01-12 07:58:09 [20200112-075807-f48d] [INFO ] Task subprocess args: "/usr/bin/python /usr/local/lib/python2.7/dist-packages/digits/tools/create_generic_db.py 20200112-075807-f48d --stage=train_db --jobs_dir=/jobs"
2020-01-12 07:58:09 [20200112-075807-f48d] [INFO ] Create val_db DB task started.
2020-01-12 07:58:09 [20200112-075807-f48d] [INFO ] Task subprocess args: "/usr/bin/python /usr/local/lib/python2.7/dist-packages/digits/tools/create_generic_db.py 20200112-075807-f48d --stage=val_db --jobs_dir=/jobs"
2020-01-12 07:58:09 [20200112-075807-f48d] [INFO ] Create test_db DB task started.
2020-01-12 07:58:09 [20200112-075807-f48d] [INFO ] Task subprocess args: "/usr/bin/python /usr/local/lib/python2.7/dist-packages/digits/tools/create_generic_db.py 20200112-075807-f48d --stage=test_db --jobs_dir=/jobs"
2020-01-12 07:58:10 [20200112-075807-f48d] [WARNING] Create train_db DB unrecognized output: libdc1394 error: Failed to initialize libdc1394
2020-01-12 07:58:10 [20200112-075807-f48d] [WARNING] Create val_db DB unrecognized output: libdc1394 error: Failed to initialize libdc1394
2020-01-12 07:58:10 [20200112-075807-f48d] [WARNING] Create test_db DB unrecognized output: libdc1394 error: Failed to initialize libdc1394
2020-01-12 07:58:10 [20200112-075807-f48d] [ERROR] Create train_db DB: OSError:
2020-01-12 07:58:10 [20200112-075807-f48d] [WARNING] Create train_db DB unrecognized output: Traceback (most recent call last):
2020-01-12 07:58:10 [20200112-075807-f48d] [WARNING] Create train_db DB unrecognized output: File "/usr/local/lib/python2.7/dist-packages/digits/tools/create_generic_db.py", line 478, in <module>
2020-01-12 07:58:10 [20200112-075807-f48d] [WARNING] Create train_db DB unrecognized output: args['stage']
2020-01-12 07:58:10 [20200112-075807-f48d] [WARNING] Create train_db DB unrecognized output: File "/usr/local/lib/python2.7/dist-packages/digits/tools/create_generic_db.py", line 443, in create_generic_db
2020-01-12 07:58:10 [20200112-075807-f48d] [WARNING] Create train_db DB unrecognized output: force_same_shape)
2020-01-12 07:58:10 [20200112-075807-f48d] [WARNING] Create train_db DB unrecognized output: File "/usr/local/lib/python2.7/dist-packages/digits/tools/create_generic_db.py", line 296, in create_db
2020-01-12 07:58:10 [20200112-075807-f48d] [WARNING] Create train_db DB unrecognized output: entry_ids = extension.itemize_entries(stage)
2020-01-12 07:58:10 [20200112-075807-f48d] [WARNING] Create train_db DB unrecognized output: File "/usr/local/lib/python2.7/dist-packages/digits/extensions/data/objectDetection/data.py", line 183, in itemize_entries
2020-01-12 07:58:10 [20200112-075807-f48d] [WARNING] Create train_db DB unrecognized output: self.load_ground_truth(self.train_label_folder)
2020-01-12 07:58:10 [20200112-075807-f48d] [WARNING] Create train_db DB unrecognized output: File "/usr/local/lib/python2.7/dist-packages/digits/extensions/data/objectDetection/data.py", line 208, in load_ground_truth
2020-01-12 07:58:10 [20200112-075807-f48d] [WARNING] Create train_db DB unrecognized output: datasrc.load_gt_obj()
2020-01-12 07:58:10 [20200112-075807-f48d] [WARNING] Create train_db DB unrecognized output: File "/usr/local/lib/python2.7/dist-packages/digits/extensions/data/objectDetection/utils.py", line 174, in load_gt_obj
2020-01-12 07:58:10 [20200112-075807-f48d] [WARNING] Create train_db DB unrecognized output: files = os.listdir(self.label_dir)
2020-01-12 07:58:10 [20200112-075807-f48d] [WARNING] Create train_db DB unrecognized output: OSError: [Errno 2] No such file or directory: 'data/coco/train/labels/dog'
2020-01-12 07:58:11 [20200112-075807-f48d] [ERROR] Create train_db DB task failed with error code 1
2020-01-12 07:58:11 [20200112-075807-f48d] [ERROR] Create val_db DB: OSError:
2020-01-12 07:58:11 [20200112-075807-f48d] [WARNING] Create val_db DB unrecognized output: Traceback (most recent call last):
2020-01-12 07:58:11 [20200112-075807-f48d] [WARNING] Create val_db DB unrecognized output: File "/usr/local/lib/python2.7/dist-packages/digits/tools/create_generic_db.py", line 478, in <module>
2020-01-12 07:58:11 [20200112-075807-f48d] [WARNING] Create val_db DB unrecognized output: args['stage']
2020-01-12 07:58:11 [20200112-075807-f48d] [WARNING] Create val_db DB unrecognized output: File "/usr/local/lib/python2.7/dist-packages/digits/tools/create_generic_db.py", line 443, in create_generic_db
2020-01-12 07:58:11 [20200112-075807-f48d] [WARNING] Create val_db DB unrecognized output: force_same_shape)
2020-01-12 07:58:11 [20200112-075807-f48d] [WARNING] Create val_db DB unrecognized output: File "/usr/local/lib/python2.7/dist-packages/digits/tools/create_generic_db.py", line 296, in create_db
2020-01-12 07:58:11 [20200112-075807-f48d] [WARNING] Create val_db DB unrecognized output: entry_ids = extension.itemize_entries(stage)
2020-01-12 07:58:11 [20200112-075807-f48d] [WARNING] Create val_db DB unrecognized output: File "/usr/local/lib/python2.7/dist-packages/digits/extensions/data/objectDetection/data.py", line 191, in itemize_entries
2020-01-12 07:58:11 [20200112-075807-f48d] [WARNING] Create val_db DB unrecognized output: self.val_min_box_size)
2020-01-12 07:58:11 [20200112-075807-f48d] [WARNING] Create val_db DB unrecognized output: File "/usr/local/lib/python2.7/dist-packages/digits/extensions/data/objectDetection/data.py", line 208, in load_ground_truth
2020-01-12 07:58:11 [20200112-075807-f48d] [WARNING] Create val_db DB unrecognized output: datasrc.load_gt_obj()
2020-01-12 07:58:11 [20200112-075807-f48d] [WARNING] Create val_db DB unrecognized output: File "/usr/local/lib/python2.7/dist-packages/digits/extensions/data/objectDetection/utils.py", line 174, in load_gt_obj
2020-01-12 07:58:11 [20200112-075807-f48d] [WARNING] Create val_db DB unrecognized output: files = os.listdir(self.label_dir)
2020-01-12 07:58:11 [20200112-075807-f48d] [WARNING] Create val_db DB unrecognized output: OSError: [Errno 2] No such file or directory: 'data/coco/val/labels/dog'
2020-01-12 07:58:11 [20200112-075807-f48d] [ERROR] Create val_db DB task failed with error code 1
2020-01-12 07:58:11 [20200112-075807-f48d] [WARNING] Create test_db DB unrecognized output: 2020-01-12 07:58:11 [INFO ] Generic DB creation Done
2020-01-12 07:58:11 [20200112-075807-f48d] [INFO ] Create test_db DB task completed.

**Comment by CrazyShrimp-pixelPlot** [comment]
Just needed to sleep.

Answer to the problem:
I changed my patch from data/coco/train/images/dog
to /data/coco/train/images/dog
