### ISSUE TITLE
Error when creating Segmentation Dataset when using % for validation

### ISSUE THREAD

**Issue by S4WRXTTCS** [NVIDIA/DIGITS#2208]
**Environment:** NGC Container ->  Digits (20.01-caffe-py3) 

**Dataset**: The Aerial Drone Dataset from the jetson-inference Digits tutorial
https://github.com/dusty-nv/jetson-inference/blob/master/docs/segnet-dataset.md

If I follow the instructions exactly then I get the following error when creating the dataset. But, if don't use the percentage split and use a separate for the image/label then I don't get the error. So I think it's a bug. 

"Tensorflow support disabled.
2020-01-30 00:59:41 [ERROR] TypeError: 'range' object does not support item assignment
Traceback (most recent call last):
File "/opt/digits/digits/tools/create_generic_db.py", line 480, in <module>
args['stage']
File "/opt/digits/digits/tools/create_generic_db.py", line 446, in create_generic_db
force_same_shape)
File "/opt/digits/digits/tools/create_generic_db.py", line 298, in create_db
entry_ids = extension.itemize_entries(stage)
File "/opt/digits/digits/extensions/data/imageSegmentation/data.py", line 182, in itemize_entries
feature_image_list = self.split_image_list(feature_image_list, stage)
File "/opt/digits/digits/extensions/data/imageSegmentation/data.py", line 224, in split_image_list
random.shuffle(self.random_indices)
File "/usr/lib/python3.6/random.py", line 277, in shuffle
x[i], x[j] = x[j], x[i]
TypeError: 'range' object does not support item assignment"

**Comment by sowmyakavali** [comment]
I am also facing the same issue

**Comment by celiancherrier** [comment]
I had the same problem, as far as I saw, this comes from the fact that in data.py the List of random indices is generated with a range, and in python 3, a range is from type range, whereas in Python 2 it seems that as soon as it is used it gets transformed into a list (which is accepted in the shuffle function). So the solution for me (I am no programmer so it's surely not the best solution but it worked) was to go into the docker (if you run from a digit docker ) by entering:

`docker exec -u 0 -it 93b2d1accc35 /bin/bash` 

where 93b2d1accc35 is the ID of my container (to find it type `docker ps -a`. then go and edit "/opt/digits/digits/extensions/data/imageSegmentation/data.py" using nano, and change on line 223:

`self.random_indices = range(len(filelist))`  

to 

`self.random_indices = list(range(len(filelist)))`

, making it a list for sure. Once again, this is probably not the proper solution, and it could be the cause of other problems somewhere else in the container... So do at your own risk.
