### ISSUE TITLE
Inference

### ISSUE THREAD

**Issue by lesecs** [NVIDIA/DIGITS#2246]
I have this error in uvr v5 
inference.py: error: argument --input/-i: expected one argument
Dont know how to fix it.

ty

**Comment by brmarkus** [comment]
Which command-line have you called, of which application/example?

**Comment by lesecs** [comment]
Running MGM-v5-2Band-32000-BETA1
usage: inference.py [-h] [--gpu GPU] [--pretrained_model PRETRAINED_MODEL]
                    --input INPUT [--nn_architecture NN_ARCHITECTURE]
                    [--model_params MODEL_PARAMS] [--window_size WINDOW_SIZE]
                    [--output_image] [--deepextraction] [--postprocess]
                    [--tta] [--high_end_process {none,bypass,correlation}]
                    [--aggressiveness AGGRESSIVENESS]
inference.py: error: argument --input/-i: expected one argument

**Comment by brmarkus** [comment]
Can you show the full command-line, paths, parameters, please?
Are you calling "python3 inference.py"... without parameters...?

**Comment by lesecs** [comment]
Run with TTA? [Y/N]: y
=======================================
          Choose Your Model
=======================================

a. HP2-4BAND-3090_4band_1
b. HP2-4BAND-3090_4band_2
c. HP_4BAND_3090
d. Vocal_HP_4BAND_3090
e. Vocal_HP_4BAND_3090_AGG
f. Ensemble All HP Instrumental Models (5 Models) - Final Outputs Save to Ensembled Folder!
g. Ensemble HP2 Models Only (2 Models) - Final Outputs Save to Ensembled Folder!
Type the letter associated with the option you choose and hit 'Enter': a
Running HP2-4BAND-3090_4band_1
usage: inference.py [-h] [--gpu GPU] [--pretrained_model PRETRAINED_MODEL]
                    --input INPUT [--nn_architecture NN_ARCHITECTURE]
                    [--model_params MODEL_PARAMS] [--window_size WINDOW_SIZE]
                    [--output_image] [--deepextraction] [--postprocess]
                    [--tta] [--high_end_process {none,bypass,correlation}]
                    [--aggressiveness AGGRESSIVENESS]
inference.py: error: argument --input/-i: expected one argument

**Comment by lesecs** [comment]
can you tell me where i can find and download the last uvr v5 beta. May be i dont have the last one.
ty

**Comment by lesecs** [comment]
I use python 3.7.9 amd64

**Comment by lesecs** [comment]
Run with TTA? [Y/N]: y
=======================================
          Choose Your Model
=======================================

a. HP2-4BAND-3090_4band_1
b. HP2-4BAND-3090_4band_2
c. HP_4BAND_3090
d. Vocal_HP_4BAND_3090
e. Vocal_HP_4BAND_3090_AGG
f. Ensemble All HP Instrumental Models (5 Models) - Final Outputs Save to Ensembled Folder!
g. Ensemble HP2 Models Only (2 Models) - Final Outputs Save to Ensembled Folder!
Type the letter associated with the option you choose and hit 'Enter': a
Running HP2-4BAND-3090_4band_1
loading model... Traceback (most recent call last):
  File "inference.py", line 273, in <module>
    main()
  File "inference.py", line 133, in main
    model = nets.CascadedASPPNet(mp.param['bins'] * 2)
UnboundLocalError: local variable 'nets' referenced before assignment
