### ISSUE TITLE
DIGITS DOCKET CONTAINER INSTALLING SUNNY PLUGIN

### ISSUE THREAD

**Issue by crmuinos** [NVIDIA/DIGITS#2247]
I'm Sorry, I'm trying to install Sunnybrook for the segmentation example on the docker container, as I want to run it over the TensorFlow backend (not Coffe). I tried to repeat the install procedure from inside the container doing docker exec -it XXXXX bash, being XXX the container ID, and later downloading the plugin from https://github.com/NVIDIA/DIGITS/tree/master/plugins/data and later doing the install proccedure, but it not works. Is there any official way to do this?
I did
pip install --ignore-installed setuptools (no error appears)

> Installing collected packages: setuptools
> Successfully installed setuptools-44.1.1

git clone https://github.com/NVIDIA/DIGITS.git
I went to  /DIGITS/plugins/data/sunnybrook via "cd"
finally I run
pip install .
No error appear, but nothing happens

> Processing /workspace/jobs/DIGITS/plugins/data/sunnybrook
> Collecting pydicom (from digits-sunnybrook-data-plugin==0.0.1)
>   Downloading https://files.pythonhosted.org/packages/53/e6/4cae2b4b2fdbea5e2ddd188361139606d8f10f710ba1abecd6600da099c3/pydicom-1.4.2-py2.py3-none-any.whl (35.3MB)
>     100% |████████████████████████████████| 35.3MB 772kB/s 
> Building wheels for collected packages: digits-sunnybrook-data-plugin
>   Running setup.py bdist_wheel for digits-sunnybrook-data-plugin ... done
>   Stored in directory: /tmp/pip-ephem-wheel-cache-0mp6oe/wheels/02/69/22/963af5cb0119b7c5f61d06d268fb51f066afd07a3f09782b77
> Successfully built digits-sunnybrook-data-plugin
> Installing collected packages: pydicom, digits-sunnybrook-data-plugin
> Successfully installed digits-sunnybrook-data-plugin-0.0.1 pydicom-1.4.2
> You are using pip version 18.0, however version 20.3.4 is available.
> 

Can you help please?
Kind regards

**Comment by crmuinos** [comment]
After doing docker restart it appears the LV Sunny segmentation button for both create dataSet and model, but when trying to create a dataset, it fails. It seems to be a PIL problem

2022-04-14 00:47:16 [INFO ] Created features db for stage train_db in train_db/features
Exception in thread Thread-3:
Traceback (most recent call last):
File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
self.run()
File "/opt/digits/digits/tools/create_generic_db.py", line 278, in run
self.writer.write_batch(data)
File "/opt/digits/digits/tools/create_generic_db.py", line 169, in write_batch
self.feature_encoding)
File "/opt/digits/digits/tools/create_generic_db.py", line 133, in array_to_datum
PIL.Image.fromarray(data).save(s, format='PNG')
File "/usr/local/lib/python2.7/dist-packages/PIL/Image.py", line 2419, in fromarray
raise TypeError("Cannot handle this data type")
TypeError: Cannot handle this data type
Exception in thread Thread-2:
Traceback (most recent call last):
File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
self.run()
File "/opt/digits/digits/tools/create_generic_db.py", line 278, in run
self.writer.write_batch(data)
File "/opt/digits/digits/tools/create_generic_db.py", line 169, in write_batch
self.feature_encoding)
File "/opt/digits/digits/tools/create_generic_db.py", line 133, in array_to_datum
PIL.Image.fromarray(data).save(s, format='PNG')
File "/usr/local/lib/python2.7/dist-packages/PIL/Image.py", line 2419, in fromarray
raise TypeError("Cannot handle this data type")
TypeError: Cannot handle this data type
Exception in thread Thread-5:
Traceback (most recent call last):
File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
self.run()
File "/opt/digits/digits/tools/create_generic_db.py", line 278, in run
self.writer.write_batch(data)
File "/opt/digits/digits/tools/create_generic_db.py", line 169, in write_batch
self.feature_encoding)
File "/opt/digits/digits/tools/create_generic_db.py", line 133, in array_to_datum
PIL.Image.fromarray(data).save(s, format='PNG')
File "/usr/local/lib/python2.7/dist-packages/PIL/Image.py", line 2419, in fromarray
raise TypeError("Cannot handle this data type")
TypeError: Cannot handle this data type
Exception in thread Thread-4:
Traceback (most recent call last):
File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
self.run()
File "/opt/digits/digits/tools/create_generic_db.py", line 278, in run
self.writer.write_batch(data)
File "/opt/digits/digits/tools/create_generic_db.py", line 169, in write_batch
self.feature_encoding)
File "/opt/digits/digits/tools/create_generic_db.py", line 133, in array_to_datum
PIL.Image.fromarray(data).save(s, format='PNG')
File "/usr/local/lib/python2.7/dist-packages/PIL/Image.py", line 2419, in fromarray
raise TypeError("Cannot handle this data type")
TypeError: Cannot handle this data type
2022-04-14 00:47:16 [ERROR] TypeError: Cannot handle this data type
2022-04-14 00:47:16 [ERROR] TypeError: Cannot handle this data type
2022-04-14 00:47:16 [ERROR] TypeError: Cannot handle this data type
2022-04-14 00:47:16 [ERROR] TypeError: Cannot handle this data type
2022-04-14 00:47:16 [ERROR] Exception: TypeError: Cannot handle this data type
Traceback (most recent call last):
File "/opt/digits/digits/tools/create_generic_db.py", line 478, in <module>
args['stage']
File "/opt/digits/digits/tools/create_generic_db.py", line 443, in create_generic_db
force_same_shape)
File "/opt/digits/digits/tools/create_generic_db.py", line 341, in create_db
raise Exception(err)
