### ISSUE TITLE
Don't work DIGITS

### ISSUE THREAD

**Issue by SifonFeramon** [NVIDIA/DIGITS#238]
I have some trouble for work DIGITS on Windows. Who knows about this error? I install Caffe,openCV,cuDNN.

F:\DIGITS-master\DIGITS-master>C:\Anaconda\python.exe digits-devserver
Traceback (most recent call last):
  File "digits-devserver", line 44, in <module>
    from digits.webapp import app, socketio, scheduler
  File "F:\DIGITS-master\DIGITS-master\digits\webapp.py", line 45, in <module>
    import digits.views
  File "F:\DIGITS-master\DIGITS-master\digits\views.py", line 15, in <module>
    import dataset.views
  File "F:\DIGITS-master\DIGITS-master\digits\dataset\views.py", line 8, in <module>
    import images.views
  File "F:\DIGITS-master\DIGITS-master\digits\dataset\images\views.py", line 12,
 in <module>
    import classification.views
  File "F:\DIGITS-master\DIGITS-master\digits\dataset\images\classification\views.py", line 245, in <module>
    @autodoc(['datasets', 'api'])
  File "C:\Anaconda\lib\site-packages\flask_autodoc\autodoc.py", line 63, in decorator
    groupset.add(group)
TypeError: unhashable type: 'list'

**Comment by gheinrich** [comment]
Perhaps you can try installing Luke's version of autodoc: https://github.com/lukeyeager/flask-autodoc.git

**Comment by SifonFeramon** [comment]
Yes, thanks for advice.
it is work now.
