### ISSUE TITLE
LMDB version error hidden in logs

### ISSUE THREAD

**Issue by jmozah** [NVIDIA/DIGITS#242]
i created a dataset and it looks like there is some exception in the logs.. but the UI show that things are in progress and gets stuck for hours...

2015-08-28 07:58:55 [20150828-075854-7d9e] [INFO ] Parse Folder (train/val) task started.
2015-08-28 07:58:56 [20150828-075854-7d9e] [INFO ] Parse Folder (train/val) task completed.
2015-08-28 07:58:56 [20150828-075854-7d9e] [INFO ] Create DB (train) task started.
2015-08-28 07:58:56 [20150828-075854-7d9e] [INFO ] Create DB (val) task started.
2015-08-28 07:58:58 [20150828-075854-7d9e] [WARNING] Create DB (val) unrecognized output: Exception in thread Thread-11:
2015-08-28 07:58:58 [20150828-075854-7d9e] [WARNING] Create DB (val) unrecognized output: Traceback (most recent call last):
2015-08-28 07:58:58 [20150828-075854-7d9e] [WARNING] Create DB (val) unrecognized output: File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
2015-08-28 07:58:58 [20150828-075854-7d9e] [WARNING] Create DB (val) unrecognized output: self.run()
2015-08-28 07:58:58 [20150828-075854-7d9e] [WARNING] Create DB (val) unrecognized output: File "/usr/lib/python2.7/threading.py", line 763, in run
2015-08-28 07:58:58 [20150828-075854-7d9e] [WARNING] Create DB (val) unrecognized output: self.__target(*self.__args, **self.__kwargs)
2015-08-28 07:58:58 [20150828-075854-7d9e] [WARNING] Create DB (val) unrecognized output: File "/home/zahoor/digits/tools/create_db.py", line 436, in write_thread
2015-08-28 07:58:58 [20150828-075854-7d9e] [WARNING] Create DB (val) unrecognized output: self.write_batch(batch)
2015-08-28 07:58:58 [20150828-075854-7d9e] [WARNING] Create DB (val) unrecognized output: File "/home/zahoor/digits/tools/create_db.py", line 467, in write_batch
2015-08-28 07:58:58 [20150828-075854-7d9e] [WARNING] Create DB (val) unrecognized output: self.db.set_mapsize(new_limit) # double it
2015-08-28 07:58:58 [20150828-075854-7d9e] [WARNING] Create DB (val) unrecognized output: AttributeError: 'Environment' object has no attribute 'set_mapsize'
2015-08-28 07:58:58 [20150828-075854-7d9e] [WARNING] Create DB (train) unrecognized output: Exception in thread Thread-11:
2015-08-28 07:58:58 [20150828-075854-7d9e] [WARNING] Create DB (train) unrecognized output: Traceback (most recent call last):
2015-08-28 07:58:58 [20150828-075854-7d9e] [WARNING] Create DB (train) unrecognized output: File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
2015-08-28 07:58:58 [20150828-075854-7d9e] [WARNING] Create DB (train) unrecognized output: self.run()
2015-08-28 07:58:58 [20150828-075854-7d9e] [WARNING] Create DB (train) unrecognized output: File "/usr/lib/python2.7/threading.py", line 763, in run
2015-08-28 07:58:58 [20150828-075854-7d9e] [WARNING] Create DB (train) unrecognized output: self.__target(*self.__args, **self.__kwargs)
2015-08-28 07:58:58 [20150828-075854-7d9e] [WARNING] Create DB (train) unrecognized output: File "/home/zahoor/digits/tools/create_db.py", line 436, in write_thread
2015-08-28 07:58:58 [20150828-075854-7d9e] [WARNING] Create DB (train) unrecognized output: self.write_batch(batch)
2015-08-28 07:58:58 [20150828-075854-7d9e] [WARNING] Create DB (train) unrecognized output: File "/home/zahoor/digits/tools/create_db.py", line 467, in write_batch
2015-08-28 07:58:58 [20150828-075854-7d9e] [WARNING] Create DB (train) unrecognized output: self.db.set_mapsize(new_limit) # double it
2015-08-28 07:58:58 [20150828-075854-7d9e] [WARNING] Create DB (train) unrecognized output: AttributeError: 'Environment' object has no attribute 'set_mapsize'

**Comment by gheinrich** [comment]
Hi, you need to upgrade your lmdb python package to >=0.87:
`pip install lmdb -U`

**Comment by lukeyeager** [comment]
I need to find a way to propagate this error up so that DIGITS can detect it and display it. We can't expect people to run the test suite first. @jmozah, I'm going to hijack this issue and mark it as a bug to fix.
