### ISSUE TITLE
Error when web installing DIGITS 

### ISSUE THREAD

**Issue by mongoose54** [NVIDIA/DIGITS#250]
So I am following the instructions here:

At the end I get the following error:

```
Extracting MNIST images ...

Traceback (most recent call last):
  File "mnist/main.py", line 8, in <module>
    from mnist import MnistDownloader
  File "/home/alex/Desktop/DIGITS/digits-2.0/mnist/mnist.py", line 6, in <module>
    import numpy as np
  File "/usr/lib/python2.7/dist-packages/numpy/__init__.py", line 153, in <module>
    from . import add_newdocs
  File "/usr/lib/python2.7/dist-packages/numpy/add_newdocs.py", line 13, in <module>
    from numpy.lib import add_newdoc
  File "/usr/lib/python2.7/dist-packages/numpy/lib/__init__.py", line 8, in <module>
    from .type_check import *
  File "/usr/lib/python2.7/dist-packages/numpy/lib/type_check.py", line 11, in <module>
    import numpy.core.numeric as _nx
  File "/usr/lib/python2.7/dist-packages/numpy/core/__init__.py", line 6, in <module>
    from . import multiarray
ImportError: PyCapsule_Import could not import module "datetime"
```
I am running Ubuntu 15.04 instead of 14.04. Do you think that might be a problem? Thanks!

**Comment by lukeyeager** [comment]
From https://github.com/NVIDIA/DIGITS/blob/digits-2.0/docs/WebInstall.md:

> NOTE: This installer includes binaries built for Ubuntu 14.04. The installer will not work on any other platform.

I think even if you get past the `datetime` error, you are likely to run into more issues later. You will probably need to follow these directions to get and build the dependencies manually:

https://github.com/NVIDIA/DIGITS/blob/digits-2.0/README.md

**Comment by mongoose54** [comment]
@lukeyeager I used Ubuntu 14.04 and it installed.
