### ISSUE TITLE
Torch tests non-deterministic

### ISSUE THREAD

**Issue by lukeyeager** [NVIDIA/DIGITS#346]
It looks like the image classification tests for Torch aren't always passing.

https://travis-ci.org/NVIDIA/DIGITS/builds/83389812
```
======================================================================
FAIL: digits.model.images.classification.test_views.TestTorchCreatedHdf5.test_classify_one
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/miniconda/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/travis/build/NVIDIA/DIGITS/digits/model/images/classification/test_views.py", line 464, in test_classify_one
    assert predictions[0][1] == category, 'image misclassified'
AssertionError: image misclassified
-------------------- >> begin captured logging << --------------------
digits.webapp: INFO: torch classify one task started.
digits.webapp: DEBUG: torch classify one task : Loading network definition from /tmp/tmpy7uo1W/20151002-224746-faf2/model
digits.webapp: DEBUG: torch classify one task : Loading /tmp/tmpy7uo1W/20151002-224746-faf2/snapshot_10_Weights.t7 file
digits.webapp: INFO: torch classify one task completed.
--------------------- >> end captured logging << ---------------------

======================================================================
FAIL: digits.model.images.classification.test_views.TestTorchCreatedHdf5.test_classify_one_json
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/miniconda/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/travis/build/NVIDIA/DIGITS/digits/model/images/classification/test_views.py", line 483, in test_classify_one_json
    assert data['predictions'][0][0] == category, 'image misclassified'
AssertionError: image misclassified
-------------------- >> begin captured logging << --------------------
digits.webapp: INFO: torch classify one task started.
digits.webapp: DEBUG: torch classify one task : Loading network definition from /tmp/tmpy7uo1W/20151002-224746-faf2/model
digits.webapp: DEBUG: torch classify one task : Loading /tmp/tmpy7uo1W/20151002-224746-faf2/snapshot_10_Weights.t7 file
digits.webapp: INFO: torch classify one task completed.
--------------------- >> end captured logging << ---------------------
```

**Comment by gheinrich** [comment]
I think there are still some rare occasions when this test fails despite #348. I will keep looking into it.

**Comment by lukeyeager** [comment]
Two more misclassified images in this build: https://travis-ci.org/NVIDIA/DIGITS/builds/86228048

Did #376 make it worse?

**Comment by gheinrich** [comment]
I don't think #376 is at fault here as this PR didn't change the classification path (provided the network does not diverge).
I am going to put more priority on trying to nail this down.

**Comment by lukeyeager** [comment]
Ok, I just saw this and thought it might be related somehow:
```lua
-- remove any non determinism
net:apply(function(layer) if layer.weight then layer.weight:fill(0) end if layer.bias then layer.bias:fill(0) end end)
```

**Comment by lukeyeager** [comment]
This seems to be resolved.
