### ISSUE TITLE
error: Gdk-CRITICAL **: gdk_cursor_new_for_display

### ISSUE THREAD

**Issue by yarin05** [NVIDIA/DIGITS#354]
Hi everybody,
On amazon server g2.2xlarge running ubuntu 14.04
I've tried to install digits. (after installing cuda, cudnn and caffe successfully)

But, When I try to run the file 'runme.sh' in the Digits-2.0 directory, I encounter the following error:

libdc1394 error: Failed to initialize libdc1394
PuTTY X11 proxy: unable to connect to forwarded X server: Network error: Connection refused

** (digits-devserver:12172): WARNING **: Could not open X display
PuTTY X11 proxy: unable to connect to forwarded X server: Network error: Connection refused
PuTTY X11 proxy: unable to connect to forwarded X server: Network error: Connection refused

(digits-devserver:12172): Gdk-CRITICAL **: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Traceback (most recent call last):
  File "digits-devserver", line 39, in <module>
    config.load_config('quiet')
  File "/mnt/yarin/digits/digits-2.0/digits/digits/config/load.py", line 147, in load_config
    option.apply()
  File "/mnt/yarin/digits/digits-2.0/digits/digits/config/caffe_option.py", line 232, in apply
    import caffe
  File "/mnt/yarin/digits/digits-2.0/caffe/python/caffe/__init__.py", line 1, in <module>
    from .pycaffe import Net, SGDSolver
  File "/mnt/yarin/digits/digits-2.0/caffe/python/caffe/pycaffe.py", line 14, in <module>
    import caffe.io
  File "/mnt/yarin/digits/digits-2.0/caffe/python/caffe/io.py", line 2, in <module>
    import skimage.io
  File "/usr/local/lib/python2.7/dist-packages/skimage/io/__init__.py", line 15, in <module>
    reset_plugins()
  File "/usr/local/lib/python2.7/dist-packages/skimage/io/manage_plugins.py", line 89, in reset_plugins
    _load_preferred_plugins()
  File "/usr/local/lib/python2.7/dist-packages/skimage/io/manage_plugins.py", line 69, in _load_preferred_plugins
    _set_plugin(p_type, preferred_plugins['all'])
  File "/usr/local/lib/python2.7/dist-packages/skimage/io/manage_plugins.py", line 81, in _set_plugin
    use_plugin(plugin, kind=plugin_type)
  File "/usr/local/lib/python2.7/dist-packages/skimage/io/manage_plugins.py", line 251, in use_plugin
    _load(name)
  File "/usr/local/lib/python2.7/dist-packages/skimage/io/manage_plugins.py", line 295, in _load
    fromlist=[modname])
  File "/usr/local/lib/python2.7/dist-packages/skimage/io/_plugins/matplotlib_plugin.py", line 4, in <module>
    import matplotlib.pyplot as plt
  File "/usr/local/lib/python2.7/dist-packages/matplotlib/pyplot.py", line 109, in <module>
    _backend_mod, new_figure_manager, draw_if_interactive, _show = pylab_setup()
  File "/usr/local/lib/python2.7/dist-packages/matplotlib/backends/__init__.py", line 32, in pylab_setup
    globals(),locals(),[backend_name],0)
  File "/usr/local/lib/python2.7/dist-packages/matplotlib/backends/backend_gtk3agg.py", line 11, in <module>
    from . import backend_gtk3
  File "/usr/local/lib/python2.7/dist-packages/matplotlib/backends/backend_gtk3.py", line 55, in <module>
    cursors.MOVE          : Gdk.Cursor.new(Gdk.CursorType.FLEUR),
TypeError: constructor returned NULL

How can I fix this error?

**Comment by yarin05** [comment]
problem solved, what i did is to download Xming and start it before putty, in addition i worte in putty->ssh>X11->  enable   +  localhost:0  at "X display location"

**Comment by lukeyeager** [comment]
Glad you worked it out. There is a way to install the driver and/or install X such that you don't have to do this. Unfortunately I don't have the details on how to do that at the moment.

**Comment by choosehappy** [comment]
I also had an issue with this; to resolve i simply used a virtual framebuffer, and everything worked without a problem.

On ubuntu:
sudo apt-get install xvfb
xvfb-run ./digits-server
