### ISSUE TITLE
run error

### ISSUE THREAD

**Issue by Michael-Guo** [NVIDIA/DIGITS#356]
I installed digits 2.0 follow the Installation Instructions. But when I run runme.sh, I meet an error:

cudaRuntimeGetVersion() failed with error #35

Then I run the runtest.sh. The results are as follow:
```
FAIL: digits.test_webapp.TestModelCreation.test_alltests('GRAY',)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/lq/digits-2.0/venv/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/lq/digits-2.0/digits/digits/test_webapp.py", line 652, in check_snapshot_interval_2
    assert self.model_wait_completion(job_id) == 'Done', 'create failed'
AssertionError: create failed
-------------------- >> begin captured logging << --------------------
digits: DEBUG: Train Caffe Model task started.
digits.webapp: INFO: Train Caffe Model task started.
digits.webapp: ERROR: Train Caffe Model: Cannot create Cublas handle. Cublas won't be available.
digits.webapp: ERROR: Train Caffe Model: Cannot create Curand generator. Curand won't be available.
digits.webapp: ERROR: Train Caffe Model: Cannot create cuDNN handle. cuDNN won't be available.
digits.webapp: ERROR: Train Caffe Model: Check failed: error == cudaSuccess (35 vs. 0)  CUDA driver version is insufficient for CUDA runtime version
digits.webapp: ERROR: Train Caffe Model task failed with error code -6
--------------------- >> end captured logging << ---------------------

======================================================================
FAIL: digits.test_webapp.TestModelCreation.test_alltests('GRAY',)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/lq/digits-2.0/venv/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/lq/digits-2.0/digits/digits/test_webapp.py", line 661, in check_snapshot_interval_0_5
    assert self.model_wait_completion(job_id) == 'Done', 'create failed'
AssertionError: create failed
-------------------- >> begin captured logging << --------------------
digits: DEBUG: Train Caffe Model task started.
digits.webapp: INFO: Train Caffe Model task started.
digits.webapp: ERROR: Train Caffe Model: Cannot create Cublas handle. Cublas won't be available.
digits.webapp: ERROR: Train Caffe Model: Cannot create Curand generator. Curand won't be available.
digits.webapp: ERROR: Train Caffe Model: Cannot create cuDNN handle. cuDNN won't be available.
digits.webapp: ERROR: Train Caffe Model: Check failed: error == cudaSuccess (35 vs. 0)  CUDA driver version is insufficient for CUDA runtime version
digits.webapp: ERROR: Train Caffe Model task failed with error code -6
```
By the way, Caffe is working well in my computer. CUDA version is 6.5. GPU model is Tesla K40. It's driver version is 340.29.

 According to the test results, I think the CUDA may result in the error. How to solve this problem. Thanks!

**Comment by gheinrich** [comment]
Hi @Michael-Guo, the 2.0 web installer comes with CUDA 7.0, which requires driver version 346.xx. Can you update your Nvidia driver?

**Comment by gheinrich** [comment]
@Michael-Guo are you happy with the answer? Thanks!
