### ISSUE TITLE
Socket.error: [Errno 98] Address already in use: ('0.0.0.0', 5000)

### ISSUE THREAD

**Issue by fanser** [NVIDIA/DIGITS#489]
Hi, everyone! 
My installation method is via deb package. And I follow this link to install.
https://github.com/NVIDIA/DIGITS/blob/master/docs/UbuntuInstall.md
But when type  'sudo ./digits-devserver -c'  after installed , I get some errors:
1. modprobe: FATAL: Module nvidia not found.
cudaRuntimeGetVersion() failed with error #38
(I use the CPU-ONLY model, because the graphic card can't support CUDA in my computer )

2.socket.error: [Errno 98] Address already in use: ('0.0.0.0', 5000)

My digit vision is 3.0.3. 
The next section  is  return.
Thanks .
```
fzy@fzy-OptiPlex-3020:/usr/share/digits$ sudo ./digits-devserver -c
================================ Jobs Directory ================================
Where would you like to store job data?

	Suggested values:
	(*)  [Previous] /usr/share/digits/digits/jobs
	(D)  [default]  /usr/share/digits/digits/jobs
>> 
Using "/usr/share/digits/digits/jobs"

modprobe: FATAL: Module nvidia not found.
cudaRuntimeGetVersion() failed with error #38
=================================== Log File ===================================
Where do you want the log files to be stored?

	Suggested values:
	(*)  [Previous] /var/log/digits/digits.log
	(S)  [System]   /var/log/digits/digits.log
	(D)  [default]  /usr/share/digits/digits/digits.log
	(N)  [none]     <NONE>
>> 
Using "/var/log/digits/digits.log"

==================================== Caffe =====================================
Where is caffe installed?

	Suggested values:
	(*)  [Previous]        <PATHS>
	(P)  [PATH/PYTHONPATH] <PATHS>
>> 
Using "<PATHS>"

==================================== Torch =====================================
Where is torch installed?

	Suggested values:
	(*)  [Previous]       <PATHS>
	(P)  [PATH/TORCHPATH] <PATHS>
	(N)  [none]           <NONE>
>> 
Using "<PATHS>"

  ___ ___ ___ ___ _____ ___
 |   \_ _/ __|_ _|_   _/ __|
 | |) | | (_ || |  | | \__ \
 |___/___\___|___| |_| |___/ 3.0.0-rc.3

 * Running on http://0.0.0.0:5000/
Traceback (most recent call last):
  File "./digits-devserver", line 58, in <module>
    policy_server=False
  File "/usr/lib/python2.7/dist-packages/flask_socketio/__init__.py", line 414, in run
    self.server.serve_forever()
  File "/usr/lib/python2.7/dist-packages/gevent/baseserver.py", line 282, in serve_forever
    self.start()
  File "/usr/lib/python2.7/dist-packages/gevent/baseserver.py", line 234, in start
    self.init_socket()
  File "/usr/lib/python2.7/dist-packages/gevent/pywsgi.py", line 639, in init_socket
    StreamServer.init_socket(self)
  File "/usr/lib/python2.7/dist-packages/gevent/server.py", line 78, in init_socket
    self.socket = self.get_listener(self.address, self.backlog, self.family)
  File "/usr/lib/python2.7/dist-packages/gevent/server.py", line 89, in get_listener
    return _tcp_listener(address, backlog=backlog, reuse_addr=self.reuse_addr, family=family)
  File "/usr/lib/python2.7/dist-packages/gevent/server.py", line 153, in _tcp_listener
    sock.bind(address)
  File "<string>", line 1, in bind
socket.error: [Errno 98] Address already in use: ('0.0.0.0', 5000)

```

**Comment by fanser** [comment]
@lukeyeager thanks!

**Comment by fanser** [comment]
Well, I have solved second question. The first is waiting...

**Comment by lukeyeager** [comment]
That error means you already have another instance of the DIGITS devserver running. You can try using `ps ax | grep digits` to find the other process and kill it with `kill -INT`, or just reboot your machine if that's easier.
