### ISSUE TITLE
[ERROR] ValueError: math domain error

### ISSUE THREAD

**Issue by mingtop** [NVIDIA/DIGITS#50]
[DEBUG] Train Caffe Model task queued.
2015-04-07 19:32:44 [20150407-193242-7b4c] [INFO ] Train Caffe Model task started.
2015-04-07 19:32:45 [20150407-193242-7b4c] [ERROR] ValueError: math domain error

I don't know why the firefox getdata from  www.google.com.....

I did the example follow by readme.md 

who can explain,3 q

**Comment by lukeyeager** [comment]
Hi @mingtop, can you give me a little more information about your installation? Did you use the web installer or clone from GitHub? If it was from GitHub, how recently did you clone the repository? (Show me the output of `git log -n1`).

`math domain error` is not a very helpful error message - if we can figure out what's going wrong, I'll try to improve DIGITS such that the error will at least be more clear in the future if it can't be avoided entirely.

**Comment by mingtop** [comment]
Traceback (most recent call last):
  File "/home/jamin/Downloads/digits-1.0/digits/digits/scheduler.py", line 382, in task_thread
    task.run(**options)
  File "/home/jamin/Downloads/digits-1.0/digits/digits/task.py", line 196, in run
    if not self.process_output(line):
  File "/home/jamin/Downloads/digits-1.0/digits/digits/model/tasks/caffe_train.py", line 468, in process_output
    self.logger.debug('memory required: %s' % utils.sizeof_fmt(bytes_required))
  File "/home/jamin/Downloads/digits-1.0/digits/digits/utils/__init__.py", line 100, in sizeof_fmt
    i = int(math.floor(math.log(size,1024)))
ValueError: math domain error

**Comment by mingtop** [comment]
@lukeyeager  I download digital from nvidia websit 
I will update my digits from github 
here is the error 
Traceback (most recent call last):
File "/home/jamin/Downloads/digits-1.0/digits/digits/scheduler.py", line 382, in task_thread
task.run(**options)
File "/home/jamin/Downloads/digits-1.0/digits/digits/task.py", line 196, in run
if not self.process_output(line):
File "/home/jamin/Downloads/digits-1.0/digits/digits/model/tasks/caffe_train.py", line 468, in process_output
self.logger.debug('memory required: %s' % utils.sizeof_fmt(bytes_required))
File "/home/jamin/Downloads/digits-1.0/digits/digits/utils/init.py", line 100, in sizeof_fmt
i = int(math.floor(math.log(size,1024)))
ValueError: math domain error

------------------------------------
In university of china ,we can't  get google app and web chart application , so I hope you can improve it

**Comment by mingtop** [comment]
@lukeyeager  You are right, maybe I got a earily version. Now I fixed the problem by git a new version. Thank u very much.

**Comment by lukeyeager** [comment]
Yep, you were running into these issues: #13 and #9. They have since been fixed.
