### ISSUE TITLE
UnicodeDecode error

### ISSUE THREAD

**Issue by oanoelsis** [NVIDIA/DIGITS#703]
I use korean word in my labels.txt (i.e. 곽, 박). And when i doing classify in DIGITS, it said error like below. So i changed my labels.txt. Now it doesn't have any NOT ascii words. But it still makes error like below. Where this error come from? And how can i handle korean words? (I already saw several issues in DIGITS github, but nothing work for me. )  

-----------------------------------------------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/share/digits/digits/model/images/classification/views.py", line 305, in image_classification_model_classify_one
    total_parameters= sum(v['param_count'] for v in visualizations if v['vis_type'] == 'Weights'),
  File "/usr/lib/python2.7/dist-packages/flask/templating.py", line 128, in render_template
    context, ctx.app)
  File "/usr/lib/python2.7/dist-packages/flask/templating.py", line 110, in _render
    rv = template.render(context)
  File "/usr/lib/python2.7/dist-packages/jinja2/environment.py", line 969, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/lib/python2.7/dist-packages/jinja2/environment.py", line 742, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/share/digits/digits/templates/models/images/classification/classify_one.html", line 2, in top-level template code
    {% extends "layout.html" %}
  File "/usr/share/digits/digits/templates/layout.html", line 46, in top-level template code
    {% block content %}
  File "/usr/share/digits/digits/templates/models/images/classification/classify_one.html", line 33, in block "content"
    {{ label }}
UnicodeDecodeError: 'ascii' codec can't decode byte 0xeb in position 1: ordinal not in range(128)

**Comment by gheinrich** [comment]
Hello, did you modify `labels.txt` **after** creating the model? That wouldn't work (labels are stored in the job state on disk). Did you try the solution proposed on https://github.com/NVIDIA/DIGITS/issues/353#issuecomment-147453764?

**Comment by oanoelsis** [comment]
Yes, I modify labels.txt after creating the model... I already tried #353 solutions but it didn't work for me. Is there anyway I can modify labels.txt after creating the model?(If i should change the model. That means I must do my whole training jobs once again..)

**Comment by gheinrich** [comment]
The solution on https://github.com/NVIDIA/DIGITS/issues/353#issuecomment-147453764 worked for me. Did you reload DIGITS after making the change in `webapp.py`? 

Otherwise as a quick hack you can try replacing this [line](https://github.com/NVIDIA/DIGITS/blob/v3.2.0/digits/templates/models/images/classification/classify_one.html#L33) with:
```
{{loop.index}}
```
This will show the class ID, not the class name, but at least you won't have to retrain the model.

**Comment by oanoelsis** [comment]
When I restart the server it works well!! really thank you!!
