### ISSUE TITLE
How to use OpenBLAS with DIGITS?

### ISSUE THREAD

**Issue by dimon777** [NVIDIA/DIGITS#770]
Hi All,
I have followed instructions how to install DIGITS from source: https://github.com/NVIDIA/DIGITS/blob/master/docs/BuildDigits.md. I've compiled fine caffe-nv using OpenBlas. Starting DIGITS gives me error about missing library from ATLAS. Is there a way to tell DIGITS to use OpenBLAS instead of ATLAS?

```
 # ./digits-devserver
Traceback (most recent call last):
  File "./digits-devserver", line 31, in <module>
    from digits import config
  File "/data/src/nvidia/DIGITS/digits/config/__init__.py", line 7, in <module>
    from .current_config import config_value
  File "/data/src/nvidia/DIGITS/digits/config/current_config.py", line 4, in <module>
    from .caffe_option import CaffeOption
  File "/data/src/nvidia/DIGITS/digits/config/caffe_option.py", line 14, in <module>
    from digits.utils import parse_version
  File "/data/src/nvidia/DIGITS/digits/utils/__init__.py", line 157, in <module>
    from . import constants, image, time_filters, errors, forms, routing, auth
  File "/data/src/nvidia/DIGITS/digits/utils/image.py", line 16, in <module>
    import scipy.misc
  File "/usr/lib/python2.7/site-packages/scipy/misc/__init__.py", line 51, in <module>
    from scipy.special import comb, factorial, factorial2, factorialk
  File "/usr/lib/python2.7/site-packages/scipy/special/__init__.py", line 627, in <module>
    from ._ufuncs import *
ImportError: libf77blas.so.3: cannot open shared object file: No such file or directory
```

**Comment by gheinrich** [comment]
It looks like your `numpy` installation is still configured to use ATLAS. Perhaps you need to re-install `python-numpy` and `python-scipy` packages?

**Comment by lukeyeager** [comment]
You can install both ATLAS and OpenBLAS at the same time if you need to. Make sure you also install lapack, though, so you don't run into this problem:

http://stackoverflow.com/a/34956540/2404152

**Comment by dimon777** [comment]
My bad :) Closing this...
