### ISSUE TITLE
libdc1394 error: Failed to initialize libdc1394

### ISSUE THREAD

**Issue by joyofdata** [NVIDIA/DIGITS#78]
Hi!

(Working on Ubuntu 14.04 AMI on EC2 instance g2.2xlarge)

I installed CUDA 7 and c/p-ed the cuDNN files there and also of course installed caffe as described - everything seems to be fine.

So now after running ./digits-devserver for the first time I got an error that the process wasn't permitted to write to /home/ubuntu/.digits/ - lazy me I "solved" this issue by simply setting the permissions for the folder and its content recursively to 777 (```chmod -R 777 ~/.digits```). 

Now after working my way through the initial questions of the config module I get another error:

```
libdc1394 error: Failed to initialize libdc1394

(process:1596): Gtk-WARNING **: Locale not supported by C library.
	Using the fallback 'C' locale.
```

For completeness sake I am adding the full session - I accepted all the suggested defaults:

```
ubuntu@ip-172-31-15-133:~/digits$ ./digits-devserver 
  ___ ___ ___ ___ _____ ___
 |   \_ _/ __|_ _|_   _/ __|
 | |) | | (_ || |  | | \__ \
 |___/___\___|___| |_| |___/

Welcome to the DIGITS config module.

Where is caffe installed?
	(enter "SYS" if installed system-wide)
	[default is /home/ubuntu/caffe]
(q to quit) >>> 
Accepting default value of "/home/ubuntu/caffe"

Attached devices:
Device #0:
	Name                 GRID K520
	Compute capability   3.0
	Memory               4.0 GB
	Multiprocessors      8


Input the IDs of the devices you would like to use, separated by commas, in order of preference.
	(enter "NONE" if you want to run in CPU-only mode)
	[default is 0]
(q to quit) >>> 
Accepting default value of "0"

Where would you like to store jobs?
	[default is /home/ubuntu/.digits/jobs]
(q to quit) >>> 
Accepting default value of "/home/ubuntu/.digits/jobs"

What is the minimum log level that you want to save to your logfile? [error/warning/info/debug]
	[default is info]
(q to quit) >>> 
Accepting default value of "info"

New config:
            gpu_list - 0
          secret_key - 79bb59415609390009ba204b
           log_level - info
            jobs_dir - /home/ubuntu/.digits/jobs
          caffe_root - /home/ubuntu/caffe

libdc1394 error: Failed to initialize libdc1394

(process:1596): Gtk-WARNING **: Locale not supported by C library.
	Using the fallback 'C' locale.

(digits-devserver:1596): Gdk-CRITICAL **: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Traceback (most recent call last):
  File "./digits-devserver", line 40, in <module>
    from digits.webapp import app, socketio, scheduler
  File "/home/ubuntu/digits/digits/webapp.py", line 11, in <module>
    import digits.scheduler
  File "/home/ubuntu/digits/digits/scheduler.py", line 18, in <module>
    from model import ModelJob, tasks as model_tasks
  File "/home/ubuntu/digits/digits/model/__init__.py", line 3, in <module>
    from job import ModelJob
  File "/home/ubuntu/digits/digits/model/job.py", line 4, in <module>
    from . import tasks
  File "/home/ubuntu/digits/digits/model/tasks/__init__.py", line 4, in <module>
    from caffe_train import CaffeTrainTask
  File "/home/ubuntu/digits/digits/model/tasks/caffe_train.py", line 5, in <module>
    import caffe
  File "/home/ubuntu/caffe/python/caffe/__init__.py", line 1, in <module>
    from .pycaffe import Net, SGDSolver
  File "/home/ubuntu/caffe/python/caffe/pycaffe.py", line 14, in <module>
    import caffe.io
  File "/home/ubuntu/caffe/python/caffe/io.py", line 2, in <module>
    import skimage.io
  File "/usr/local/lib/python2.7/dist-packages/skimage/io/__init__.py", line 15, in <module>
    reset_plugins()
  File "/usr/local/lib/python2.7/dist-packages/skimage/io/manage_plugins.py", line 89, in reset_plugins
    _load_preferred_plugins()
  File "/usr/local/lib/python2.7/dist-packages/skimage/io/manage_plugins.py", line 69, in _load_preferred_plugins
    _set_plugin(p_type, preferred_plugins['all'])
  File "/usr/local/lib/python2.7/dist-packages/skimage/io/manage_plugins.py", line 81, in _set_plugin
    use_plugin(plugin, kind=plugin_type)
  File "/usr/local/lib/python2.7/dist-packages/skimage/io/manage_plugins.py", line 251, in use_plugin
    _load(name)
  File "/usr/local/lib/python2.7/dist-packages/skimage/io/manage_plugins.py", line 295, in _load
    fromlist=[modname])
  File "/usr/local/lib/python2.7/dist-packages/skimage/io/_plugins/matplotlib_plugin.py", line 4, in <module>
    import matplotlib.pyplot as plt
  File "/usr/local/lib/python2.7/dist-packages/matplotlib/pyplot.py", line 109, in <module>
    _backend_mod, new_figure_manager, draw_if_interactive, _show = pylab_setup()
  File "/usr/local/lib/python2.7/dist-packages/matplotlib/backends/__init__.py", line 32, in pylab_setup
    globals(),locals(),[backend_name],0)
  File "/usr/local/lib/python2.7/dist-packages/matplotlib/backends/backend_gtk3agg.py", line 11, in <module>
    from . import backend_gtk3
  File "/usr/local/lib/python2.7/dist-packages/matplotlib/backends/backend_gtk3.py", line 55, in <module>
    cursors.MOVE          : Gdk.Cursor.new(Gdk.CursorType.FLEUR),
TypeError: constructor returned NULL
```

*Any ideas what to do or how to figure out what's the problem?*

Kind Regards

Raffael

**Comment by lukeyeager** [comment]
This looks like an installation issue. The [digits-users group](https://groups.google.com/d/forum/digits-users) is intended for these types of questions. Please ask your question there and I or somebody else will get back to you soon.

**Comment by joyofdata** [comment]
Okay, cool!

https://groups.google.com/forum/#!topic/digits-users/uvQpHooD6WY
