### ISSUE TITLE
Install error :Can`t run digits-devserver

### ISSUE THREAD

**Issue by mindcont** [NVIDIA/DIGITS#926]
I use Ubuntu 14.04 and [BVLC-Caffe](https://github.com/BVLC/caffe) with CUDA 7.5 + CuDNN 7.5 which is successfully installed,
```
pi@DeepMind:/usr/share/digits$ uname -a
Linux DeepMind 4.2.0-42-generic #49~14.04.1-Ubuntu SMP Wed Jun 29 20:22:11 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
```
When i install digits follow the [Ubuntu Installation](https://github.com/NVIDIA/DIGITS/blob/master/docs/UbuntuInstall.md) step by step,input this **sudo ./digits-server** , i got error like this:
```
pi@DeepMind:/usr/share/digits$ sudo ./digits-server
2016-07-24 18:47:45 [6335] [INFO] Starting gunicorn 17.5
2016-07-24 18:47:46 [6335] [ERROR] Connection in use: ('0.0.0.0', 34448)
2016-07-24 18:47:46 [6335] [ERROR] Retrying in 1 second.
2016-07-24 18:47:47 [6335] [ERROR] Connection in use: ('0.0.0.0', 34448)
2016-07-24 18:47:47 [6335] [ERROR] Retrying in 1 second.
2016-07-24 18:47:48 [6335] [ERROR] Connection in use: ('0.0.0.0', 34448)
2016-07-24 18:47:48 [6335] [ERROR] Retrying in 1 second.
2016-07-24 18:47:49 [6335] [ERROR] Connection in use: ('0.0.0.0', 34448)
2016-07-24 18:47:49 [6335] [ERROR] Retrying in 1 second.
2016-07-24 18:47:50 [6335] [ERROR] Connection in use: ('0.0.0.0', 34448)
2016-07-24 18:47:50 [6335] [ERROR] Retrying in 1 second.
2016-07-24 18:47:51 [6335] [ERROR] Can't connect to ('0.0.0.0', 34448)
```
![digits_error](https://cloud.githubusercontent.com/assets/13744152/17083544/39c28aae-51d7-11e6-9c8a-ca267bd3ec60.png)

than i use the dev mode ,by **sudo ./digits-devserver**
```
pi@DeepMind:/usr/share/digits$ sudo ./digits-devserver
/usr/local/lib/python2.7/dist-packages/flask/exthook.py:71: ExtDeprecationWarning: Importing flask.ext.socketio is deprecated, use flask_socketio instead.
  .format(x=modname), ExtDeprecationWarning
/usr/local/lib/python2.7/dist-packages/flask/exthook.py:71: ExtDeprecationWarning: Importing flask.ext.autodoc is deprecated, use flask_autodoc instead.
  .format(x=modname), ExtDeprecationWarning
/usr/local/lib/python2.7/dist-packages/flask/exthook.py:71: ExtDeprecationWarning: Importing flask.ext.wtf is deprecated, use flask_wtf instead.
  .format(x=modname), ExtDeprecationWarning
Traceback (most recent call last):
  File "./digits-devserver", line 44, in <module>
    from digits.webapp import app, socketio, scheduler
  File "/usr/local/lib/python2.7/dist-packages/gevent/builtins.py", line 93, in __import__
    result = _import(*args, **kwargs)
  File "/usr/share/digits/digits/webapp.py", line 45, in <module>
    import digits.views
  File "/usr/local/lib/python2.7/dist-packages/gevent/builtins.py", line 93, in __import__
    result = _import(*args, **kwargs)
  File "/usr/share/digits/digits/views.py", line 270, in <module>
    app.register_error_handler(code, handle_error)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1186, in register_error_handler
    self._register_error_handler(None, code_or_exception, f)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 65, in wrapper_func
    return f(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1201, in _register_error_handler
    exc_class, code = self._get_exc_class_and_code(code_or_exception)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1121, in _get_exc_class_and_code
    exc_class = default_exceptions[exc_class_or_code]
KeyError: 300
```
and run **digits-test**，the result is  : 
```
======================================================================
ERROR: Failure: KeyError (300)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/nose/loader.py", line 411, in loadTestsFromName
    addr.filename, addr.module)
  File "/usr/lib/python2.7/dist-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/usr/lib/python2.7/dist-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/usr/share/digits/digits/test_views.py", line 10, in <module>
    import webapp
  File "/usr/local/lib/python2.7/dist-packages/gevent/builtins.py", line 93, in __import__
    result = _import(*args, **kwargs)
  File "/usr/share/digits/digits/webapp.py", line 45, in <module>
    import digits.views
  File "/usr/local/lib/python2.7/dist-packages/gevent/builtins.py", line 93, in __import__
    result = _import(*args, **kwargs)
  File "/usr/share/digits/digits/views.py", line 270, in <module>
    app.register_error_handler(code, handle_error)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1186, in register_error_handler
    self._register_error_handler(None, code_or_exception, f)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 65, in wrapper_func
    return f(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1201, in _register_error_handler
    exc_class, code = self._get_exc_class_and_code(code_or_exception)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1121, in _get_exc_class_and_code
    exc_class = default_exceptions[exc_class_or_code]
KeyError: 300

----------------------------------------------------------------------
Ran 391 tests in 10.326s

FAILED (SKIP=4, errors=10)
```
**is there anybody with the same error like me ,how do i solve this problem? 
Thanks a lot !**

**Comment by mindcont** [comment]
**Update error**
```
root@DeepMind:/usr/share/digits# ./digits-devserver
/usr/local/lib/python2.7/dist-packages/flask/exthook.py:71: ExtDeprecationWarning: Importing flask.ext.socketio is deprecated, use flask_socketio instead.
  .format(x=modname), ExtDeprecationWarning
The gevent-socketio package is incompatible with this version of the Flask-SocketIO extension. Please uninstall it, and then install the latest version of python-socketio in its place.

```
After fixed some conflicts , i only got the one

>  **The gevent-socketio package is incompatible with this version of the Flask-SocketIO extension. Please uninstall it, and then install the latest version of python-socketio in its place.**

```
root@DeepMind:/usr/share/digits# pip uninstall gavent-socketio
Cannot uninstall requirement gavent-socketio, not installed
```
But not installed ?

**Comment by mindcont** [comment]
Has been solved, found the cause of the problem is my version of the Flask is higher than the set version (0.10.1) specifie by  in file [requirements.txt](https://github.com/NVIDIA/DIGITS/blob/master/requirements.txt) 

```
 pip list
```
**Fixed by input :** 
```
sudo pip uninstall Flask
sudo pip install Flask-0.10.1
```
