### ISSUE TITLE
Network visualization not working (Caffe)

### ISSUE THREAD

**Issue by enoonIT** [NVIDIA/DIGITS#935]
Using the latest version of digits, whenever I try to visualize a network I get:

```
500: INTERNAL SERVER ERROR
'module' object has no attribute 'poll'
```
![screenshot from 2016-07-27 12 20 47](https://cloud.githubusercontent.com/assets/7884236/17172280/91260888-53f4-11e6-8b89-eb759e48a69e.png)

**Comment by lukeyeager** [comment]
Works for me. I bet this is some sort of library version mismatch. Can you run the server in debug mode to get a more detailed error message?

    ./digits-devserver --debug

**Comment by mingtop** [comment]
Traceback (most recent call last):
  File "/home/jamin/anaconda/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jamin/anaconda/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/jamin/git/DIGITS/digits/webapp.py", line 67, in decorated
    return f(*args, **kwargs)
  File "/home/jamin/git/DIGITS/digits/model/views.py", line 113, in visualize_network
    ret = fw.get_network_visualization(flask.request.form['custom_network'])
  File "/home/jamin/git/DIGITS/digits/frameworks/caffe_framework.py", line 131, in get_network_visualization
    return ''
  File "/home/jamin/git/caffe/python/caffe/draw.py", line 204, in draw_net
    return get_pydot_graph(caffe_net, rankdir).create(format=ext)
  File "/home/jamin/anaconda/lib/python2.7/site-packages/pydot.py", line 1879, in create
    stdout_data, stderr_data = p.communicate()
  File "/home/jamin/anaconda/lib/python2.7/subprocess.py", line 800, in communicate
    return self._communicate(input)
  File "/home/jamin/anaconda/lib/python2.7/subprocess.py", line 1417, in _communicate
    stdout, stderr = self._communicate_with_poll(input)
  File "/home/jamin/anaconda/lib/python2.7/subprocess.py", line 1447, in _communicate_with_poll
    poller = select.poll()
AttributeError: 'module' object has no attribute 'poll'

**Comment by gheinrich** [comment]
Hello @mingtop do you have Pydot 1.0.28 as recommended in [requirements.txt](https://github.com/NVIDIA/DIGITS/blob/v4.0.0/requirements.txt#L16).

**Comment by mingtop** [comment]
Thank you very much!!

**Comment by lukeyeager** [comment]
I'm just curious - did you have a newer version of pydot that caused the problem?

**Comment by mingtop** [comment]
@lukeyeager  yes, change to the certain version by pip install pydot=1.0.*.
