### ISSUE TITLE
Object Detection: Kitti Script does not work

### ISSUE THREAD

**Issue by PatrickChrist** [NVIDIA/DIGITS#946]
Hey Digits-Team,

I tried to follow your tutorial on object detection and encountered the following problem while creating the LMDB from KITTI Dataset which have been processed using the https://github.com/NVIDIA/DIGITS/blob/master/examples/object-detection/prepare_kitti_data.py script. The files exist in this directory and are not corrupted. If i try to create a LMDB from KITTI Dataset without your script it works, however not having the same train/val spilt and therefore not possible to reproduce your experiment.

Would be nice if you could look into this.
Thanks,
Patrick

Error Log from Digits

2016-08-01 15:54:57 [ERROR] IOError:
Traceback (most recent call last):
File "/root/digits/tools/create_generic_db.py", line 458, in <module>
args['stage']
File "/root/digits/tools/create_generic_db.py", line 423, in create_generic_db
label_encoding)
File "/root/digits/tools/create_generic_db.py", line 276, in create_db
entry_ids = extension.itemize_entries(stage)
File "/root/digits/digits/extensions/data/objectDetection/data.py", line 188, in itemize_entries
self.load_ground_truth(self.train_label_folder)
File "/root/digits/digits/extensions/data/objectDetection/data.py", line 213, in load_ground_truth
datasrc.load_gt_obj()
File "/root/digits/digits/extensions/data/objectDetection/utils.py", line 178, in load_gt_obj
with open( os.path.join(self.label_dir, label_file), 'rb') as flabel:
IOError: [Errno 2] No such file or directory: u'/data/kitti/kitti-data/train/labels/004074.txt'

**Comment by gheinrich** [comment]
I assume you verified that `/data/kitti/kitti-data/train/labels/004074.txt` exists and is reachable?

**Comment by lukeyeager** [comment]
`/data/` isn't an external HDD or anything weird like that?

**Comment by lukeyeager** [comment]
@PatrickChrist any update?

**Comment by JulyUp** [comment]
@gheinrich Can you tell me when and where the funtion "task_arguments" in module "torch_train.py" is called?

**Comment by lukeyeager** [comment]
^ answered at https://github.com/NVIDIA/DIGITS/issues/979#issuecomment-240464706

**Comment by lukeyeager** [comment]
Closing due to lack of response.

**Comment by PeterSprague** [comment]
I'm getting a very similar error.  Item exists, built with supplied python script.

Any solution?

`libdc1394 error: Failed to initialize libdc1394
2017-04-19 19:12:37 [ERROR] IOError:
Traceback (most recent call last):
File "/usr/local/lib/python2.7/dist-packages/digits/tools/create_generic_db.py", line 467, in <module>
args['stage']
File "/usr/local/lib/python2.7/dist-packages/digits/tools/create_generic_db.py", line 432, in create_generic_db
force_same_shape)
File "/usr/local/lib/python2.7/dist-packages/digits/tools/create_generic_db.py", line 283, in create_db
entry_ids = extension.itemize_entries(stage)
File "/usr/local/lib/python2.7/dist-packages/digits/extensions/data/objectDetection/data.py", line 185, in itemize_entries
self.load_ground_truth(self.train_label_folder)
File "/usr/local/lib/python2.7/dist-packages/digits/extensions/data/objectDetection/data.py", line 210, in load_ground_truth
datasrc.load_gt_obj()
File "/usr/local/lib/python2.7/dist-packages/digits/extensions/data/objectDetection/utils.py", line 178, in load_gt_obj
with open( os.path.join(self.label_dir, label_file), 'rb') as flabel:
IOError: [Errno 2] No such file or directory: u'/data/kitti/kitti-data/train/labels/003225.txt'`

**Comment by PeterSprague** [comment]
Suspect that the absolute address symlinks produced by the script, when run in a Docker volume create the error.

Tested access to a couple of label files from inside a container.  Revised symlinks are indeed readable from container, while originals are not.

Will see about adjusting the script to suit my situation.

**Comment by baloodevil** [comment]
@PeterSprague's solution worked.  It is misleading that the symlink files appear, but if you bash into the docker image, you'll notice that the symlink label txt files are in red, whereas when you view them when not in docker bash, they are normal.  This shows that the symlinks are invalid within the context of the docker image.  So if you are running this inside docker, you need the `./prepare_kitti_data.py --no-symlinks`  The instructions should be edited to include this detail.

**Comment by TheMikeyR** [comment]
Can confirm @PeterSprague solution worked when running digits inside an nvidia-docker container.

**Comment by JadBatmobile** [comment]
Just to be clear. 
Do i run the ./prepare_kitti_data.py --no-symlinks in my host space?

Then i create a bindmount docker container to link it into the docker space for utilization with DIGITS?

**Comment by JadBatmobile** [comment]
edit: 
Yea thats the way
